### ISSUE TITLE
Rust?

### ISSUE THREAD

**Issue by manuel-uberti** [Wilfred/remacs#1]
Sorry, this is not an issue, just a question out of curiosity: does that _r_ before _emacs_ mean you're about to do something in Rust with this repo?

I'll be VERY interested in this. :-)

**Comment by manuel-uberti** [comment]
Ok, I was too quick, the README explains it all.

**Comment by ninrod** [comment]
Wait, what? I did not get it even from reading the readme. Do you want to build emacs with rust?

**Comment by Wilfred** [comment]
I've fleshed out the README.md, and just written an announcement blog post: http://www.wilfred.me.uk/blog/2017/01/11/announcing-remacs-porting-emacs-to-rust/
