### ISSUE TITLE
add patches from the "mac" window system (as opposed to the "ns" window system)

### ISSUE THREAD

**Issue by glyph** [Wilfred/remacs#10]
Although it has a checkered history (it started out as a Carbon port) the "mac" window system actually is a much nicer experience on OS X.  Proper support for digraphs, emoji, input methods, smooth scrolling, native menu search, and a host of other features.  See here for more details: https://bitbucket.org/mituharu/emacs-mac/overview

**Comment by Wilfred** [comment]
I don't have really have a mac to test on, so this isn't something I'm going to spend time on. I'm very happy to take PRs for this though.

**Comment by shaleh** [comment]
Should this still be open?

**Comment by Wilfred** [comment]
Probably not. If anyone would like to submit pull requests from the emacs-mac, those would still be very welcome though :)
