### ISSUE TITLE
Cursor doesn't blink

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/remacs#1029]
When I start Remacs with `-Q`, the cursor blinks once and then stays dark, that is, it doesn't continue blinking.

**Comment by nickdrozd** [comment]
The cursor also disappears when it moves, as with <kbd>C-f</kbd>, etc.

**Comment by shaleh** [comment]
Ya'll will get tired of me saying it....

`git bisect` and report where the problem starts. Even if you cannot fix it due to time or skill. Just identifying the root commit is a big big help.
