### ISSUE TITLE
Automatically update rustfmt-preview

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#1051]
It's currently necessary to manually run `rustup component add rustfmt-preview` after we updated the rust version.

**Comment by shaleh** [comment]
This is a `rustup` bug IMHO. `rustup update` does not work.

**Comment by brotzeit** [comment]
Yeah I thought so. I leave it open until this is fixed.

**Comment by brotzeit** [comment]
I will document this in the wiki.
