### ISSUE TITLE
Build fails when libxml2 library is absent

### ISSUE THREAD

**Issue by nitishch** [Wilfred/remacs#1075]
In case `libxml2` library is not installed, `./configure` step figures the library to be absent and as far as I understand, the corresponding C code is not built using `#define`s. But Rust code uses methods `init_libxml2_functions` in `xml.rs` file anyway and this leads to the compilation error -

```
error[E0432]: unresolved imports `crate::remacs_sys::init_libxml2_functions`, `crate::remacs_sys::parse_region`
 --> src/xml.rs:9:18
  |
9 |     remacs_sys::{init_libxml2_functions, parse_region},
  |                  ^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^ no `parse_region` in `remacs_sys`. Did you mean to use `write_region`?
  |                  |
  |                  no `init_libxml2_functions` in `remacs_sys`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `remacs`.
```

Conditional compilation has to be propagated to Rust code too.

**Comment by db48x** [comment]
That's correct. You can add `#[cfg(have_libxml2)]` (or whatever name you like) to `src/xml.rs`, and then arrange for `src/Makefile.in` to run cargo with the option to define that feature whenever appropriate.
