### ISSUE TITLE
Thoughts on porting the regex engine

### ISSUE THREAD

**Issue by cpitclaudel** [Wilfred/remacs#11]
Hi there,

This is a cool project! There was recently some discussion about changing Emacs' regex engine, so I thought I'd post the [link](https://lists.gnu.org/archive/html/emacs-devel/2016-12/msg00622.html) here.  The TL;DR is that a major difficulty lies in Emacs' use of a gap buffer, a structure that few regex-parsing libraries support.

Good luck!

**Comment by ahmadfalhoti** [comment]
Top team

**Comment by Wilfred** [comment]
Thanks! We don't yet have Rust-based string support, but this is something I'm really keen to explore in future.

I don't think this issue has anything actionable in it, so I'm going to close it.
