### ISSUE TITLE
elisp-fun: base64-encode-string optional arg NO-LINE-BREAK is inverted

### ISSUE THREAD

**Issue by 2mc** [Wilfred/remacs#1125]
As the doc-string for fun

    (base64-encode-string STRING &optional NO-LINE-BREAK)

has it:

    Optional second argument NO-LINE-BREAK means do not break long lines into shorter lines.

**the actual REmacs implementation does exacly the opposite:**

#+begin_src emacs-lisp
  (base64-encode-string (make-string 200 ?x) t)
#+end_src

#+RESULTS:
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=

#+begin_src emacs-lisp
  (base64-encode-string (make-string 200 ?x))
#+end_src

#+RESULTS:
: `eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=`

**But it should be like in Emacs:** 

#+begin_src emacs-lisp
  (base64-encode-string (make-string 200 ?x) t)
#+end_src

#+RESULTS:
: 
`eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=`

#+begin_src emacs-lisp
  (base64-encode-string (make-string 200 ?x))
#+end_src

#+RESULTS:
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4
: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHg=

**Comment by shaleh** [comment]
The `no_line_break` parameter to `base64-encode-string` is supposed to be negated and is not. It is a one character change for anyone who has the time.

**Comment by shaleh** [comment]
Thank you @2mc for noticing. We should improve our unit tests for this function.
