### ISSUE TITLE
delete-frame is not an interactive command

### ISSUE THREAD

**Issue by 2mc** [Wilfred/remacs#1134]
Contrary to Emacs, `delete-frame` appears not to be an interactive command.

Because of this, when triggering the standard key-binding `C-x 5 0,` REmacs throws the error

    wrong-type-argument commandp delete-frame

and does not delete the frame.

**Comment by brotzeit** [comment]
Thanks for the bug report. The intspec in the `lisp_fn` macro is missing. Want to give it a try ?

**Comment by brotzeit** [comment]
You just have to add `intspec = ""`.
