### ISSUE TITLE
build.rs fails with "no such file or directory" error

### ISSUE THREAD

**Issue by agraven** [Wilfred/remacs#1140]
Building fails with a panic in build.rs with a panic, giving the message
```
thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
```

The relevant line in the stack trace is `9: build_script_build::main`. It for some reason does not print which line number the error occurs in.

I am running Ubuntu Comsic (18.10), and gcc version 8.2.0. I did not give configure any arguments, but I did supply make with the argument `EMACS_CFLAGS:="-Isrc -isystem /usr/include/c++/8/tr1"`, since otherwise it failed with the error of not being able to find `stdbool.h`

**Comment by agraven** [comment]
I added the details to the original post.

**Comment by shaleh** [comment]
There is also this noise which needs to be cleaned up when using the new gcc.

```
cc1: warning: -Wabi won't warn about anything [-Wabi]
cc1: note: -Wabi warns about differences from the most up-to-date ABI, which is also used by default
cc1: note: use e.g. -Wabi=11 to warn about changes from GCC 7
```

**Comment by shaleh** [comment]
I cannot reproduce the failure in a Docker container. #1141 has the updates needed to make a Cosmic based container.

**Comment by shaleh** [comment]
I just saw this failure on a Debian machine that I upgraded from Stretch to unstable aka not quite Buster. Have not had a chance to debug it yet.

I also saw that we still fail to always detect clang during configure. I needed to install libclang-dev.

**Comment by shaleh** [comment]
I installed the `clang-7` package and poof, it worked.

**Comment by agraven** [comment]
This fixed it for me as well. I suppose `clang-7` should be added to the list of required packages in README.md then?

**Comment by shaleh** [comment]
Should we close this @agraven or is there something else we should fix?

**Comment by agraven** [comment]
No, the solution has been found, so I'm closing it.
