### ISSUE TITLE
'assertion failed: buffer_ref.beg() <= charpos && charpos <= buffer_ref.z()', src/marker.rs:618:5

### ISSUE THREAD

**Issue by gaak99** [Wilfred/remacs#1145]
Twas doing some ```helm``` I think...

not running with ```RUST_BACKTRACE=1``` so no backtrace of note and no core file.

```
git log --oneline HEAD|head -1
de43398 Updated Mojave build instructions for libxml2 (#1129)
```

**Comment by gaak99** [comment]
Am now running with ```RUST_BACKTRACE=1``` and will try to reproduce (or at least remember the sequence of ops to trigger assertion).

**Comment by shaleh** [comment]
This has been something of a ghost lately. Recompiling or just running again has resolved it. If you can find a reproducible case that would be super helpful.

**Comment by brotzeit** [comment]
I'm optimistic that the fix works.
