### ISSUE TITLE
Progress indicator in README

### ISSUE THREAD

**Issue by siddharthist** [Wilfred/remacs#115]
It'd be awesome to have a high-level overview of how much is done in the README for folks that are just watching this project :)

**Comment by Wilfred** [comment]
It's a nice idea, but I don't really think there's any good metric we can use. Lines of C code? Number of elisp primitives in Rust?

In the meantime, I am writing regular status updates on my blog, and these are also being posted on [r/remacs on Reddit](https://www.reddit.com/r/remacs/).
