### ISSUE TITLE
Implement LispSymbolOrString type

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/remacs#1209]
There are a few functions that accept either strings or symbols, like `string-lessp`, `string-equal`, and `intern-soft`. Currently these all take `LispObject` as argument and then cast them with `LispObject::symbol_or_string_as_string`. Example:

```rust
#[lisp_fn]
pub fn string_lessp(string1: LispObject, string2: LispObject) -> bool {
    let s1 = LispObject::symbol_or_string_as_string(string1);
    let s2 = LispObject::symbol_or_string_as_string(string2);

    s1.as_slice() < s2.as_slice()
}
```

This would be better handled with a dedicated `LispSymbolOrString` type, giving something like:

```rust
#[lisp_fn]
pub fn string_lessp(string1: LispSymbolOrString, string2: LispSymbolOrString) -> bool {
    string1.as_slice() < string2.as_slice()
}
```

Implement this type, along with whatever functions are required (`From<LispSymbolOrString> for LispObject`, etc).

**Comment by shaleh** [comment]
We should also define `From<LispSymbolOrString> for LispStringRef` and also for `LispSymbolRef`. This will simplify the call sites. When a dev calls `string_lessp` they can call it like `string_lessp(string1.into(), string2.into())`.

**Comment by nickdrozd** [comment]
`process.rs` also has some places that could use a union type of some kind.

```
/// Return the process named NAME, or nil if there is none.
#[lisp_fn(name = "get-process", c_name = "get_process")]
pub fn get_process_lisp(name: LispObject) -> LispObject {
    if name.is_process() {
        name
    } else {
        name.as_string_or_error();
        cdr(assoc(name, unsafe { Vprocess_alist }, Qnil))
    }
}
```
