### ISSUE TITLE
describe-key fails

### ISSUE THREAD

**Issue by krobelus** [Wilfred/remacs#1211]
Entering `C-h k C-n` on a clean build gives me this message:

`file-name-sans-extension: Wrong type argument: stringp, (require . elec-pair)`

Does anyone have the same issue?

**Comment by shaleh** [comment]
I have not seen `describe-key` fail. If you can reduce this to a reproducible test case let us know. Hopefully we can include it for future test runs.

**Comment by krobelus** [comment]
I built it in the docker container, then it worked.
It keeps working now, also without docker.
There was probably some weird interaction with my system, sorry for the noise. Closing this for now, if this occurs again I'll see why so.
