### ISSUE TITLE
Port str2sig to Rust

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#122]
It's a simple C library, converting signal numbers to strings.

**Comment by crlf0710** [comment]
To move this to the Rust side maybe we should find a way to deal with the posix SIG* macros - rust doesn't have a good way to deal with them now...

**Comment by barrucadu** [comment]
I'm pretty new to Rust, so there may be another way to approach this, but it seems to me that there are two ways to handle the `SIG*` macros from the Rust side:

1. Use CPP in str2sig.rs, and run `cpp` over the file before compilation.
2. Write a small C file to expose the macro values as ints: something like this for every signal:

    ```c
    #ifdef SIGHUP
        const int sighup = SIGHUP;
        const int has_sighup = 1;
    #else
        const int sighup = 0;
        const int has_sighup = 0;
    #endif
    ```

Neither feels very satisfactory, but I'm willing to give this a go if there's a preference for which approach to take (or if anyone has a pointer to a better way).

**Comment by Wilfred** [comment]
@barrucadu if you fancy writing a PR, that would be great! We can help you if you get stuck.

Looks like libc has constants defined for the different signals: https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/src/libc/unix/notbsd/mod.rs.html#289 , but I can't see any nice way of going from signal number to string.

I'm wondering whether we can just get away with a simple case statement. We don't need to support older systems like AIX, BeOS or HP-UX. Looking at signal related libraries on crates.io, others seems to just do an enumeration: https://github.com/swizard0/rust-simple-signal/blob/4be2783f4ec068e874e10b351aef949b66bae8a5/src/lib.rs#L14 or we could even use the enum here: http://adjivas.github.io/sig/sig/ffi/enum.Sig.html

Do you have a preference?

**Comment by barrucadu** [comment]
I've copied the enum from that sig crate, I didn't use the crate directly because I'd have had to implement a lookup table for the names anyway (might be a nice addition to that crate actually). I've got a dummy implementation which just returns `-1` from both `sig2str` and `str2sig` compiling and linking.

I'll ask if I need any more help, and open a PR when I'm ready for some code review.
