### ISSUE TITLE
Add a team commit guideline, don't merge failing builds to master

### ISSUE THREAD

**Issue by jasonm23** [Wilfred/remacs#123]
I don't know how many collaborators have a push bit, but you should seriously consider setting a guideline to not merge / push to master when a build is failing.

**Comment by Wilfred** [comment]
We have CONTRIBUTING.md to clarify this. It's not actually possible to merge to master if the build is failing.

The build failed on master yesterday due to another unreliable test :/. I'm going to skip it.
