### ISSUE TITLE
Update to latest base64 crate

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#1241]
Today we are able to use a `Config` work around to set the line end characters and expected line length. However the current version of base64 no longer supports this.

Can we just use base64 as is?
Do we try to send a PR?
Do we need to investigate adding a vendor/ area so we can keep old versions of crates we use around?

**Comment by daichimukai** [comment]
According to the [Release note of the base64 crate](https://github.com/alicemaz/rust-base64/blob/master/RELEASE-NOTES.md), line wrapping had pulled out into [line-wrap](https://crates.io/crates/line-wrap) crate and
strip whitespace option is dropped but can be achived one filter() function.

So I tried to use base64 as-is as a first option, and it seems to work fine. The code is [here](https://github.com/daichimukai/remacs/commit/b923da8eed176a3476ad22d9a523cc818ab68ade).

**Comment by daichimukai** [comment]
I did :wink:
