### ISSUE TITLE
Please setup Patreon so people can donate

### ISSUE THREAD

**Issue by codygman** [Wilfred/remacs#125]
Hi, I support Redox (Rust kernel) on Patreon. I'd like to support Remacs as well.

**Comment by Wilfred** [comment]
I'm flattered, but I'm not looking for donations I'm afraid. Patches and bug reports are the best way to contribute :)

**Comment by codygman** [comment]
I have no time and get paid well using emacs. Remacs could make my job
easier. Money is all I currently have to give right now ;)
