### ISSUE TITLE
Set up a 'workspace' in our Cargo config

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#1254]
This will enable more cargo tools to work with our crates.

https://learning-rust.github.io/docs/d5.workspaces.html

**Comment by daichimukai** [comment]
TIL: a cargo workspace share its parent's profile (cf. [link](https://github.com/rust-lang/cargo/issues/3206)).

So just making `remacs-.*` crates as members might have some side effects.
* `remacs-macro` is ready. 
* `remacs-lib` and `remacs-util` has `lto = true`. I don't know how effective it is neither why we use it :sweat:. 
* `remacs-bindgen` is ..., I have no idea. Does it run before compiling all other Rust codes and not related with this issue?

Though, I report that just adding all of them as member had successfully ended building and testing on my local machine, while `cargo` complaining profiles will be shared, as expected :+1:.

**Comment by shaleh** [comment]
My understanding is the `lto=true` option is doing us nothing as long as remacs is compiled as a library. Once we are self hosting we can LTO everywhere. For now, that can be dropped.

The bindgen crate is a good question. However, we can mark crates as exempt from the work space. For MacOS we ought to do this for the unexec crate as well.

**Comment by daichimukai** [comment]
Sounds good, I'm testing changes on my machine. I will make PR later.
