### ISSUE TITLE
Building on mac fails

### ISSUE THREAD

**Issue by cyrillk** [Wilfred/remacs#127]
Hi,

I followed the instruction and tried to build the project. Unfortunately, the project build fails for me. Could you help me to sort it out?

```
^
4 warnings generated.
  CC       terminfo.o
  CC       lastfile.o
RUSTFLAGS= \
	cargo build  --manifest-path ../rust_src/Cargo.toml
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading lazy_static v0.2.2
 Downloading libc v0.2.17
   Compiling alloc_unexecmacosx v0.1.0 (file:///Users/kirill/develop/remacs/rust_src/alloc_unexecmacosx)
   Compiling lazy_static v0.2.2
   Compiling libc v0.2.17
error[E0554]: #[feature] may not be used on the stable release channel
 --> /Users/kirill/develop/remacs/rust_src/alloc_unexecmacosx/src/lib.rs:1:1
  |
1 | #![feature(allocator)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `alloc_unexecmacosx`.
```

To build it I run

```
$ ./autogen.sh
$ ./configure --enable-rust-debug --without-makeinfo
$ make
```

**Comment by pnkfelix** [comment]
Hi @cyrillk 

We don't support building `remacs` on the stable channel, because for Mac OS X we need a feature (overriding the low-level allocator used for Rust's heap-allocation) that is only available on the nightly channel.

Why do we need that feature? Because the way that Mac OS X's unexec support is implemented, it needs to intercept all calls to malloc/realloc/free and send them to a custom allocator that allows unexec.

The bug that uncovered this problem is #38; the PR that added the `#[allocator]` usage on Mac OS X is #112

**Comment by pnkfelix** [comment]
If you are using `rustup`, you can switch to the nightly Rust channel using: 
```
$ rustup default nightly
```

If you are not using `rustup`, then you can download one of the nightly versions of Rust here: https://www.rust-lang.org/en-US/other-installers.html

**Comment by cyrillk** [comment]
@pnkfelix Thank you. It seems to look a bit better. Though it fails for me in a different place now.

```
  CC       nsterm.o
nsterm.m:6844:10: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
  [NSApp registerServicesMenuSendTypes: ns_send_types
         ^
1 warning generated.
  CC       nsfns.o
  CC       nsmenu.o
  CC       nsselect.o
  CC       nsimage.o
make[1]: Circular bootstrap-emacs <- temacs dependency dropped.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../lisp update-subdirs
./temacs --batch  --load loadup bootstrap
make[1]: ./temacs: No such file or directory
make[1]: *** [bootstrap-emacs] Error 1
make: *** [src] Error 2
```

**Comment by CNBorn** [comment]
I had the exact same issue yesterday, thanks for pointing out to use the rust-nightly!

@cyrillk I think you'll need:
1. make sure you're running rust-nightly: `rustc --version`
2. `make clean` then `make` again.

btw I'm seeing this error now:

```
Processing header part...
Formatting translation rules...
  GEN      ../lisp/leim/quail/tsang-b5.el
Converting cangjie-table.b5 to tsang-b5.el...
Loading macroexp.elc...
Wrong type argument: arrayp, nil
make[2]: *** [../lisp/leim/quail/tsang-b5.el] Error 255
make[1]: *** [../lisp/leim/leim-list.el] Error 2
```

Don't know if anyone has idea what that is

**Comment by benjamreynolds** [comment]
Using rust nightly and starting from a `make clean` got the build to complete on my machine. (Lots of warnings, but I did get a working copy of emacs out of it) I do however get an error in the mini-buffer when I start the freshly built copy of emacs, but I dont know if that is because Im running it on mac or if there are just some incomplete stuff in this fork.

**Comment by Wilfred** [comment]
@benjamreynolds it should just work. Note that Remacs is based on Emacs master, ie Emacs 26, so you may have .elc files in your `~/.emacs.d` that need recompiling.

If `src/remacs -q` works, then the .elc files are probably to blame.

**Comment by benjamreynolds** [comment]
So the solution would be to do a `find ~/.emacs.d -name "*.elc" -type f -delete` to clear them out and then re-open remacs?

**Comment by Wilfred** [comment]
Yep, that should do the trick. If that doesn't fix it, please post the error from your minibuffer.

**Comment by benjamreynolds** [comment]
`Cannot open load file: No such file or directory, time-date`

If this matters at all, my emacs config is a symlinked directory into a dotfiles directory..

```
$ ls -lah
...
lrwxr-xr-x    1 me  staff    41B Jan  2 15:43 .emacs.d -> /Users/me/.dotfiles/emacs.d
...
```

I deleted all `.elc` files from both `~/.emacs.d` and `~/.dotfiles/emacs.d`

**Comment by cyrillk** [comment]
@CNBorn Thank you. `make clean` helped to solve the issue.

**Comment by Wilfred** [comment]
OK, since @cyrillk has managed to build OS X, I'm going to close this.

@CNBorn @benjamreynolds would you mind opening separate issues? If you're still seeing problems, I don't want them to get lost in this issue.
