### ISSUE TITLE
Remove SHA-224 API

### ISSUE THREAD

**Issue by briansmith** [Wilfred/remacs#128]
I suggest removing the SHA-224 API completely.  From searching the source code, it seems nothing actually uses it. Also #110 proposes switching to *ring*, which doesn't implement SHA-224 (because no real-world things use it, and because it is less secure than SHA-256, which is the minimum that people should be using these days).

**Comment by Wilfred** [comment]
I'm afraid that this is functionality exposed at the elisp level, so removing this would break backward compatibility.

The elisp docs do mention that SHA1 and older are insecure: https://www.gnu.org/software/emacs/manual/html_node/elisp/Checksum_002fHash.html (perhaps they could be clearer)

However, there are examples in the wild of users using the older hashes. [Here's an example of MD5](http://stackoverflow.com/q/26491305/509706) and [here's a popular Emacs writer demonstrating SHA224 in elisp](http://nullprogram.com/blog/2015/10/30/). 

I understand your concerns, but as a lesser used elisp implementation I don't think we're in a position to influence API. Breaking backwards compatibility risks hurting our initial experience for new users.

**Comment by briansmith** [comment]
Understandable, if your goal is 100% compatibility with Emacs then removing it doesn't make sense.
