### ISSUE TITLE
remacs just exits (no crash)

### ISSUE THREAD

**Issue by manfredlotz** [Wilfred/remacs#1283]
I have started remacs from the command line. It happens that it just exits without user intervention.

The last time it happened I saw this in the terminal where I previously started remacs:

```
End of buffer

[1]  + 2979 exit 255   remacs
```
Any idea what's going on?

**Comment by manfredlotz** [comment]
I played a bit and now it happened with: Beginning of buffer

**Comment by manfredlotz** [comment]
OK, I can reproduce it. 

I go to the beginning of the buffer and press the Up Arrow key, and remacs exits.

**Comment by shaleh** [comment]
https://github.com/emacs-mirror/emacs/blob/7960951d5df714957bcfff82df77a94a6ee8960b/src/keyboard.c#L1002 is the original C.

If looks like we dropped the '!' at the beginning of the 'if'.

**Comment by daichimukai** [comment]
Yes, I realized that few minutes ago. Making PR!

**Comment by daichimukai** [comment]
Fixed! Thank you for reporting @manfredlotz
