### ISSUE TITLE
Wrong type argument: windowp, nil

### ISSUE THREAD

**Issue by manfredlotz** [Wilfred/remacs#1287]
In org mode when defining a new task and then calling org-schedule I get the message
    Wrong type argument: windowp, nil

Instead a calendar buffer should show up where I can select the schedule date I want.

**Comment by manfredlotz** [comment]
In *Messages* the full message text is:

```
window-edges: Wrong type argument: windowp, nil
```

**Comment by shaleh** [comment]
https://www.gnu.org/software/emacs/manual/html_node/eintr/debug_002don_002dentry.html may be able to help you identify the culprit.

**Comment by shaleh** [comment]
Any chance this is related to your window fix @agraven?

**Comment by agraven** [comment]
I doubt it, the error is `windowp` and not `window-valid-p`

**Comment by shaleh** [comment]
I think we only have two candidates on the Rust side: From<LispObject> for LispWindowRef and window::as_minibuffer_or_error.

**Comment by manfredlotz** [comment]
I tried to debug but didn't find anything which was helpful

**Comment by agraven** [comment]
Can you give us the output in the `*Backtrace*` buffer after setting `debug-on-error` to `t` and then reproducing the error?

**Comment by manfredlotz** [comment]
When first debugging I tried (debug-on-enrty org-schedule). I had to type 'd' to often.

Ok, no only debug-on-error t and I get:

```
Debugger entered--Lisp error: (wrong-type-argument windowp nil)
  window-body-height(#<window 3 on *Backtrace*> t)
  window-edges(nil t)
  window-inside-edges()
  calendar-update-mode-line()
  calendar-generate-window(1 2019)
  calendar-basic-setup(nil)
  calendar()
  org-read-date(nil to-time nil nil nil nil)
  org-add-planning-info(scheduled nil closed)
  #f(compiled-function () #<bytecode 0x2af88cd>)()
  org--deadline-or-schedule(nil scheduled nil)
  org-schedule(nil)
  funcall-interactively(org-schedule nil)
  call-interactively(org-schedule nil nil)
  command-execute(org-schedule)
```

**Comment by nickdrozd** [comment]
It also triggers when doing autocomplete in the minibuffer, which actually makes this a pretty severe usability issue.

**Comment by agraven** [comment]
Looks like the culprit is `window-body-height`. Is the error reproducible in versions prior to the function being ported?

**Comment by shaleh** [comment]
`window-body-height` is quite simple. Also, the window is clearly not nil. This is quite interesting.

**Comment by nickdrozd** [comment]
`087f4691ee` works and `696434c3c9` doesn't (wrt this bug).

**Comment by shaleh** [comment]
Replace `body_height`'s implementation with a function which simply returns 30 and does not work. The error goes away.

**Comment by shaleh** [comment]
Found it.

`LispWindowRef::prev` turns the LispObject into a LispWindowRef without checking if the prev is NIL.
The original C code compares prev to FRAME_ROOT_WINDOW which are both LispObjects. The current code tries to turn both into LispWindowRef.
