### ISSUE TITLE
Add graph that shows remacs oxidation 

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#1313]
Like this https://i.redd.it/nmevcjpstd921.png

**Comment by shaleh** [comment]
Current code is in the remacs wiki git repo.

**Comment by jaccarmac** [comment]
We comparing against the last merged-in version of the GNU tree or the tip of mainline Emacs development?

**Comment by brotzeit** [comment]
I'd say we only use our repo for it.

**Comment by jaccarmac** [comment]
Ah, true for that graph. Was distracted by the existing code, but can start without messing with the existing graphs.

**Comment by shaleh** [comment]
The current code can compare ANY emacs or remacs tree. We could have it clone at the last synced emacs hash for instance. The reason it uses the emacs tree is we need a number for what was there versus what we have now. Some of this could be parsed and stored for later use.

**Comment by jaccarmac** [comment]
Was just wondering about regenning the existing pie charts and wondering what the comparison is to. But didn't end up refreshing those anyway :)

Made some horrible hacks on top of the script that generated the image from Reddit and added the PNG to the wiki. Want the author's blessing and less hacks before I push it though. Notably it requires `git clean -fxd`-nuking the Remacs tree to prevent the script from looking for commits all the way back to the dawn of time.

**Comment by jaccarmac** [comment]
[link for the lazy](https://raw.githubusercontent.com/wiki/Wilfred/remacs/burndown.png)
