### ISSUE TITLE
'lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke' test is inconsistent. 

### ISSUE THREAD

**Issue by DavidDeSimone** [Wilfred/remacs#133]
Between https://github.com/Wilfred/remacs/pull/116, https://github.com/Wilfred/remacs/pull/131, and https://github.com/Wilfred/remacs/pull/106, there have been several PR's opened that seem to inconsistently fail this particular test. 

I think we should either investigate whats going on here, or remove this test from the list required to pass for PR submission.

**Comment by Wilfred** [comment]
I think we should do both: skip the test, but investigate further. I've been tracking noisy tests in #99.

**Comment by Wilfred** [comment]
Aha, I recall this test. It only fails when you run tests in parallel (e.g `make -j 3 check`). We don't do this any more, so this test should now be passing.

If old branches are rebased onto master (or merge master in), then they should go green.

I think this is already fixed, but do shout if that's not the case.
