### ISSUE TITLE
Keep gnulib (lib/) and remacs (src/) code apart.

### ISSUE THREAD

**Issue by crlf0710** [Wilfred/remacs#134]
Shall we keep the gnulib library (lib/), which may ship alone as a separate crate in theory apart from those code of Emacs itself?

**Comment by DavidDeSimone** [comment]
So as part of https://github.com/Wilfred/remacs/pull/116, I am replacing a function implemented in lib/ with a rust implementation. It seems logical for me to implement a remacs-lib/ cargo project as part of that PR.

I notice that we recently added a remacs-sys/ project. Is there documentation on what should go in remacs-sys vs src? Will adding remacs-lib be redundant now that we have remacs-sys? What do you think @jeandudey?

**Comment by jeandudey** [comment]
I think that `remacs-sys` shouldn't be mixed with `gnulib`, it should only have code that comes from emacs, i think that another crate is needed for that specific purpose.

**Comment by Wilfred** [comment]
`remacs-sys` is an FFI library I think: it provides Rust type definitions and declarations of functionality defined in the C code. We should definitely document this.

When we replace code in lib/ with pre-existing Rust crates, we just need to add the bits required to make Emacs use the Rust crates. I don't think having a rust-lib directory will make that any easier. Do you see any benefit from it? I'm open to persuasion.

**Comment by DavidDeSimone** [comment]
Sorry for the delayed response @Wilfred, I've been a little swamped with an upcoming title release at work and I haven't had a ton of time for open source contributions.

So the only argument I can make for a rust-lib crate is that I feel it will fit in with the current build system a little better then alternative solutions. We can keep lib-src/ a self contained module capable of being build with a single make step. For example, when replacing mkostemp with a rust alternative, we need to replace calls in both src/ and lib-src/ files with the rust implementation. This means when building lib-src/ we now need to link against the rust implementation.  I may be doing something stupid, but my initial attempt in doing this was throwing problems and linker errors. 

I may not not have a full understanding of the situation, but it seems like if we rustify code that lives in lib-src/ and is used by src/ and lib-src/, the path of least resistance may be to make a lib-src/ crate.

**Comment by Wilfred** [comment]
OK, so the rust-lib crate is for code that:

* is generic functionality (i.e. not specific to elisp)
* self-contained functionality (so code can depend on it in isolation)

Is that a good summary? I don't want to just say "use the same directory structure as before" because that's not helpful to new contributors after we port things to Rust.

If that summary sounds good to you, I propose we just put a docstring saying something like this at the top of remacs-lib/lib.rs :)

**Comment by DavidDeSimone** [comment]
That sounds like a good summary to me.
