### ISSUE TITLE
Check if I am running remacs in elisp

### ISSUE THREAD

**Issue by PythonNut** [Wilfred/remacs#137]
How can I determine if my config is running in `remacs` in elisp? I'd like to use the fix from #92, but I'd prefer to do that only when actually running `remacs`.

**Comment by Wilfred** [comment]
Can you inspect `invocation-name`? I suppose `command-line-args` would work too, but I'd be tempted to write:

```emacs-lisp
(when (string= invocation-name "remacs")
 ...)

**Comment by PythonNut** [comment]
Ah that works wonderfully. I looked for something like that for about 20 minutes or so, but gave up. :/

Anyway, that looks like the perfect solution.

**Comment by Wilfred** [comment]
`M-x aprops-value RET remacs` :)
