### ISSUE TITLE
RFC: Use Rust codegen

### ISSUE THREAD

**Issue by jeandudey** [Wilfred/remacs#138]
About the use of Rust codegen
-------------------------------------------

### Description
I've thinked that we could use nigthtly **Rust** features to make **Remacs**
development and porting easier. I was inspired how the *rocket.rs* crate
handled the *HTTP* request using Rust attributes, it looks something like this:

```rust
#[get("/")]
fn index() -> &'static str {
   "Hello, world!"
}
```

I think Remacs could do something similar and have a `defun` or a
`lisp_function` attribute to generate FFI code, also it would solve the problem
of having two lisp object types, because the generated code can hide all the
details of having a FFI `Lisp_Object` type.

An example of a native lisp function would look like this in Rust:

```rust
#[lisp_function(name = "symbolp", min = 1)]
#[lisp_doc("Return t if OBJECT is a symbol")]
#[lisp_doc("(fn OBJECT)")]
fn symbolp(object: LispObject) -> LispObject {
    if object.is_symbol() {
        LispObject::constant_t()
    } else 
        LispObject::constant_nil()
    }
}
```

And the generated code would look something like this:

```rust
lazy_static! {
    pub static ref Ssymbolp: remacs_sys::Lisp_Subr = remacs_sys::Lisp_Subr {
        header: VectorlikeHeader {
            size: ((lisp::PvecType::PVEC_SUBR as libc::c_int) << lisp::PSEUDOVECTOR_AREA_BITS) as libc::ptrdiff_t,
        },
        function: Fsymbolp as *const libc::c_void,
        min_args: 1,
        max_args: 1,
        symbol_name: b"symbolp\0".as_ptr(),
        intspec: std::ptr:null(),
        doc: b"Return t if OBJECT is a symbol\n(fn OBJECT)".as_ptr(),
    }
}

pub extern "C" Fsymbolp(p0: remacs_sys::Lisp_Object) -> remacs_sys::Lisp_Object {
    let p0 = LispObject::from_raw(p0);
    let ret = symbolp(p0);
    ret.to_raw()
}

fn symbolp(object: LispObject) -> LispObject {
    if object.is_symbol() {
        LispObject::constant_t()
    } else 
        LispObject::constant_nil()
    }
}
```

You will notice that there is an extra type in the `Fsymbolp` function, this is
used to keep the ABI compability with the **C** code.

### Implementation
First there are some requeriments for a function to use the attribute, first all of it's parameters and the return types *must* be a `LispObject`. Also the parameter limit is 6, because that is how `Lisp_Subr` is defined in C.

Also i think it would be good to hve the FFI code in a separate crate (maybe called `remacs-sys`) to decouple the FFI code.

On the `rustc` side i don't know how this could be done, some research needs to be made to make this possible on the Rust compiler side.

### Advantages
- It hides a lot of the FFI.
- Clean code.
- It will be more hard to make mistakes.
- Builds on Travis CI will be more faster because we don't need additional versions.

### Disadvantages
- This will require the use of nightly Rust, however we now are using it on
Mac OS X builds so this should be no problem.
- It will be a bit more difficult to debug because an extra call is made.
- The Rust nightly compiler API is unstable, it changes a lot, we will need to
stick to a specific nightly version and update the codegen code when a breaking
change happens on the `rustc` side.

### Alternatives
- Leave it as is.
- Wait for Rust to have an stable API for code generation.

#### My opinion
Having this feature is worth it because if the project needs to be cleaned up
this is the way to go.

**UPDATE:** `min` parameter is used to specify the minimum parameters the function
has, and the maximum is calculated.

**Comment by Wilfred** [comment]
Interesting idea! The example code is definitely elegant.

If we go this approach, there a few things we'll need to figure out:

* min and max arguments (as you mentioned) -- could just be another attribute if `min != max`.
* `Fsymbolp` only needs to be public if the remaining C code calls it directly. How do we ensure that only the necessary functions are made `pub`?
* After `Ssymbolp` is defined, we need to call `defsubr` on it during Emacs initialisation. How do we make this explicit? Readers can't see that `Ssymbolp` exists.
* The Emacs convention of `Ffoo`, `Sfoo` and `Qfoo` is not terribly pretty, but it does solve the issue of having both a variable and a function with the same name. If we define a function `foo`, what happens when we want a variable called `foo`?

**Comment by Wilfred** [comment]
> Builds on Travis CI will be more faster because we don't need additional versions.

Note that we can do this today if we want. We're currently building linux on Rust stable and beta, and OS X on nightly. We could change linux to just build on one Rust version if you think it's worthwhile. It's usually the OS X build that's slowest though, since there's a queue at peak times on Travis CI.

**Comment by Wilfred** [comment]
> Also i think it would be good to have the FFI code in a separate crate (maybe called remacs-sys) to decouple the FFI code.

This is a good idea, but we can do this regardless of when/if we do rust codegen.

**Comment by jeandudey** [comment]
> Fsymbolp only needs to be public if the remaining C code calls it directly. How do we ensure that only the necessary functions are made pub?

I think that can be solved using another attribute like `#[lisp_export]` and insert the proper `use` declaration automatically in the crate root.

> After Ssymbolp is defined, we need to call defsubr on it during Emacs initialisation. How do we make this explicit? Readers can't see that Ssymbolp exists.

Maybe this can be solved creating a `rust_init_syms` function automatically. Also i don't think that symbol export should be explicit at all, it should be hidden to avoid mistakes because is too easy to forgot a `defsubr` call.

> The Emacs convention of Ffoo, Sfoo and Qfoo is not terribly pretty, but it does solve the issue of having both a variable and a function with the same name. If we define a function foo, what happens when we want a variable called foo?

I don't think this should be a problem, maybe we could have a `static mut Vfoo: Lisp_Object = ??` and make a function that access it in a safe manner.

**Comment by jeandudey** [comment]
Closing since #181 was merged
