### ISSUE TITLE
Document the relationship between remacs-sys and remacs

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#157]
This is important for new contributors not familiar with this convention.

remacs-sys is FFI declarations, whereas actual functionality should go in remacs.

**Comment by ludwigpacifici** [comment]
Hello @Wilfred,

First time I look at this project. So I have some (beginner) questions:

- What kind of document is expected (code comment, `cargo doc`, etc.)?
- Where to write it?
- Where to find the information about the relationship between `remacs-sys` and `remacs`

**Comment by Wilfred** [comment]
Hi @ludwigpacifici! Welcome aboard :)

I think we just need a REAMDE.md in each directory. We have one in remacs-lib and remacs-macros, but nothing in remacs-sys.

Supporting `cargo doc` is a great idea too. We could add a summary of the README.md in each lib.rs file in remacs-sys, remacs-lib and remacs-macros.

remacs-sys contains FFI declarations. It contains Rust declarations of structs and functions that are defined on the C side so we can use them in Rust. Have a look at `remacs-sys/lib.rs` to see some examples.

**Comment by peter-b** [comment]
I think this should be closed because #301 was merged.

**Comment by Wilfred** [comment]
Aha, yep! :)
