### ISSUE TITLE
Keyboard input not recognized in graphical mode on OSX

### ISSUE THREAD

**Issue by nickjmeyer** [Wilfred/remacs#168]
I'm running OSX 10.12.4.  Everything compiles and all the tests pass.  When I run `./src/remacs -q` the gui is not responding to keyboard input.  I can see the characters printing in the console.  For example, if I type `asdf` into the gui, I"ll see `asdf` in the terminal (but not in the buffer) or if I try to move the cursor I'll see `^N` and `^P` in the terminal (but the cursor doesn't respond).  The only keyboard input that seems to be picked up is close.  If I run `C-x C-c` then the window will close.

I'll try and take a deeper look soon.  Though I just recently forked the repo, so it will most likely take me a bit to warm up to the code base.

**Comment by birkenfeld** [comment]
When you build a stock Emacs in the same way, does it behave normally?

**Comment by nickjmeyer** [comment]
Yes, that's correct.

**Comment by qezz** [comment]
I have had same issue until i tried to build .app via `./nextstep` and configure with

```bash
CC=$(which clang) ./configure --without-makeinfo --with-ns
```

So latest version works fine for me. (macOS 10.12.4)

**Comment by nickjmeyer** [comment]
I just tried that on 10.12.5 and I get the same result I had before.  All
key presses show up in the terminal as text rather than as input to the
emacs frame.

**Comment by xuchunyang** [comment]
The official GNU Emacs has the same issue. However, in my experience, to run GUI Application on macOS, the normal way is click the Application from the Finder or Dock or use the `open(1)` command, for example,

    $ open ~/src/remacs/nextstep/Emacs.app --args -Q

BTW, don't forget to run `make install` to finish building Emacs.app, which is not documented on README.md.

**Comment by nickjmeyer** [comment]
Ah that did it!  Thanks @xuchunyang.
