### ISSUE TITLE
Change EmacsInt to EMACS_INT

### ISSUE THREAD

**Issue by jeandudey** [Wilfred/remacs#172]
We should match the type names used in C for consistency. Also it's other types should be changed like: `EmacsUint`.

This shouldn't be too hard to do just change it in `build.rs` and do a find and replace on all files.

**Comment by porglezomp** [comment]
As someone who is not yet a contributor, but has been looking at the project and is interested in working with it, I disagree with this. It seems like it would be bad to make the quality of the Rust code suffer due to legacy concerns.

**Comment by jeandudey** [comment]
@porglezomp what i mean by changing `EmacsInt` to `EMACS_INT` is to rename it only on the `remacs-sys` crate, and then add a module that wraps `EMACS_INT` to `EmascInt` (a type definitions) and it's constants (like `std::u32`).

**Comment by shaleh** [comment]
Is this still a goal?

**Comment by shaleh** [comment]
The current coding standard follows Rust naming and idioms. Because of this, I am closing this Issue. Please re-open it if this is a controversial choice.
