### ISSUE TITLE
Implement __rust_allocate_zeroed properly

### ISSUE THREAD

**Issue by jeandudey** [Wilfred/remacs#180]
Currently the memory returned by `__rust_allocate_zeroed` on `alloc_unexecmacosx` is not zeroed.

**Comment by Wilfred** [comment]
@jeandudey why is this closed?

**Comment by DavidDeSimone** [comment]
Fixed by https://github.com/Wilfred/remacs/pull/221, suggesting that we close this.

**Comment by Wilfred** [comment]
Agreed :)
