### ISSUE TITLE
Can't build Remacs: cl-defgeneric error

### ISSUE THREAD

**Issue by nlamirault** [Wilfred/remacs#184]
hi,
i've got an error after autogen and configure : 

```bash
$ make 
Makefile:901: warning: overriding recipe for target 'lisp_distclean'
Makefile:901: warning: ignoring old recipe for target 'lisp_distclean'
Makefile:914: warning: overriding recipe for target 'lisp_bootstrap-clean'
Makefile:914: warning: ignoring old recipe for target 'lisp_bootstrap-clean'
make -C lib all
make info-real info-dir
make[1]: Entering directory '/home/nlamirault/Apps/remacs'
Makefile:901: warning: overriding recipe for target 'lisp_distclean'
Makefile:901: warning: ignoring old recipe for target 'lisp_distclean'
Makefile:914: warning: overriding recipe for target 'lisp_bootstrap-clean'
Makefile:914: warning: ignoring old recipe for target 'lisp_bootstrap-clean'
make[1]: Entering directory '/home/nlamirault/Apps/remacs/lib'
note: library: rt

note: library: pthread

note: library: gcc_s

note: library: c

note: library: m

note: library: rt

note: library: util

    Finished debug [unoptimized + debuginfo] target(s) in 14.24 secs
mkdir -p ../rust_src/target/
echo " " > ../rust_src/target/.rustflags.tmp
diff -q ../rust_src/target/.rustflags ../rust_src/target/.rustflags.tmp || cp ../rust_src/target/.rustflags.tmp ../rust_src/target/.rustflags
diff: ../rust_src/target/.rustflags: No such file or directory
rm -f ../rust_src/target/.rustflags.tmp
make -C ../admin/charsets all
[...]
/usr/bin/mkdir -p ../etc
setfattr -n user.pax.flags -v er temacs
make -C ../lisp update-subdirs
make[2]: Entering directory '/home/nlamirault/Apps/remacs/lisp'
make[2]: Leaving directory '/home/nlamirault/Apps/remacs/lisp'
./temacs --batch  --load loadup bootstrap
Loading loadup.el (source)...
Using load-path (/home/nlamirault/Apps/remacs/lisp /home/nlamirault/Apps/remacs/lisp/emacs-lisp /home/nlamirault/Apps/remacs/lisp/language /home/nlamirault/Apps/remacs/lisp/international /home/nlamirault/Apps/rem
acs/lisp/textmodes /home/nlamirault/Apps/remacs/lisp/vc)
Loading emacs-lisp/byte-run (source)...
Loading emacs-lisp/backquote (source)...
Loading subr (source)...
Loading version (source)...
Loading widget (source)...
Loading custom (source)...
Loading emacs-lisp/map-ynp (source)...
Loading international/mule (source)...
Loading international/mule-conf (source)...
Loading env (source)...
Loading format (source)...
Loading bindings (source)...
Loading window (source)...
Loading /home/nlamirault/Apps/remacs/lisp/files.el (source)...
Loading /home/nlamirault/Apps/remacs/lisp/emacs-lisp/macroexp.el (source)...
Loading /home/nlamirault/Apps/remacs/lisp/emacs-lisp/pcase.el (source)...
Loading /home/nlamirault/Apps/remacs/lisp/emacs-lisp/macroexp.el (source)...
Loading /home/nlamirault/Apps/remacs/lisp/cus-face.el (source)...
Loading /home/nlamirault/Apps/remacs/lisp/faces.el (source)...
Loading /home/nlamirault/Apps/remacs/lisp/button.el (source)...
Loading /home/nlamirault/Apps/remacs/lisp/loaddefs.el (source)...
Symbol’s function definition is void: cl-defgeneric
make[1]: *** [Makefile:777: bootstrap-emacs] Error 255
make[1]: Leaving directory '/home/nlamirault/Apps/remacs/src'
make: *** [Makefile:424: src] Error 2

```

Any idea ? Thanks.

**Comment by DavidDeSimone** [comment]
I was able to fix this by commenting out the references to cl-defgeneric, and doing a clean build. After doing this, I was able to build without having this change pending.

**Comment by jaccarmac** [comment]
Does this error still occur? The CI Mac build appears to work, at least.

**Comment by shaleh** [comment]
I have not seen this on Linux or OSX.

**Comment by shaleh** [comment]
Appears to be long fixed.

**Comment by Frost** [comment]
It is not fixed, unfortunalety. I am getting this error on the latest master (On Fedora 27). Unfortunately, I'm not sure what references to remove from where to get it to build, so I can't get remacs to build.

**Comment by jaccarmac** [comment]
From a clean clone, or an old dirty tree? Sometimes bits of an old Emacs build stick around and cause problems until you `make clean` or `git clean -fxd`.

**Comment by shaleh** [comment]
Agreed.

Clean clone
Run autogen
Configure
Make

Save all of the output.

**Comment by shaleh** [comment]
This Dockerfile:

    FROM fedora:latest  # latest is 27 right now
    
    RUN yum install -y \
        git \
        gcc gcc-c++ \
        kernel-devel \
        make \
        automake \
        ncurses-devel \
        giflib-devel \
        libjpeg-turbo-devel \
        libtiff-devel \
        gtk3-devel \
        libxml2-devel \
        libXpm-devel \
        gnutls-devel \
        curl \
        texinfo
    
    ENV PATH "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    
    RUN curl https://sh.rustup.rs -o rustup.sh && \
        sh rustup.sh --default-toolchain nightly-2017-12-23 -y && \
        rustup default nightly-2017-12-23

When built and run like so:

    docker build -t fedora-latest-rust -f Dockerfile.fedora .
    docker run -it --security-opt seccomp=unconfined --name fedora-remacs fedora-latest-rust /bin/bash

I was able to compile remacs and run make check. No issues.

**Comment by Frost** [comment]
My failed build was apparently from a dirty tree, but I thought I had cleaned it out using `make clean`, etc. I did not know about `make clean -fxd`.

I just did a clean clone, autogen, configure and make, and this time it worked like a charm.

Thank you for your help and I'm sorry to have wasted your time.

**Comment by shaleh** [comment]
@Frost, No worries at all. We know the fixes because we have had it happen too.

I added the Fedora dockerfile to the tree so we can reference it in the future.

**Comment by jaccarmac** [comment]
Happy to help. `git clean -fxd` (not sure if you made a typo above, the flags are indeed for Git and not Make) is something I've used a lot and not enough people use. Much easier than doing a full reclone if your tree gets polluted.

**Comment by Frost** [comment]
@jaccarmac Ah, yes, that was indeed a typo on my part. Thank you for pointing that out :)

**Comment by nlamirault** [comment]
:+1:  LGTM too.
