### ISSUE TITLE
Rust doesn't appear (yet?) in language analysis

### ISSUE THREAD

**Issue by piotr-yuxuan** [Wilfred/remacs#186]
Is Rust still in the "other" group or is language analysis broken?

<img width="1014" src="https://cloud.githubusercontent.com/assets/3686502/25697070/e018c32a-30b9-11e7-9506-3a167aa85658.png">

**Comment by jeandudey** [comment]
It's in the other, the Rust codebase it's still in it's infancy there aren't much LOC there (`rust_src`), so it doesn't have enough lines to show up in language analysis (i think).
