### ISSUE TITLE
Move base64 lisp functions from C completely

### ISSUE THREAD

**Issue by jeandudey** [Wilfred/remacs#193]
Move base64 lisp functions from C completely

Currently in Rust two functions are exported to C, these functions are `base64_encode_1` and `base64_decode_1` and are defined in `rust_src/src/base64.rs`. These functions are reused too in `src/fns.c`in the lisp native functions `base64-encode-region` and `base64-decode-region`.

Ideally these functions could be moved to Rust in the `base64.rs` module removing the need of intermediary functions like `base64_encode_1` that are unsafe and deal with raw pointers. Also these unsafe functions are reused too in the `strings.rs` module.

Here is a list of what needs to be done (in order):

1. [ ] Move `base64-encode-region` and `base64-decode-region` to the Rust codebase. Probably these functions should belong to the `base64.rs` module.
2. [ ] Refactor `base64_encode_1` and `base64_decode_1` and make them more safe and clean.
3. [x] Move the `base64-encode-string` and `base64-encode-string` defined in `strings.rs` to the `base64.rs` module.
4. [x] **Optional:** modify the code to use the `base64` crate and drop the `rustc-serialize` dependency.

**Comment by mjfeller** [comment]
I spent yesterday reading through the available docs and source. I think I'm going to give this one a go.

I'm still learning rust and Remacs, but this does look like a good first bug for me to try and tackle.

**Comment by Wilfred** [comment]
I've updated the checklist as several of these have been done now.

@jeandudey `base64_encode_1` has had some refactoring, do you think it's sufficiently safe and clean now, or did you have further changes in mind?

**Comment by Wilfred** [comment]
I'm going to close this as our base64 implementation is now pure Rust.

Feel free to open an issue if you have ideas for further cleanup :)
