### ISSUE TITLE
Port subrp to Rust

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#200]

**Comment by Fuco1** [comment]
I think I'm going to try this one.  This is a somewhat fascinating project I've been meaning to get into for quite a bit... my Rust knowledge is exactly 0 so it might be fun.

**Comment by birkenfeld** [comment]
This has been done by @mjfeller in #213. Sorry :)

**Comment by Wilfred** [comment]
I've created some new bugs in the good-first-bug label if you fancy: https://github.com/Wilfred/remacs/labels/good-first-bug
