### ISSUE TITLE
 make_natnum(marker_position(x) as i64) >expected i32, found i64

### ISSUE THREAD

**Issue by oaxjogi** [Wilfred/remacs#21]
Hi,

Windows 10, latest Rust version installed I run into the arch problem but don't know really why?!

[C:\workspace\rust\Projekte\remacs-master\rust_src]cargo build
   Compiling lazy_static v0.2.2
   Compiling libc v0.2.17
   Compiling remacs v0.1.0 (file:///C:/workspace/rust/Projekte/remacs-master/rust_src)
error[E0308]: mismatched types
   --> src\lisp.rs:316:21
    |
316 |         make_natnum(marker_position(x) as i64)
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected i32, found i64

error: aborting due to previous error

error: Could not compile `remacs`.

To learn more, run the command again with --verbose.

**Comment by gallexme** [comment]
https://github.com/rust-lang/libc/blob/4577f089b4fea9fe34b785800324b06d36ff48c9/src/windows.rs
looks like libc ignores the arch of windows and always uses 32 bit Int as Word Size

**Comment by Wilfred** [comment]
Hm, this is my bad, lazily writing `i64` instead of `EmacsInt`.
