### ISSUE TITLE
Question: Do Rust really need tagged pointers

### ISSUE THREAD

**Issue by shanavas786** [Wilfred/remacs#216]
Emacs uses tagged pointer to represent `Lisp_Objects`, Rust being a `safe` language do not encourage raw pointers and its manipulation.

I am excited to know if there is a `safe` alternative in `Rust` without compromising performance.

**Comment by birkenfeld** [comment]
Any other solution would at least double the space consumption of every `Lisp_Object`. IMO, the tagged pointer representation is not really such a bad thing as long as we build a safe API around it, as we have started to. And of course as long as there is C code left, you have to keep interoperability or rewrite the C parts as well...

**Comment by Wilfred** [comment]
Yes, I think tagged pointers are correct for Remacs. It's an extremely efficient way of representing data in a dynamically typed language, and I'd like us to use it more (e.g. we could use nan-boxing to store floats as a tagged value). High performance JS interpreters do the same thing.

Provided that we have a safe API, it should be perfectly rustic :). Value types (integers etc) are easy to manipulate safely. It takes a little more care with pointer types, but a small layer of unsafe code should be sufficient for rustc to check everything else.
