### ISSUE TITLE
Port get-process to Rust

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#230]
The C looks like this:

```c
DEFUN ("get-process", Fget_process, Sget_process, 1, 1, 0,
       doc: /* Return the process named NAME, or nil if there is none.  */)
  (register Lisp_Object name)
{
  if (PROCESSP (name))
    return name;
  CHECK_STRING (name);
  return Fcdr (Fassoc (name, Vprocess_alist));
}
```

so the Rust code should check the value is a process or a string, then look up the name in `Vprocess_alist`.

**Comment by sieudcls** [comment]
I would love to work on this one!

**Comment by sieut** [comment]
I would love to work on this one!

**Comment by sieut** [comment]
Hi, I've been working on this for a couple of days; however, I'm running into some problems with Vprocess_alist. I'm not sure how could I get this alist and I've been looking at the code base for a while. It would be great if someone could give me hints for this issue. Thank you very much

**Comment by Wilfred** [comment]
`Vprocess_alist` is defined in process.c:

```c
static Lisp_Object Vprocess_alist;
```

you should be able to add it to `remacs-sys/lib.rs` in the same way that `Vbuffer_alist` is defined.

**Comment by jsoo1** [comment]
I think [#256](https://github.com/Wilfred/remacs/pull/256) closes this issue.

**Comment by birkenfeld** [comment]
Done!
