### ISSUE TITLE
Port window-live-p to Rust

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#232]
The function:

```c
DEFUN ("window-valid-p", Fwindow_valid_p, Swindow_valid_p, 1, 1, 0,
       doc: /* Return t if OBJECT is a valid window and nil otherwise.
A valid window is either a window that displays a buffer or an internal
window.  Windows that have been deleted are not valid.  */)
  (Lisp_Object object)
{
  return WINDOW_VALID_P (object) ? Qt : Qnil;
}
```

The macro:

```c
/* True if WINDOW is a live window.  */
#define WINDOW_LIVE_P(WINDOW)					\
  (WINDOWP (WINDOW) && BUFFERP (XWINDOW (WINDOW)->contents))
```

**Comment by gregkatz** [comment]
Hi,

I'm new to the project (and emacs lisp though I have decent rust proficiency) and I was thinking about taking this one. Quick question: In this bug, it has ```WINDOW_LIVE_P``` listed for the macro but the function is for ```window-valid-p```. Is that intentional?

Thanks,

Greg

**Comment by Wilfred** [comment]
Woops! Sorry, that was my mistake. The function is actually this one:

```c
DEFUN ("window-live-p", Fwindow_live_p, Swindow_live_p, 1, 1, 0,
       doc: /* Return t if OBJECT is a live window and nil otherwise.
A live window is a window that displays a buffer.
Internal windows and deleted windows are not live.  */)
  (Lisp_Object object)
{
  return WINDOW_LIVE_P (object) ? Qt : Qnil;
```

it's in `src/window.c`.

**Comment by gregkatz** [comment]
Ok, no problem and thanks. I should have a PR opened tomorrow. 

I'm planning on mimicking the implementation of ```buffer-live-p```. Sound like a good plan to you? It will involve adding a a window struct to remacs-sys.

**Comment by Wilfred** [comment]
Merged! :)
