### ISSUE TITLE
Build fails on Ubuntu 17.04 with Rust stable

### ISSUE THREAD

**Issue by sieut** [Wilfred/remacs#241]
I'm trying to build Remacs but running into this error

```
error: unions are unstable and possibly buggy (see issue #32836)
   --> /home/sieut/work/remacs/rust_src/remacs-sys/lib.rs:671:1
    |
671 | / pub union SymbolUnion {
672 | |     pub value: Lisp_Object,
673 | |     pub alias: *mut Lisp_Symbol,
674 | | pub blv: *mut libc::c_void, // @TODO implement Lisp_Buffer_Local_Value
675 | | pub fwd: *mut libc::c_void, // @TODO implement Lisp_Fwd
676 | | }
    | |_^

error: aborting due to previous error

error: Could not compile `remacs-sys`.

````

**Comment by DavidDeSimone** [comment]
Hello, thank you for the report.

Could you do me a favor, and run `rustc --version` and paste me the output?

**Comment by sieut** [comment]
I got `rustc 1.18.0 (03fc9d622 2017-06-06)`
I installed nightly Rust and didn't switch to it and also didn't make clean and rebuild properly, I'm trying to rebuild Remacs again.

**Comment by shanavas786** [comment]
@sieut 
use `rustup default nightly` to set it as default tool chain.
Hope that helps

**Comment by sieut** [comment]
@shanavas786 Thanks for the tip, I am able to build now with nightly Rust. I'm sorry for not checking thoroughly before opening an issue. I'll close this issue
