### ISSUE TITLE
C-h f on a Rust primitive shows 'in C source code'

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#259]
Jumping to definition works, however.

**Comment by birkenfeld** [comment]
Hm yes, at this point the DOC file is not yet loaded, so Emacs doesn't know the source file name.

But we can say "C/Rust source" of course.

**Comment by db48x** [comment]
or perhaps "in compiled source code"?

**Comment by shaleh** [comment]
I looked a little at this. The elisp code is where the decision is being made. remacs is basically treated as if the source code was not available. It should be possible to tweak it.
