### ISSUE TITLE
#[lisp_fn] makes rustc show errors in the wrong position

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#263]
For example, adding the following code:

```rust
#[lisp_fn]
pub fn foo() -> LispObject {
    1 // wrong type!
}
```

produces:

```
error[E0308]: mismatched types
   --> src/buffers.rs:117:1
    |
117 | #[lisp_fn]
    | ^^^^^^^^^^ expected struct `lisp::LispObject`, found integral variable
    |
    = note: expected type `lisp::LispObject`
               found type `{integer}`
```

I'm not sure if this is a bug in rustc itself, or our macro implementation.

**Comment by birkenfeld** [comment]
This is a current limitation of proc macros, unfortunately.

**Comment by Wilfred** [comment]
@birkenfeld oh, interesting. Is there an upstream Rust bug tracking this?

**Comment by birkenfeld** [comment]
Well, the API is currently "get token stream, convert to string, parse with `syn`, transform, convert to string, pass back to rustc". So the span info relative to the original source is necessarily lost in the process. I hope that in the future, AST objects will be passed into the macro directly, as it used to be with old-style compiler plugins, but of course that runs into all of rustc being unstable and so might not be possible on stable any time soon.

There is certainly several issues dealing with the future of proc macros, but I can't tell you any issue numbers.

**Comment by Wilfred** [comment]
Gotcha, that makes sense. I don't think there's much we can do here, so I'll close this.

**Comment by DavidDeSimone** [comment]
As a note, based on https://quodlibetor.github.io/posts/debugging-rusts-new-custom-derive-system/, it looks like using `cargo expand` is an option if you have a proc macro error you just can't make heads of tails over.

**Comment by birkenfeld** [comment]
Hadn't seen `cargo expand` before, thanks for the pointer!

**Comment by Wilfred** [comment]
That's really useful, thanks. The other crude workaround is to just define a worker function, at least whilst you're debugging:

```rust
fn foo_1() -> LispObject {
    1 // wrong type!
}

#[lisp_fn]
pub fn foo() -> LispObject {
    foo_1()
}
```

```
error[E0308]: mismatched types
   --> src/math.rs:359:5
    |
359 |     1 // wrong type!
    |     ^ expected struct `lisp::LispObject`, found integral variable
    |
    = note: expected type `lisp::LispObject`
               found type `{integer}`
```

**Comment by birkenfeld** [comment]
In the end, since `lisp_fn` doesn't change the function's code at all, I just comment out the attribute until the function compiles.
