### ISSUE TITLE
Compiling complains about: unresolved import `remacs_sys::wrong_type_argument`

### ISSUE THREAD

**Issue by terlar** [Wilfred/remacs#270]
I cannot compile the current master using the compilation instructions from [AUR package for remacs-git](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=remacs-git).

I had no problem compiling it sometime in the beginning of last week. But currently the following error occurs:
```
  Compiling remacs v0.1.0 (file:///.../remacs-git/rust_src)
error[E0432]: unresolved import `remacs_sys::wrong_type_argument`
 --> .../remacs-git/rust_src/src/fonts.rs:2:64
  |
2 | use remacs_sys::{font, Qfont_spec, Qfont_entity, Qfont_object, wrong_type_argument};
  |                                                                ^^^^^^^^^^^^^^^^^^^ no `wrong_type_argument` in the root. Did you mean to use `Qwrong_type_argument`?
```

This is code coming from the recently merged: https://github.com/Wilfred/remacs/pull/248

**Comment by s-kostyaev** [comment]
#269

**Comment by terlar** [comment]
Missed that, I was only searching through the issues, guess I should have checked the PR:s too.

**Comment by terlar** [comment]
Works now when that fix is merged.
