### ISSUE TITLE
The invocation-name is still "Emacs" for Emacs.app on macOS

### ISSUE THREAD

**Issue by xuchunyang** [Wilfred/remacs#272]
The text-mode Emacs gives `"remacs"` as expected

    $ src/remacs -Q -nw

However, the graphic Emacs still gives `"Emacs"`

    $ open nextstep/Emacs.app --args -Q

**Comment by shaleh** [comment]
@Wilfred https://github.com/shaleh/remacs/tree/macos_remacs_name is your branch with the needed changes to have a proper Remacs.app.

BTW In case anyone did not know, `make install` is what copies the elisp into the .app.
