### ISSUE TITLE
Question about marker position

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#287]
I'm trying to port marker-position and there's already a method for the position. But I don't understand why it throws an error if the marker points nowhere, while the original returns nil. Is there something I'm missing and I'm supposed to add another method or was this unintended ?

**Comment by Wilfred** [comment]
OK, so `marker-position` returns nil, but `marker_position` in marker.rs raises an error if a marker doesn't point anywhere. This was introduced in f0b21194c1.

We did this because `rust_mod` allows you to use markers as numbers, but that requires the marker to point somewhere. In marker.c:

```
ptrdiff_t
marker_position (Lisp_Object marker)
{
  register struct Lisp_Marker *m = XMARKER (marker);
  register struct buffer *buf = m->buffer;

  if (!buf)
    error ("Marker does not point anywhere");

  eassert (BUF_BEG (buf) <= m->charpos && m->charpos <= BUF_Z (buf));

  return m->charpos;
}
```

I suggest that we change `LispMarkerRef::position` to return an `Option<ptrdiff_t>`. Sound reasonable?

**Comment by brotzeit** [comment]
It seems `marker_position` is used quite often. Does that mean we would have to raise the error for every function that use it ? If that's the case, it's maybe better to add a second method ?

**Comment by Wilfred** [comment]
You mean `LispMarkerRef::position` is used often? I can see two calls (one in math.rs and one in lisp.rs). We could define: `LispMarkerRef:: position() -> Option<ptrdiff_t>` and a `LispMarkerRef::position_or_error() -> ptrdiff_t`. That could be a nice API.

You could then do something like:

```rust
#[lisp_fn]
fn marker_position(marker: LispObject) -> LispObject {
    let marker = object
        .as_marker()
        .unwrap_or_else(|| wrong_type!(Qmarkerp, self));

    marker.position().unwrap_or(LispObject::constant_nil)
}
```

**Comment by brotzeit** [comment]
Yes, thats what I had in mind. But shouldn't we use charpos instead of position for consistency ?

**Comment by Wilfred** [comment]
Oh, you mean `LispMarkerRef::charpos` from #292? Yep, that would work :)
