### ISSUE TITLE
Next merge with upstream

### ISSUE THREAD

**Issue by birkenfeld** [Wilfred/remacs#315]
... should be done soon. I'll do it on the weekend if nobody else gets to it.

**Comment by brotzeit** [comment]
I've already tried it, but there were some spots I wasn't sure about what to do. It would be good if you can do it this time. I would give it another try in a few weeks when there aren't that many commits to be merged.

**Comment by birkenfeld** [comment]
Sure, thanks for the offer. The merges are annoying because of lots of changes in files we deleted (changelogs, MSDOS related, gnulib), but there is also some meat that is easy to miss if the churn is too great, so the more often they are done the easier.

**Comment by DavidDeSimone** [comment]
I wonder if it would be worth it to try and do these merges in a shorter interval? Maybe every 1-2 weeks?

**Comment by Wilfred** [comment]
I've been wondering about ChangeLog files. We removed them in #43.

Eventually, we will want changelogs in Remacs. Reinventing our own system when there's an existing approach for changelogs seems silly.

On the other hand, I expect a changelog to tell me about user-visible changes. A good changelog is a summary for users, and is valuable when it's not just a dump of commit messages. In Emacs, the NEWS file handles user-visible changes. AFAICS the ChangeLog files add nothing to commit messages (and I think there's been some discussion on emacs-devel about dropping them, but workflows change slowly).

**Comment by brotzeit** [comment]
@DavidDeSimone It would make this certainly easier. I will give it another try next weekend.

@Wilfred I tend to go along with your proposal from #322 and merge the dos stuff that was already removed.
