### ISSUE TITLE
Port following-char to Rust

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#318]
```c
DEFUN ("following-char", Ffollowing_char, Sfollowing_char, 0, 0, 0,
       doc: /* Return the character following point, as a number.
At the end of the buffer or accessible region, return 0.  */)
  (void)
{
  Lisp_Object temp;
  if (PT >= ZV)
    XSETFASTINT (temp, 0);
  else
    XSETFASTINT (temp, FETCH_CHAR (PT_BYTE));
  return temp;
}
```

**Comment by peter-b** [comment]
This issue appears to have been fixed by #318 and should be closed!

**Comment by Wilfred** [comment]
There was #320, but that was closed by the original author. This is still up for grabs :)

**Comment by brotzeit** [comment]
He had problems implementing FETCH_CHAR, just like me #316 :)

**Comment by enebo** [comment]
Ah so the issue was that we need multi-byte character read.  I got really confused when I looked at the already ported fetch_char as it appears to be the multi-byte character logic and not the single-bytes version with a single-byte return value.  Am I wrong about that?

**Comment by brotzeit** [comment]
@enebo We have a `fetch_char` method now, if you want to complete your PR.

**Comment by brotzeit** [comment]
#436
