### ISSUE TITLE
October rollup

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#335]
I started another try and found the gitignore file. Is there a reason for not adding the deleted files ?

**Comment by birkenfeld** [comment]
If that works - go for it. I hadn't thought of trying it.

**Comment by brotzeit** [comment]
It seems to work if I use git "rm -rf --cached . && git add ." after merge with upstream, but I don't know if this has any other side effects.

I'm also not sure how to handle a new function called logcount in data.rs. I noticed that we use rust_count_one_bits instead of the c implementation.

Last question is how do I resolve conflicts in lib/gnulib.mk.in. Is it possible by simply generating a new one ? How can I do it ?

**Comment by DavidDeSimone** [comment]
In the past we have punted on generating that Makefile, and have resorted to hand editing it. I tried to generate it given our changes, and was unsuccessful for some reasons I didn’t fully understand, with issues like the copyright date in the Makefile being inconsistent, along with other subtle differences in the Makefile.

As for rust_count_one_bits, if anything new is using the old count_one_bits function, we should just switch it to use the Rust equivalent in the merge imo.

**Comment by Wilfred** [comment]
> It seems to work if I run "git rm -rf --cached . && git add ." after merge with upstream, but I don't know if this has any other side effects.

This would commit any files with merge conflict markers to the repo. What output is git giving you if you don't do this? There might be a better solution we can find :)

**Comment by Wilfred** [comment]
Regarding the .gitignore file, this exists on both the Remacs and GNU Emacs side, so I wonder why that's causing issues.

**Comment by brotzeit** [comment]
It's not exactly causing issues, but we have to manually remove the files we already deleted. I thought it would be more convenient if this would be done automatically and it seems to work as I still have to resolve conflicts in files we did not delete.
