### ISSUE TITLE
Fix mock related Travis linker error.

### ISSUE THREAD

**Issue by DavidDeSimone** [Wilfred/remacs#339]
It seems that somehow our mocked static functions have their names being mangled. This isn't reproducing on my local machine, so something funky is happening. As a note, this is an error I would expect in mock_derive 0.6.0, as it was fixed in 0.6.1. So it's almost like travis is using a dated version of the lib. 

Is anyone else having `cargo test` fail on their local machine with a linker error?

**Comment by DavidDeSimone** [comment]
Aha, so this is a regression introduced around Sept. 30 into nightly. I'll hunt this down and inform the rust team once I have the details, but until then, lets remove mock_derive from the project.

**Comment by Wilfred** [comment]
@DavidDeSimone tests are green for me, is this still an issue?

**Comment by DavidDeSimone** [comment]
This should no longer be an issue, closing.
