### ISSUE TITLE
links to "C source code" in documentation do not work when function is defined in rust

### ISSUE THREAD

**Issue by dpzmick** [Wilfred/remacs#34]
C-h f <function name>

Then attempt to click on C source code

**Comment by chrisbarrett** [comment]
I'm having a go at this. Can someone point me to an example of how the C DEFVAR macro looks when ported to Rust?

**Comment by Wilfred** [comment]
@chrisbarrett we don't have any `DEFVAR` equivalents in Rust yet, so your patch would only need to handle functions. Hopefully that will make things more straightforward :)

**Comment by jeandudey** [comment]
A side note, the `documentation` lisp function doesn't work with functions defined in Rust (returns `Qnil`).
Maybe it's related to [this][1]

[1]: https://github.com/Wilfred/remacs/blob/master/rust_src/remacs-sys/lib.rs#L85

**Comment by chrisbarrett** [comment]
I'm not gonna have time to work on this anytime soon, so someone else can pick this up. :)

**Comment by shaleh** [comment]
`documentation` function works now. So does `C-h f`. It looks like this issue can be closed.

**Comment by Wilfred** [comment]
Agreed :)
