### ISSUE TITLE
Port subset of dired.c to Rust

### ISSUE THREAD

**Issue by gaak99** [Wilfred/remacs#346]
Greetings from Cabbagetown, GA, USA ...

I have the following ported from dired.c

  

-   directory_files_internal
-   directory-files
-   directory-files-and-attributes
-   file-attributes
-   file-attributes-lessp
-   system-users

Only tested on Linux. Can anybody here test&fix on Windows/MacOS/etc?

Cheers,
gtb

ps. not ported in dired.c:

- file_name_completion and related funcs
--it's a beast and worthy of a seperate proj

- system-groups
--it appears no Rust equiv (in libc anyways) of Linux's getgrent(3).

**Comment by brotzeit** [comment]
Thanks for your contribution. You can always open a pull request if you want a review of your code. I don't think you need to additionally open an issue, unless you have any specific questions.

**Comment by shaleh** [comment]
#348 is the linked PR.

**Comment by gaak99** [comment]
Obsolete pr.
