### ISSUE TITLE
Port beginning-of-line to Rust

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#353]
```c
DEFUN ("beginning-of-line", Fbeginning_of_line, Sbeginning_of_line, 0, 1, "^p",
       doc: /* Move point to beginning of current line (in the logical order).
With argument N not nil or 1, move forward N - 1 lines first.
If point reaches the beginning or end of buffer, it stops there.

This function constrains point to the current field unless this moves
point to a different line than the original, unconstrained result.
If N is nil or 1, and a front-sticky field starts at point, the point
does not move.  To ignore field boundaries bind
`inhibit-field-text-motion' to t, or use the `forward-line' function
instead.  For instance, `(forward-line 0)' does the same thing as
`(beginning-of-line)', except that it ignores field boundaries.  */)
  (Lisp_Object n)
{
  if (NILP (n))
    XSETFASTINT (n, 1);
  else
    CHECK_NUMBER (n);

  SET_PT (XINT (Fline_beginning_position (n)));

  return Qnil;
}
```

**Comment by galczo5** [comment]
Hi, I would be happy to join you, but I'm not sure if I understand structure of code. 
That task is to add functions `Fline_beginning_position (Lisp_Object n)` and `set_point (ptrdiff_t)` to `./rust_src/remacs-sys/lib.rs`, then add simple function to `/rust_src/src/cmds.rs` and `defsubr` code to `/rust_src/src/lib.rs`. Am I right?

**Comment by brotzeit** [comment]
Correct, but we skipped `set_point` and just use `set_point_both` which is already in /remacs-sys/lib.rs. If you have any further questions feel free to ask.

**Comment by galczo5** [comment]
Ok, I'll try to do this issue.

**Comment by galczo5** [comment]
Hi, I have some problems with code. https://github.com/galczo5/remacs/commit/d1df0e854df4529f2ad2ede6428b0cc94af035c3

Code throws ` Segmentation fault` from rust code and number from elisp call. I have one question, why `Fline_beginning_position` in rust want `i64` as argument, not `Lisp_Object` as I declared in `lib.rs`? Sorry if my question is dumb.

Here is my testing code:
```
(defun test0 ()
  (interactive)
  (print (line-beginning-position 1)))

(defun test1 ()
  (interactive)
  (test-b 1))
```

**Comment by brotzeit** [comment]
Don't worry, I still don't understand most of this stuff ;)

`as_fixnum_or_error` gives you a fixnum, but you need a `Lisp_Object`. You can cast your `LispObject` "n" with `to_raw`.  Remember that  `Fline_beginning_position` also returns a `Lisp_Object`. Use `from_raw` for this.

You can find many similiar unsafe function calls in the rust codebase. I'm sure, that will help you.

**Comment by galczo5** [comment]
https://github.com/Wilfred/remacs/pull/382

Something like this?
