### ISSUE TITLE
Logo for remacs :) ?

### ISSUE THREAD

**Issue by shanavas786** [Wilfred/remacs#358]

**Comment by Wilfred** [comment]
Yep, a logo would be great. See #360, but if someone has the skills to create something distinctive (perhaps a stylised R rather than an E?), contributions would be very welcome.

**Comment by shanavas786** [comment]
I attempted replacing R in rust logo with E but didn't succeed.

@chenl would you like to give a try ? :)

On October 14, 2017 1:25:32 PM GMT+03:00, Wilfred Hughes <notifications@github.com> wrote:
>Yep, a logo would be great. See #360, but if someone has the skills to
>create something distinctive (perhaps a stylised R rather than an E?),
>contributions would be very welcome.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Wilfred/remacs/issues/358#issuecomment-336625860

-- 
ഷാനവാസ്
Sent from my Android device with K-9 Mail.

**Comment by xenodium** [comment]
How about a welcoming, playful, cute take on it?

![lemmling-cartoon-gnu](https://user-images.githubusercontent.com/8107219/32315491-338f4b40-bfa4-11e7-9f9c-0a66b4f40bca.png)

Sample usage when switching apps on macOS:

![switchingapps](https://user-images.githubusercontent.com/8107219/32315368-bd76acaa-bfa3-11e7-95e2-8bbcf3835cd2.jpg)

Not my work, but friendly license: Creative Commons Zero 1.0 Public Domain License

Source at: https://openclipart.org/detail/17624/cartoon-gnu

**Comment by brotzeit** [comment]
We have a logo now.
