### ISSUE TITLE
"<t> is undefined" (known emacs bug)

### ISSUE THREAD

**Issue by guskovd** [Wilfred/remacs#363]
Now I'm using emacs 25.3.1 because of this problem. I understand that in new versions (26+) they do not hurry to fix this bug.

Is there any plan to fix this problem in remacs?

read more: https://github.com/PythonNut/emacs-config/commit/479f658e4480a17392cc193923fdb259404818b1
https://emacs.stackexchange.com/questions/32540/t-is-undefined-error-on-first-keypress

**Comment by Wilfred** [comment]
If it's in the primitive functions, then we could look at fixing in Remacs. Skimming PythonNot's commit, they mention `sit-for`, which we're looking at porting in #374.

If it's in elisp, I would prefer we fix it upstream.

**Comment by shaleh** [comment]
@guskovd did the bug go away now that the function is written in Rust?

**Comment by shaleh** [comment]
Closing this ticket.

We have ported some of this code and incorporated upstream fixes in the C code as well.

@guskovd if you can still reproduce this please re-open the issue.
