### ISSUE TITLE
Couldn't resolve host 'github.com'

### ISSUE THREAD

**Issue by tsmarques** [Wilfred/remacs#367]
I'm trying to build remacs with docker and when I run `docker-compose exec remacs make` I get the following error:

> curl error: Couldn't resolve host 'github.com'

**Comment by shaleh** [comment]
Any luck?

**Comment by tsmarques** [comment]
I've worked around this by setting rust's version to nightly instead of using docker.

**Comment by shaleh** [comment]
Should we resolve this issue? Do you believe it is a docker error or an error in the remacs scripts?

**Comment by shaleh** [comment]
Step 4/4 : RUN curl https://sh.rustup.rs -o rustup.sh && sh rustup.sh --default-toolchain nightly -y && rustup default nightly
 ---> Running in 0dded81168e9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9293  100  9293    0     0  21617      0 --:--:-- --:--:-- --:--:-- 21662
info: downloading installer
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2017-10-24, rust version 1.22.0-nightly (4c053db23 2017-10-22)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'

info: default toolchain set to 'nightly'
  nightly installed - rustc 1.22.0-nightly (4c053db23 2017-10-22)

info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.22.0-nightly (4c053db23 2017-10-22)

 ---> b0f8b2c40a88
Removing intermediate container 0dded81168e9
Successfully built b0f8b2c40a88

**Comment by shaleh** [comment]
Seems ok

**Comment by tsmarques** [comment]
Hm , so I've compiling on my work computer and everything seems fine. Probably it was my laptop's problem then. It think this can be closed.

**Comment by shaleh** [comment]
Thank you for responding. Closing the issue.
