### ISSUE TITLE
Build failed on fresh checkout

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#370]
../rust_src/remacs-lib/target/debug/libremacs_lib.a(rand-fe8d725aecdfc566.rand13.rust-cgu.o): In function `std::f64::{{impl}}::exp':/checkout/src/libstd/f64.rs:440: undefined reference to `exp'

In C land this usually means a missing `-lm`. I have tried today's rust nightly and a week ago's nightly. Same failure.

**Comment by Wilfred** [comment]
Could you try 'make clean' and see if re-occurs? I'm struggling to reproduce this.

**Comment by shaleh** [comment]
Configured for 'x86_64-pc-linux-gnu'.

  Where should the build process find the source code?    .
  What compiler should emacs be built with?               gcc -g3 -O2
  Should Emacs use the GNU version of malloc?             yes
      (Using Doug Lea's new malloc from the GNU C Library.)
  Should Emacs use a relocating allocator for buffers?    no
  Should Emacs use mmap(2) for buffer allocation?         no
  What window system should Emacs use?                    x11
  What toolkit should Emacs use?                          GTK3
  What libraries will lib-remacs link against?            -ldl -lrt
  Where do we find X Windows header files?                Standard dirs
  Where do we find X Windows libraries?                   Standard dirs
  Does Emacs use -lXaw3d?                                 no
  Does Emacs use -lXpm?                                   yes
  Does Emacs use -ljpeg?                                  yes
  Does Emacs use -ltiff?                                  yes
  Does Emacs use a gif library?                           yes -lgif
  Does Emacs use a png library?                           yes -lpng12
  Does Emacs use -lrsvg-2?                                yes
  Does Emacs use cairo?                                   no
  Does Emacs use -llcms2?                                 yes
  Does Emacs use imagemagick (version 6)?                 no
  Does Emacs support sound?                               yes
  Does Emacs use -lgpm?                                   no
  Does Emacs use -ldbus?                                  yes
  Does Emacs use -lgconf?                                 no
  Does Emacs use GSettings?                               yes
  Does Emacs use a file notification library?             yes -lglibc (inotify)
  Does Emacs use access control lists?                    no
  Does Emacs use -lselinux?                               no
  Does Emacs use -lgnutls?                                yes
  Does Emacs use -lxml2?                                  yes
  Does Emacs use -lfreetype?                              yes
  Does Emacs use -lm17n-flt?                              no
  Does Emacs use -lotf?                                   no
  Does Emacs use -lxft?                                   yes
  Does Emacs use -lsystemd?                               yes
  Does Emacs directly use zlib?                           yes
  Does Emacs have dynamic modules support?                no
  Does Emacs use toolkit scroll bars?                     yes
  Does Emacs support Xwidgets (requires gtk3)?            no
  Does Emacs have threading support in lisp?              yes

**Comment by shaleh** [comment]
Compiling remacs-lib v0.1.0 (file:///home/shaleh/repos/mine/remacs/rust_src/remacs-lib)
     Running `rustc --crate-name remacs_lib /home/shaleh/repos/mine/remacs/rust_src/remacs-lib/lib.rs --crate-type staticlib --crate-type rlib --emit=dep-info,link -C panic=abort -C debuginfo=2 -C metadata=edf12c2941d31c28 -C extra-filename=-edf12c2941d31c28 --out-dir /home/shaleh/repos/mine/remacs/rust_src/remacs-lib/target/debug/deps -L dependency=/home/shaleh/repos/mine/remacs/rust_src/remacs-lib/target/debug/deps --extern libc=/home/shaleh/repos/mine/remacs/rust_src/remacs-lib/target/debug/deps/liblibc-54abf159be0de30e.rlib --extern rand=/home/shaleh/repos/mine/remacs/rust_src/remacs-lib/target/debug/deps/librand-fe8d725aecdfc566.rlib --extern errno=/home/shaleh/repos/mine/remacs/rust_src/remacs-lib/target/debug/deps/liberrno-a82e61d380312545.rlib`
note: link against the following native artifacts when linking against this static library

note: This list will not be printed by default. Please add --print=native-static-libs if you need this information

note: library: util

note: library: dl

note: library: rt

note: library: pthread

note: library: gcc_s

note: library: c

note: library: m

note: library: rt

note: library: pthread

note: library: util

    Finished dev [unoptimized + debuginfo] target(s) in 2.9 secs
  CCLD     etags
../rust_src/remacs-lib/target/debug/libremacs_lib.a(rand-fe8d725aecdfc566.rand13.rust-cgu.o): In function `std::f64::{{impl}}::exp':
/checkout/src/libstd/f64.rs:440: undefined reference to `exp'
collect2: error: ld returned 1 exit status
Makefile:401: recipe for target 'etags' failed
make[1]: *** [etags] Error 1
make[1]: Leaving directory '/home/shaleh/repos/mine/remacs/lib-src'
Makefile:413: recipe for target 'lib-src' failed
make: *** [lib-src] Error 2

**Comment by shaleh** [comment]
rustc --version
rustc 1.22.0-nightly (b7960878b 2017-10-18)

**Comment by shaleh** [comment]
Running the build with V=1 so the commands are output gives me this:

make[1]: Entering directory '/home/shaleh/repos/mine/remacs/lib-src'
gcc   -fno-common -W -Wabi -Waddress -Waggressive-loop-optimizations -Wall -Wattributes -Wbool-compare -Wbuiltin-macro-redefined -Wcast-align -Wchar-subscripts -Wchkp -Wclobbered -Wcomment -Wcomments -Wcoverage-mismatch -Wcpp -Wdate-time -Wdeprecated -Wdeprecated-declarations -Wdesignated-init -Wdisabled-optimization -Wdiscarded-array-qualifiers -Wdiscarded-qualifiers -Wdiv-by-zero -Wdouble-promotion -Wempty-body -Wendif-labels -Wenum-compare -Wextra -Wformat-contains-nul -Wformat-extra-args -Wformat-security -Wformat-signedness -Wformat-y2k -Wformat-zero-length -Wfree-nonheap-object -Wignored-qualifiers -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wincompatible-pointer-types -Winit-self -Wint-conversion -Wint-to-pointer-cast -Winvalid-memory-model -Winvalid-pch -Wjump-misses-init -Wlogical-not-parentheses -Wlogical-op -Wmain -Wmaybe-uninitialized -Wmemset-transposed-args -Wmissing-braces -Wmissing-declarations -Wmissing-include-dirs -Wmissing-parameter-type -Wmissing-prototypes -Wmultichar -Wnarrowing -Wnested-externs -Wnonnull -Wodr -Wold-style-declaration -Wold-style-definition -Wopenmp-simd -Woverflow -Wpacked -Wpacked-bitfield-compat -Wparentheses -Wpointer-arith -Wpointer-sign -Wpointer-to-int-cast -Wpragmas -Wpsabi -Wreturn-local-addr -Wreturn-type -Wsequence-point -Wshift-count-negative -Wshift-count-overflow -Wsizeof-array-argument -Wsizeof-pointer-memaccess -Wstrict-aliasing -Wstrict-prototypes -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-final-methods -Wsuggest-final-types -Wswitch-bool -Wtrampolines -Wtrigraphs -Wuninitialized -Wunknown-pragmas -Wunused -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-macros -Wunused-result -Wunused-value -Wunused-variable -Wvarargs -Wvariadic-macros -Wvector-operation-performance -Wvolatile-register-var -Wwrite-strings -Warray-bounds=2 -Wnormalized=nfc -Wredundant-decls -Wno-missing-field-initializers -Wno-override-init -Wno-sign-compare -Wno-type-limits -Wno-unused-parameter -Wno-format-nonliteral  -I. -I../src -I../lib -I. -I./../src -I./../lib  -L.././rust_src/target/debug  -g3 -O2 -pthread -DEMACS_NAME="\"GNU Emacs\"" -DVERSION="\"27.0.50\"" -o etags etags.c regex.o  ../lib/libgnu.a  ../rust_src/remacs-lib/target/debug/libremacs_lib.a -ldl -lrt
../rust_src/remacs-lib/target/debug/libremacs_lib.a(rand-fe8d725aecdfc566.rand13.rust-cgu.o): In function `std::f64::{{impl}}::exp':
/checkout/src/libstd/f64.rs:440: undefined reference to `exp'
collect2: error: ld returned 1 exit status

**Comment by shaleh** [comment]
I do not see a `-lm` on that line. It needs to be used somewhere right?

**Comment by shaleh** [comment]
Confirmed. If I manually edit the generated Makefile and add `-lm` right after `-lrt` the build proceeds.
