### ISSUE TITLE
Interactive rust functions

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#383]
I've tried to use our `lisp_fn` macro with the `intspec` option, but I can't get this to work. `goto-char` should be interactive and maybe there are more functions we have already ported, but are not interactive. Related PR is #382.

**Comment by shaleh** [comment]
Is the "intspec: null" inside lisp_fn part of this?

**Comment by DavidDeSimone** [comment]
@shaleh That appears to be the case. I believe https://github.com/Wilfred/remacs/pull/385 should address this.
