### ISSUE TITLE
Port window-combination-limit to Rust

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#396]
```c
DEFUN ("window-combination-limit", Fwindow_combination_limit, Swindow_combination_limit, 1, 1, 0,
       doc: /* Return combination limit of window WINDOW.
WINDOW must be a valid window used in horizontal or vertical combination.
If the return value is nil, child windows of WINDOW can be recombined with
WINDOW's siblings.  A return value of t means that child windows of
WINDOW are never (re-)combined with WINDOW's siblings.  */)
  (Lisp_Object window)
{
  struct window *w;

  CHECK_VALID_WINDOW (window);
  w = XWINDOW (window);
  if (WINDOW_LEAF_P (w))
    error ("Combination limit is meaningful for internal windows only");
  return w->combination_limit;
}
```

**Comment by shaleh** [comment]
Question.

The C code checks WINDOW_LEAF_P. The errors say that it should only be called on internal windows. So should it really call WINDOW_INTERNAL_P? Maybe no one updated it when the macro was added?

    /* Non-nil if window W is leaf window (has a buffer).  */
    #define WINDOW_LEAF_P(W) \
      (BUFFERP ((W)->contents))

    /* Non-nil if window W is internal (is a parent window).  */
    #define WINDOW_INTERNAL_P(W) \
      (WINDOWP ((W)->contents))

**Comment by shaleh** [comment]
Looking at the blame output, this appears to be the case.


* window.h (struct window): Replace hchild, vchild and buffer slots
5 years ago
#define WINDOW_LEAF_P(W) \
  (BUFFERP ((W)->contents))
Provide additional support for child frames
4 months ago
/* Non-nil if window W is internal (is a parent window).  */
Fix `window-configuration-change-hook' and `window-size-change-functi…
2 years ago
#define WINDOW_INTERNAL_P(W) \
(WINDOWP ((W)->contents))
