### ISSUE TITLE
New compiler warning from recent hashtable PR

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#408]
fns.c:2851:1: warning: no previous prototype for ‘hash_clear’ [-Wmissing-prototypes]
     hash_clear (struct Lisp_Hash_Table *h)

**Comment by DavidDeSimone** [comment]
Good catch, I missed this. I'll submit a PR that fixes it. It should be a harmless for the time being.

**Comment by shaleh** [comment]
It is harmless. No worries.
