### ISSUE TITLE
Style guideline time?

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#412]
Should we order imports alphabetically?

Should we group sections in rust_src/src/lib.rs?

As discussed elsewhere, if the From PR lands, should we allow `into` for returns but use `::from` otherwise?

Is `return` verboten or does @brotzeit  just not like it :)

**Comment by jaccarmac** [comment]
Your point about imports is addressed by #394 :)

As a newcomer, section grouping would be very nice.

**Comment by shaleh** [comment]
You want to start a PR?

On October 25, 2017 6:13:29 PM PDT, Jacob MacDonald <notifications@github.com> wrote:
>Your point about imports is addressed by #394 :)
>
>As a newcomer, section grouping would be very nice.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Wilfred/remacs/issues/412#issuecomment-339520203

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jaccarmac** [comment]
Plan to as soon as I finish navigating the contribution process and solidify my knowledge of it!

**Comment by shaleh** [comment]
No,the imports are not sorted or ordered:

    use lisp::{ExternalPtr, LispObject};
    use remacs_macros::lisp_fn;
    use remacs_sys::{minibuf_level, minibuf_selected_window as current_minibuf_window,
                 selected_window as current_window, EmacsInt, Lisp_Window};
    use marker::marker_position;
    use editfns::point;
    use libc::c_int;

This grab bag makes it a little confusing for the new contributor. Where should I add code? imports? The current plan appears to be just add everything to the end. Which is not satisfying :-)

**Comment by jaccarmac** [comment]
Which file is that from? I had seen that the imports from each module got sorted, and extrapolated that to the modules themselves; Clearly I was wrong.

**Comment by shaleh** [comment]
That is windows.rs

**Comment by jaccarmac** [comment]
rust-lang-nursery/rustfmt#298 is a discussion of this exact issue and has some links to maybe-useful configuration options. I haven't finished reading the thread but it might be useful to other interested parties in this one.

**Comment by shaleh** [comment]
reorder_imports and reorder_import_names are supported now. We can tweak the config and keep rolling.

On October 26, 2017 7:33:00 PM PDT, Jacob MacDonald <notifications@github.com> wrote:
>rust-lang-nursery/rustfmt#298 is a discussion of this exact issue and
>has some links to maybe-useful configuration options. I haven't
>finished reading the thread but it might be useful to other interested
>parties in this one.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Wilfred/remacs/issues/412#issuecomment-339855799

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jaccarmac** [comment]
Unfortunately it doesn't look like there is a rule to take imports of the style
```rust
use a::b;
use a::c;
```
and convert them to
```rust
use a::{b, c};
```
so those will stay somewhat inconsistent.

**Comment by jaccarmac** [comment]
To whoever chooses to create this guide: The import reordering rules do not respect comments, so be careful when creating your patch!

**Comment by shaleh** [comment]
#426 adds the sorting for imports. The rest of this is still up for discussion.

**Comment by Wilfred** [comment]
We should definitely write a style guidelines if it will help newcomers contribute! :)

Sorting for imports is a nice example of something where we don't need a guideline: the computer just fixes it without the developer needing to do anything.

A document with best practices or suggestions would probably be worthwhile -- what do we think it should cover?

**Comment by shaleh** [comment]
Things like don't be a slave to the C code. If there is a better Rust way do it.

If you see order in a file, follow it.

**Comment by shaleh** [comment]
PR #426 includes the tweaked rustfmt config for sorting imports. I also went through and broke out the imports most likely to conflict into multiple lines. So the Q* are their own line.

**Comment by shaleh** [comment]
Perhaps this belongs in CONTRIBUTING instead? It is less a style guideline and more a how we want code organized.

**Comment by shaleh** [comment]
Notes or a link to what ported lisp function comments should look like? Note the example in the README for porting does not keep the original comment.

**Comment by shaleh** [comment]
I am closing this issue. Further issues can be raised for updating the CONTRIBUTING.md contents.
