### ISSUE TITLE
Reorg travis config

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#443]
Current the test stage is defined in the root and the rustfmt stage is defined as a stage. test should also be defined as a stage. [Stages](https://docs.travis-ci.com/user/build-stages/) has all of the details.

Due to my change in #441, we build with a different version of Rust than we used to compile rustfmt. This is sure to bite us some day.

**Comment by Wilfred** [comment]
I think pinning rustc for rustfmt is not a huge problem for build reliability. It does make life harder for new contributors though ("what version of nightly do I need to get this version of rustfmt working?").

**Comment by shaleh** [comment]
True. It would be nice to document it in the Cargo.toml config. Not supported at the moment.

**Comment by tonyday567** [comment]
As a newbie, I'm finding it very hard to maintain rustfmt.

Tracking down why #430 was a travis fail, I found out from this issue that I shouldn't have been updating to a newer rustfmt-nightly (it does say nightly!).  Then on trying to go back, with `cargo install rustfmt-nightly --vers 0.2.9` I get a compile error - presumably because I haven't pinned rustc (I don't know what pinned means yet etc etc).

**Comment by shaleh** [comment]
Yup.

rustup install nightly-2017-10-22
rustup default nightly-2017-10-22

This is what I use with 0.2.9. 0.2.12 which we tried needs the next newer nightly but not the lastest :-)

**Comment by shaleh** [comment]
You can have multiple nightlies installed and switch between them using 'rustup default XX'. rustup even lets you specify that this project (aka directory) uses version A, this other project uses version B, but my system default otherwise is version C.

**Comment by shaleh** [comment]
@Wilfred [rust-toolchain](https://github.com/rust-lang-nursery/rustup.rs/#the-toolchain-file) file is the solution. The user clones remacs, cd into rust_src, runs `rustup install`, then cd to top level and runs make.

**Comment by Wilfred** [comment]
That's a great idea! Having a `rust-toolchain` file is explicit and makes it much easier to get up and running.

I think we could put that file at the root of the repo, unless I'm missing something. Saves a few keystrokes (like a good (r)emacs package!) :)

**Comment by shaleh** [comment]
Yes, in rust_src I believe

**Comment by shaleh** [comment]
PR #451 has my reorg work.

The stages are clearly defined.
There are stages with and without any window system.
OSX and Linux now build with the same configure options.

**Comment by jaccarmac** [comment]
Is this issue resolved or is there more work to do re: Travis?

**Comment by shaleh** [comment]
I would like to see #460 merged before this issue is closed. Otherwise I believe Travis config is good to go.

**Comment by shaleh** [comment]
All complete.
