### ISSUE TITLE
error[E0512]: transmute called with differently sized types: *const libc::c_void (32 bits) to lisp::LispMisc (64 bits)

### ISSUE THREAD

**Issue by mkesper** [Wilfred/remacs#45]
michael@Three:~/src/remacs/rust_src$ cargo build
   Compiling lazy_static v0.2.2
   Compiling libc v0.2.17
   Compiling remacs v0.1.0 (file:///home/michael/src/remacs/rust_src)
error[E0512]: transmute called with differently sized types: *const libc::c_void (32 bits) to lisp::LispMisc (64 bits)
   --> src/lisp.rs:465:14
    |
465 |     unsafe { mem::transmute(XUNTAG(a, LispType::Lisp_Misc)) }
    |              ^^^^^^^^^^^^^^ transmuting between 32 bits and 64 bits

error[E0512]: transmute called with differently sized types: lisp::LispMisc (64 bits) to *const lisp::LispMiscAny (32 bits)
   --> src/lisp.rs:471:14
    |
471 |     unsafe { mem::transmute(XMISC(a)) }
    |              ^^^^^^^^^^^^^^ transmuting between 64 bits and 32 bits

error[E0512]: transmute called with differently sized types: lisp::LispMisc (64 bits) to *const marker::LispMarker (32 bits)
   --> src/lisp.rs:500:14
    |
500 |     unsafe { mem::transmute(XMISC(a)) }
    |              ^^^^^^^^^^^^^^ transmuting between 64 bits and 32 bits

error: aborting due to 3 previous errors

error: Could not compile `remacs`.

**Comment by mkesper** [comment]
rustc 0.14

**Comment by jeandudey** [comment]
#31 and #35 Solves this issue.

**Comment by Wilfred** [comment]
Both of which have been merged, so this should be fixed! 🎉
