### ISSUE TITLE
Document our policy for giving commit access

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#472]
At the moment, I'm making people collaborators (i.e. they can approve and merge PRs) after they've made a couple of non-trivial (i.e anything other than a spelling fix) PRs.

I'd like to document this, to make it clear what the process is. Since we have great CI in place, we should err on giving this out early :)

Any thoughts on what the threshold should be?

**Comment by brotzeit** [comment]
I think it's fine as it is. Why does somebody, who only made a few commits, need write access ? Most contributors make a few commits and leave. I would prefer making those users to collaborators, who stick around at least for some weeks.

**Comment by shaleh** [comment]
After a few good reviews. The first few are often bumpy as we learn the code, the style, etc. Also, maybe ask them if they want to join first. Some people like to solve a few issues and then move on to the next project. Others do not mind sending in the occasional batch of PRs but have no interest in day to day work.

**Comment by Wilfred** [comment]
Here's a handy oneliner for finding recent PR authors who aren't yet collaborators:

```
curl 'https://api.github.com/repos/Wilfred/remacs/pulls?sort=created' | jq -r '.[] | select(.author_association != "COLLABORATOR") | .user.login' | sort | uniq -c
      2 db48x
      1 gaak99
      1 robbert-vdh
      1 rski
```

**Comment by brotzeit** [comment]
@Wilfred I think it works well. If you still want to document this I will add a line in the cookbook.
