### ISSUE TITLE
Enable the wiki for the Project

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#481]
My PR for the the porting cookbook led to a conversation on Gitter. Lots of good suggestions about what should end up in the document. Instead of writing the text via PR this would be better served as a wiki page.

**Comment by Wilfred** [comment]
I didn't spot the conversation on gitter after a quick skim. However, I'm totally happy to enable the wiki.

If it bitrots, I've tended to find that updating docs at PR time works well. Still, let's see what works for us.

**Comment by Wilfred** [comment]
Enabled.

**Comment by shaleh** [comment]
If nothing else, we can use the wiki to draft and then push it into the tree.
