### ISSUE TITLE
[Discussion] Don't use &self for ExternalPtr<T> impls.

### ISSUE THREAD

**Issue by DavidDeSimone** [Wilfred/remacs#482]
Looking through source code, it seems that a common pattern in the remacs code base is

``` rust
type XRef = ExternalPtr<X>;
impl XRef {
  fn foo(&self) { ... }
}
```

`self` here is already a wrapper over a pointer, and so &self is really a pointer to a pointer. I believe this is confusing, and it would be cleaner to have a policy for ExternalPtr<T> impls to take self by value instead of by reference.

**Comment by shaleh** [comment]
:+1:

**Comment by Wilfred** [comment]
Agreed. Do you want to put this in the porting guide? That's probably the best place to document style things like this.

**Comment by shaleh** [comment]
Agreed.
