### ISSUE TITLE
Teach lisp_fn to handle option max="UNEVALLED"

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#519]
#463

**Comment by shaleh** [comment]
The `max` attribute is not used in the Rust port. Instead this is handled by the `lisp_fn` macro. Because of this I chose to add a new option to the `lisp_fn` macro called 'unevalled` which is boolean. When `unevalled` is true, ithe `max_args` field of Lisp_Subr is set to -1 as it expects.

**Comment by shaleh** [comment]
@birkenfeld 's addition of darling made this really straightforward.

**Comment by Wilfred** [comment]
#519 has been merged.
