### ISSUE TITLE
Remacs icon isn't used on macOS builds

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#527]
We end up with the purple Emacs icon rather than the orange Remacs one.

**Comment by shaleh** [comment]
On OSX the culprit is nextstep/Cocoa/Remacs.base/Contents/Resources/Emacs.icns and for anyone using GNUStep it is nextstep/GNUstep/Remacs.base/Resources/emacs.tiff

Both are still the purple version.

**Comment by shaleh** [comment]
Ideally there would be a script/tool that generates these and the Windows icon from a core source.

**Comment by shaleh** [comment]
OSX and GNUStep generated from SVG source. Windows is the only remaining hold out.

@DavidDeSimone ?
