### ISSUE TITLE
Move to #[repr(transparent)] for Lisp_Object

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#568]
This should give us all the advantages of a struct, but without breaking ABI on 32-bit. See #562, https://github.com/rust-lang/rfcs/pull/1758#issuecomment-276465077 and #95.

**Comment by shaleh** [comment]
**GRUMBLE**

https://github.com/rust-lang/rust/issues/43036 is the tracking issue. The RFC was accepted but they are still working out how to implement it.

**Comment by shaleh** [comment]
How do we want to handle this @Wilfred? 32bit is broken as long as my commit is present.

I am loathe to revert it but if it must happen it must.

**Comment by Wilfred** [comment]
I think we should revert it I'm afraid. Sorry.

It'll be really nice when we can use structs (we've done it twice now :) ) but it's not possible today.

**Comment by shaleh** [comment]
Why are we supporting 32 bit? It is routinely broken and no one complains. There is no 32 bit OSX. 32 bit Linux is a dying user base. Fedora and RedHat have largely dropped 32 bit. The story is similar with Windows. For the effort, we are not really getting any return.

**Comment by Wilfred** [comment]
I'm open to dropping 32-bit support. If we do, we should mention that we're 64-bit only and maybe also refuse to compile on 32-bit.

We do get 32-bit bug reports, such as #31, #95 and #497. @jeandudey, would you object to us dropping support for 32-bit?

**Comment by shaleh** [comment]
For the record, I would be open to supporting 32 bit if we could get automation to support it. Even without my recent change the 32 bit was busted and had been for a few commits. So we are just asking for a constant stream of bug reports. To make it worse, the failures look like this:

`EmacsInt::from(foo)` where 32-bit requires 'foo as EmacsInt`. !YUCK! What makes this especially bad is clippy suggests using the `from` style over the `as foo` style so the compiler can give better warnings.

**Comment by shaleh** [comment]
Apparently this was merged in to nightly recently. When someone has time to investigate it we may be able to resolve this and have 32 bit working again.

**Comment by Wilfred** [comment]
Done in #706.
