### ISSUE TITLE
Cannot locate specified Dockerfile

### ISSUE THREAD

**Issue by adelq** [Wilfred/remacs#577]
I tried building Remacs using the provided instructions on using Docker. However, I am unable to start the docker-compose powered build and get the following error:

```
$ docker-compose up -d
Building remacs
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

Docker version 17.12.0-ce, build 486a48d270
docker-compose version 1.18.0, build unknown
Linux version 4.9.68 x86_64

**Comment by shaleh** [comment]
I recently moved them down a folder. The compose file likely needs updating.
