### ISSUE TITLE
Remove !USE_LSB_TAG related code

### ISSUE THREAD

**Issue by 0xAX** [Wilfred/remacs#58]
Hello everyone,

as we assume that ` USE_LSB_TAT=1`, can we remove all code related to `! USE_LSB_TAG`?

**Comment by Wilfred** [comment]
```
/* The following option controls the tagging scheme:
   - USE_LSB_TAG means that we can assume the least 3 bits of pointers are
     always 0, and we can thus use them to hold tag bits, without
     restricting our addressing space.

   If ! USE_LSB_TAG, then use the top 3 bits for tagging, thus
   restricting our possible address range.

   USE_LSB_TAG not only requires the least 3 bits of pointers returned by
   malloc to be 0 but also needs to be able to impose a mult-of-8 alignment
   on the few static Lisp_Objects used: lispsym, all the defsubr, and
   the two special buffers buffer_defaults and buffer_local_symbols.  */
```

If we assume `USE_LSB_TAG` true, we need pointers to be aligned to 8 bytes on all architectures. I'm not sure this is true on 32-bit x86. I suspect `LispSubr` just gets word alignment as we haven't specified yet. We're also dependent on the behaviour of `malloc()`.

I'd like to find a way to simplify this code, but I'm not sure we can with code in the current state. Can you see any solutions?

**Comment by 0xAX** [comment]
> If we assume USE_LSB_TAG true, we need pointers to be aligned to 8 bytes on all architectures. I'm not sure this is true on 32-bit x86.

Yes this could be problem for now. will try to invistigate step by step. Thanks fir reply
