### ISSUE TITLE
window-system port changes spacemacs window colors

### ISSUE THREAD

**Issue by mateon1** [Wilfred/remacs#582]
The colors in spacemacs windows changed (and are extremely broken) as of commit fc64d5a99ae0ebe603117cccbbdc49b0d3983aa7, found by git-bisect.

As of commit 812b84a241a07f1a2a65dd938efbc9691fc391e7, everything worked fine - notably, the background of the window was dark gray with bright gray text, but the next commit changed it to black text on white background with broken colors.

This only affects windowed mode, `src/remacs -nw` is unaffected.

**Comment by shaleh** [comment]
Have you tried a97e31b612f26392519b1beec8596822ec428805?

**Comment by shaleh** [comment]
When you open a window, enter `m-x ielm`. and then run `(framep (selected-frame))` and `(window-system (selected-frame))` what is the output?

**Comment by mateon1** [comment]
I haven't tried a97e31b, but I have tried HEAD (7c8ed09f34caadf565531069d1e73fcfabf2fac4)
The following are on 7c8ed09f34caadf565531069d1e73fcfabf2fac4:
`(framep (selected-frame))` => `x`
`(window-system (selected-frame))` => `nil`
The following are on 812b84a241a07f1a2a65dd938efbc9691fc391e7:
[todo, waiting for build]

**Comment by shaleh** [comment]
Perfect. Thank you. That was the confirmation I needed.

I am looking into this currently.

**Comment by shaleh** [comment]
diff --git a/rust_src/src/frames.rs b/rust_src/src/frames.rs
    index f1b2eca..e38db9e 100644
    --- a/rust_src/src/frames.rs
    +++ b/rust_src/src/frames.rs
    @@ -9,11 +9,10 @@ use remacs_sys::{selected_frame as current_frame, BoolBF, Emac
    sInt, Lisp_Frame};
     use remacs_sys::{fget_column_width, fget_iconified, fget_internal_border_width, fget_left_pos,
                      fget_line_height, fget_minibuffer_window, fget_output_method, fget_root_window,
                      fget_terminal, fget_top_pos, fget_visible, frame_dimension, Fcons, Fselect_window};
    -use remacs_sys::{Qframe_live_p, Qicon, Qns, Qpc, Qt, Qw32, Qx};
    +use remacs_sys::{Qframe_live_p, Qframep, Qicon, Qns, Qpc, Qt, Qw32, Qx};
     
     use lisp::{ExternalPtr, LispObject};
     use lisp::defsubr;
    -use symbols::LispSymbolRef;
     use windows::{selected_window, LispWindowRef};
     
     pub type OutputMethod = c_int;
    @@ -225,14 +224,21 @@ pub fn framep(object: LispObject) -> LispObject {
     /// use `display-graphic-p' or any of the other `display-*-p'
     /// predicates which report frame's specific UI-related capabilities.
     #[lisp_fn(min = "0")]
    -pub fn window_system(frame: Option<LispFrameRef>) -> Option<LispSymbolRef> {
    -    let f = frame.map_or(selected_frame(), |f| f.as_lisp_obj());
    -    let window_system = framep(f);
    +pub fn window_system(mut frame: LispObject) -> LispObject {
    +    if frame.is_nil() {
    +        frame = selected_frame();
    +    }
    +
    +    let window_system = framep(frame);
    +
    +    if window_system.is_nil() {
    +        wrong_type!(Qframep, frame);
    +    }
     
         if window_system.is_t() {
    -        None
    +        LispObject::constant_nil()
         } else {
    -        window_system.as_symbol()
    +        window_system
         }
     }

**Comment by shaleh** [comment]
This may not be the final code, but it does resolve the issue.

**Comment by shaleh** [comment]
#583 resolves the core problem. We were not handling the conversion from a pointer properly. The code above will be placed in another PR as part of a refactor.
