### ISSUE TITLE
Add about `pkgconfig` thing to README?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [Wilfred/remacs#611]
I think this related to issue #155 , #189.

I don't know details about this.

I've got error message like this when I trying ./configure
>Maybe some development libraries/packages are missing?
>If you don't want to link with them give
>     --with-gnutls=no
>as options to configure

I found [this](https://stackoverflow.com/questions/41898925/compiling-filezilla-on-osx) on SO, and I can run remacs now.

`brew install pkgconfig`
`pkg-config --cflags gnutls`

**Comment by db48x** [comment]
Maybe we should add an explicit check for pkgconfig to configure.in, so that the error message is a bit more appropriate. Aside from that, I think a page on the wiki about the dependencies would work better than a long section in the already rather long readme file.

**Comment by shaleh** [comment]
Sounds reasonable @db48x. If `configure` errors out due to missing `pkgconfig` it is obvious to the user what the next step is.

**Comment by accidentalrebel** [comment]
Ran into the same issue as @luceat-lux-vestra. The suggested fix works for me. I agree that the dependencies should be listed somewhere.

**Comment by shaleh** [comment]
PR welcomed

**Comment by jgmize** [comment]
I needed to tell pkg-config where to find zlib in order for it to generate the cflags for gnutls:
```bash
brew install zlib
export LIBGNUTLS_CFLAGS=$(PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig pkg-config --cflags gnutls)
export LIBGNUTLS_LIBS=$(PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig pkg-config --libs gnutls)
./configure
make
```

**Comment by agraven** [comment]
It's my understanding that `PKG_PROG_PKG_CONFIG` should throw an explicit error about a missing pkg-config if that is the case. Do we still want to make an explicit check, e.g. with ´AC_CHECK_TOOL`?

**Comment by shaleh** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884798 has some interesting commentary @agraven

**Comment by agraven** [comment]
That confirms it, the `PKG_PROG_PKG_CONFIG` check makes invoking `AC_CHECK_TOOL` entirely redundant.
