### ISSUE TITLE
port expand-file-name

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#617]
I will try to port this function using [this crate](https://github.com/udoprog/relative-path). If anybody has thoughts on this please tell me.

**Comment by shaleh** [comment]
As we discussed on the Gitter channel my main concern is the author does not hide the OS behind an abstraction. So we need to ensure that we can support all 3 operating systems but not have code like the current C implementation.

We also need to ensure there are plenty of tests that demonstrate the new code works like the original C. It should use examples from the GNU documentation where possible.

**Comment by brotzeit** [comment]
I'm currently not working on this. Hopefully there will be a rust crate that we can use to handle this.
