### ISSUE TITLE
Port minibuffer-depth and minibuffer-prompt

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#626]
```c
DEFUN ("minibuffer-depth", Fminibuffer_depth, Sminibuffer_depth, 0, 0, 0,
       doc: /* Return current depth of activations of minibuffer, a nonnegative integer.  */)
  (void)
{
  return make_number (minibuf_level);
}

DEFUN ("minibuffer-prompt", Fminibuffer_prompt, Sminibuffer_prompt, 0, 0, 0,
       doc: /* Return the prompt string of the currently-active minibuffer.
If no minibuffer is active, return nil.  */)
  (void)
{
  return Fcopy_sequence (minibuf_prompt);
}
```

**Comment by covercash2** [comment]
`minibuffer-depth` was a breeze.

for `minibuffer-prompt` i'm having trouble linking to `static Lisp_Object minibuf-prompt` in `minibuf.c`. is there a config file that i have to declare variables, functions, etc. in to access them from rs source?

**Comment by shaleh** [comment]
Declaring the function with the `lisp_fn` macro will export it for linking. Go ahead and push your PR and we can help you resolve whatever is happening.

**Comment by covercash2** [comment]
it's linking to the C code that i'm having trouble with. i'm trying to import `static Lisp_Object minibuf_prompt` in `minibuf.c` by adding `pub static minibuf_prompt: Lisp_Object` to an `extern "C"` block in `remacs_sys.rs`. but then the linker complains:

```
Undefined symbols for architecture x86_64:
  "_minibuf_prompt", referenced from:
      _Fminibuffer_prompt in libremacs.a(remacs-1f464c21ac5dced9.remacs6-6cd0e2288367d9126c78c506261b8087.rs.rcgu.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by shaleh** [comment]
`static` means it is not exported.

**Comment by shaleh** [comment]
Go ahead and post the half finished PR. We can give you help directly. Just mark it WIP (work in progress).
