### ISSUE TITLE
Ideas to investigate problems in Semantic and TRAMP?

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#628]
Hi!

I am very excited about this project, thanks for the effort. Remacs is working now on my macOS 10.13.2 and it's seems to be faster than regular Emacs (I'm not entirely sure, haven't done any tests).

Some problems that I experience with remacs that I don't experience with ordinary emacs when I use the exact same configuration.

* The semantic parsing of php-mode doesn't find the correct functions for `imenu`
* TRAMP doesn't parse `~/.netrc` for passwords to SSH connections
* I received error with some symbols in `.authinfo.gpg` that I didn't get in regular Emacs
* `mmm-mode` doesn't seem to work, I get an error `Idle Parse Error: "#<buffer index.php> - No support found to parse buffer \"Index.php\"" [3 times]`

Do you have any recommendations for how to investigate problems like these? I can do some research and maybe track down were the errors are coming from.

**Comment by Wilfred** [comment]
Could you confirm that you see these issues with GNU Emacs trunk? It's possible that these issues are just differences in tramp etc that we haven't changed.

If you could provide steps to replicate the issues you're seeing, that would also help us investigate :)

**Comment by shaleh** [comment]
Errors in *Messages* may also be useful

**Comment by cjohansson** [comment]
Alright, I'll do that and make separate issues if I manage to consistently reproduce them in remacs and not in GNU Emacs trunk

**Comment by cjohansson** [comment]
Ok I get identical errors with GNU Emacs trunk, I'm closing this issue

**Comment by shaleh** [comment]
Thank for the update @cjohansson
