### ISSUE TITLE
make install fails (on fedora26)

### ISSUE THREAD

**Issue by DaanHoogland** [Wilfred/remacs#629]
I'm a lurking user that has remacs as his standard emacs, on macos and fedora mostly. once in a while i pretend to develop and i have to re-install on my fedora, as I did last weekend. however the make install step failed with "error[E0554]: #![feature] may not be used on the stable release channel" I am using nightly but maybe not for one of the tools?
`$ src/remacs -Q`
starts a nice windows with a over featured editor but
`$ sudo make install`
gave me a very ugly
```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/dahn/prj/remacs/rust_src/remacs-sys/lib.rs:1:1
  |
1 | #![feature(const_size_of)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `remacs-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make[1]: *** [Makefile:610: ../rust_src/target/release/libremacs_lib.a] Error 101

make[1]:

 Leaving directory '/home/dahn/prj/remacs/src'
make: *** [Makefile:426: src] Error 2

```
I realize the problem might be between chair and keyboard, if so please help. it seems strange to me that a compilation error occurs during install and not during normal build.

**Comment by shaleh** [comment]
I am looking at this currently.

**Comment by DaanHoogland** [comment]
I may well close this myself soon; rustup installs the nightly version for the current user not available under sudo, which in turn is needed to install. remains the question why compile is needed during install.

**Comment by DaanHoogland** [comment]
thanks @shaleh , I just did a sudo make and that didn't go as well as make so i tried sudo rustc --version showing part of the problem

**Comment by shaleh** [comment]
AH. yes, the annoyance of per user Rust toolchain setup.

Once you are satisfied with a working solution would you mind submitting a PR for updating the documentation?

**Comment by DaanHoogland** [comment]
of course, but can you shine a light as to why make install compiles even when make finished succesfully?

**Comment by shaleh** [comment]
No, I cannot. I was just about to look at that.

**Comment by shaleh** [comment]
hmmm.

If I run it like this (as me):

    $ ./configure --prefix=~/tmp/remacs-install --enable-rust-debug
    $ make -j8
    $ make install  # works because it is my path so permissions are OK

I do not see a second compilation. However....

    $ make -j8
    $ sudo su -
    $ cd back to repo
    $ PATH=~me/.cargo/bin:$PATH make install

Now I do see a second compilation as root.

**Comment by shaleh** [comment]
I believe this is an issue with cargo. If you run both the build and the install as the same user the compile does not repeat. If you run the compile as a user and the install as root them cargo goes back through to ensure the dependencies are right and this can trigger a relink of the build.

**Comment by shaleh** [comment]
It looks like build and test as a user. Then when ready to install it build and install as root.

If you are the only user on the system, consider installing it into ~/opt (or ~/local) and adding that path to your PATH.

**Comment by DaanHoogland** [comment]
ok, this is still not nice but i think we should close this with a enterprisial "won't fix".

**Comment by DaanHoogland** [comment]
and thanks for the trouble @shaleh

**Comment by shaleh** [comment]
@DaanHoogland are you still going to submit a doc update?

**Comment by DaanHoogland** [comment]
Yes @shaleh , i will tonight. What I can think of now are teh readme and the install file. Any other places this needs pointing out?

**Comment by shaleh** [comment]
That should cover it.

:+1:
