### ISSUE TITLE
Typo in comment to `wants_header_line`

### ISSUE THREAD

**Issue by zevlg** [Wilfred/remacs#646]
Comment to `wants_header_line` says:

> Moreover, its 'window-mode-line-format' parameter must not be 'none'  and either that parameter or window's buffer's 'mode-line-format' value must be non-nil

It should be `window-header-line-format` and `header-line-format` instead

**Comment by shaleh** [comment]
@zevig this would be a really easy Pull Request for a first PR. You want to give it a swing?
