### ISSUE TITLE
Add clippy to Travis CI?

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#651]
With PR #650 I have clippy silent with the current state of the code. A developer can run `cargo build --features clippy` for their initial compilation. This will both complain about compilation issues and clippy warnings too.

Should we add the clippy compilation to the Travis?

**Comment by Wilfred** [comment]
Hmm, interesting question. I think we should make it easy for contributors to run clippy, but shouldn't mandate that PRs are clean from clippy's perspective.

We require rustfmt but that just requires you to run a command. We also forbid warnings but those are more likely to be bugs and have a very low false positive rate.

I've seen the clippy developers say that they find keeping the clippy codebase clean tricky, and they're skilled rustaceans. My concern is that requiring clippy will make it harder for new contributors.

**Comment by shaleh** [comment]
That is a totally reasonable view. Which is why I started this as an Issue instead of a PR.

What I would like to see is some mechanism to provide clippy output to PR reviewers. Just so we can keep up on any issues that may appear.
