### ISSUE TITLE
Port keymap-parent from keymap.c

### ISSUE THREAD

**Issue by accidentalrebel** [Wilfred/remacs#656]
I'll be porting `keymap-parent` and `keymap_parent` from `keymap.c` next.

```c
/* Return the parent map of KEYMAP, or nil if it has none.
   We assume that KEYMAP is a valid keymap.  */

static Lisp_Object
keymap_parent (Lisp_Object keymap, bool autoload)
{
  Lisp_Object list;

  keymap = get_keymap (keymap, 1, autoload);

  /* Skip past the initial element `keymap'.  */
  list = XCDR (keymap);
  for (; CONSP (list); list = XCDR (list))
    {
      /* See if there is another `keymap'.  */
      if (KEYMAPP (list))
	return list;
    }

  return get_keymap (list, 0, autoload);
}

DEFUN ("keymap-parent", Fkeymap_parent, Skeymap_parent, 1, 1, 0,
       doc: /* Return the parent keymap of KEYMAP.
If KEYMAP has no parent, return nil.  */)
  (Lisp_Object keymap)
{
  return keymap_parent (keymap, 1);
}
```

The for loop line ` for (; CONSP (list); list = XCDR (list))` is a bit confusing at first but I think it's just a different way of iterating through the keymap elements.

**Comment by db48x** [comment]
Yes, each time through that loop, `list` will point to the next tail of the list. `iter_tails` is the equivalent on the Rust side.

**Comment by accidentalrebel** [comment]
Thanks for pointing me in the right direction!

**Comment by accidentalrebel** [comment]
Huh. So it seems to be a bit more complicated than I initially thought.

I need help in determining how I'll port the two functions above.

From my understanding, the function below:
```c
static Lisp_Object keymap_parent (Lisp_Object keymap, bool autoload)
```

would roughly translate to:
```rust
#[no_mangle]
pub extern "C" fn keymap_parent(keymap: Lisp_Object, autoload: bool) -> Lisp_Object
```

And the lisp function:
```c
DEFUN ("keymap-parent", Fkeymap_parent, Skeymap_parent, 1, 1, 0,
       doc: /* Return the parent keymap of KEYMAP.
If KEYMAP has no parent, return nil.  */)
  (Lisp_Object keymap)
```

Would translate to:
```rust
/// Return the parent keymap of KEYMAP.
/// If KEYMAP has no parent, return nil.
#[lisp_fn]
pub fn keymap_parent(keymap: LispObjectl) -> LispObject 
```

The problem here is that both of the ported functions now has the same function names as shown in the error below:
```
the name `keymap_parent` is defined multiple times (`keymap_parent` redefined here) [E0428]
```

One solution I can think of is to rename the first "C" function, but since it is used in a lot of other C files this would mean I'd have to rename it on all of them, which I don't think is a good idea.

Have you guys experienced this before? Any help is welcome! Thanks!

**Comment by shaleh** [comment]
Also covered in the docs. If we need to be more clear, please comment in the wiki or open an Issue against the checked in documentation.

The `lisp_fn` macro takes a "name" and a "c_name" parameter which allows for the function to have a different name than what is exported. This helps if the name is a Rust keyword like the "if" function.

**Comment by shaleh** [comment]
Also, in general you want to use `iter_tails_safe` or `iter_cars_safe`. Otherwise the code will raise errors if the list is too short, not properly formed, etc. The simple answer is if the code has no explicit checking beyond CONSP or NILP then you should use the `_safe` version.

**Comment by accidentalrebel** [comment]
> Also covered in the docs. If we need to be more clear, please comment in the wiki or open an Issue against the checked in documentation.

The docs about the `lisp_fn` macro is actually quite clear now that I am reading it. It's just I forgot about the part where I can set the name. I think I would need to do another pass of the docs so I can go over stuff that did not register with me before.

Thanks!

**Comment by accidentalrebel** [comment]
Hello, I ran into another problem with the porting. Please bear with me as this is a long one.

So I'm trying to port the `keymap_parent` static function show below:

```c
static Lisp_Object keymap_parent (Lisp_Object keymap, bool autoload) {
   ...
}
```

Following the guide found [here](https://github.com/Wilfred/remacs/wiki/Porting-cookbook#porting-widely-used-c-functions), I created the appropriate port and added it to the `keymap.rs` file.

```rust
#[no_mangle]
pub extern "C" fn keymap_parent(keymap: Lisp_Object, _autoload: bool) -> Lisp_Object {
    ...
}
```

I then removed the original `keymap_parent` C function from `keymap.c`.

This, however, threw an error:

```shell
keymap.c:243:10: warning: implicit declaration of function 'keymap_parent' is invalid in C99
      [-Wimplicit-function-declaration]
``` 

After some digging around, I found [this](https://github.com/Wilfred/remacs/pull/297#discussion_r136451086) and learned that I need to declare the function in `keymap.h`.

```c
static Lisp_Object keymap_parent (Lisp_Object, bool);
```

The error went away but a new one surfaced.

```shell
  CC       keymap.o
In file included from keymap.c:55:
./keymap.h:39:20: warning: function 'keymap_parent' has internal linkage but is not defined [-Wundefined-internal]
```

So from the looks of it, the compiler does not seem to detect the `pub extern "C" fn keymap_parent` function that I made in `keymap.rs`.  So to fix this I added a declaration to `remacs-sys/lib.rs`:

```rust
extern "C" {
    ....
    pub fn keymap_parent(keymap: Lisp_Object, autoload: bool) -> Lisp_Object;
    ....
}
```

Building the project now shows the following:

```shell
  ....
  GEN      loaddefs.el
   Compiling remacs-sys v0.1.0 (file:///Users/arebel-mac/development/projects/rust/remacs/rust_src/remacs-sys)
   Compiling remacs v0.1.0 (file:///Users/arebel-mac/development/projects/rust/remacs/rust_src)
    Finished dev [unoptimized + debuginfo] target(s) in 6.55 secs
  CCLD     temacs
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
../build-aux/install-sh -c -d ../etc
LC_ALL=C ./temacs -batch  -l loadup dump
```

The last line `LC_ALL=C ./temacs -batch  -l loadup dump`, just loops on forever no matter how long I wait. So it seems that the rust compilation completes but not the make compilation.

I'm at a lost here and in need of guidance. I feel I'm doing something wrong or missed something important. Any help would be greatly appreciated.

Thanks!

**Comment by shaleh** [comment]
The error is the use of the word "static". In C and in Rust, "static" means not exported, local only to the file it is defined in. In the port, you are taking a function that was not exported and are now making it exported. Drop the static keyword and things should work out better.

**Comment by accidentalrebel** [comment]
@shaleh  helped me figure out the cause of the infinitely looping compilation. The problem was that I only made a bare port of the function with no logic (seen [here](https://github.com/Wilfred/remacs/commit/e85ddcbebcda7bf50f41c434517b37b1df6c51a4)). Since the function is used in other parts of the codebase, somewhere during compilation an infinite loop occurred.

I'll be correcting this in the next commit.
