### ISSUE TITLE
Naming conventions for elisp test functions.

### ISSUE THREAD

**Issue by accidentalrebel** [Wilfred/remacs#665]
Do we have naming conventions for elisp test functions? Currently, I follow something along the lines of `<file-name>-<function-name>-tests`. I've seen others do `<file-name>-test--<function-name>`. The tests in `remacs/test/src` doesn't seem to have a convention as they vary per file.

I ask because I plan to rename my test functions as well as update the wiki to explicitly say what convention to follow.

Thanks!

**Comment by shaleh** [comment]
Look at the files in `test/rust_src/src`. If you have ideas to improve it, please make a recommendation.

**Comment by accidentalrebel** [comment]
Got it. Based on the other files the convention is `<file-name>-test--<function-name>`. Will be using this going forward and update the wiki for future porters.
