### ISSUE TITLE
Error startup with init.el

### ISSUE THREAD

**Issue by guoxiangyang** [Wilfred/remacs#670]
```commit c001681bd9eafe1bbfec226f56ab503810982bd0``
```
File mode specification error: (error avl-tree--dummyroot accessing a non-avl-tree-)               
error in process sentinel: org-element--cache-find: avl-tree--dummyroot accessing a non-avl-tree-  
error in process sentinel: avl-tree--dummyroot accessing a non-avl-tree-                           
scroll-down-command: Beginning of buffer                                                           
scroll-down-command: Beginning of buffer                                                           
```

```
gxy@local:~/work/remacs$ lsb_release  -a
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: LinuxMint
Description:    Linux Mint 18.3 Sylvia
Release:        18.3
Codename:       sylvia
```

**Comment by shaleh** [comment]
@guoxiangyang have you confirmed that commit causes your issue? Could you please describe more of your configuration? Maybe provide a small test case?

**Comment by shaleh** [comment]
Is this file current? https://github.com/guoxiangyang/.emacs.d/blob/master/init.el

**Comment by guoxiangyang** [comment]
It's strange that I just receive the notification email right now.
The .emacs.d repo you see 8 days before is very old. I just push my current .emacs.d.

HTH

**Comment by shaleh** [comment]
Yes, that will be helpful. Thank you.

**Comment by aborn** [comment]
Set org-element-use-cache to nil

`(setq org-element-use-cache nil)`

**Comment by brotzeit** [comment]
@guoxiangyang Does it work now ?

**Comment by guoxiangyang** [comment]
It works now.

**Comment by mario-bermonti** [comment]
> Set org-element-use-cache to nil
> 
> `(setq org-element-use-cache nil)`

This worked for me.
