### ISSUE TITLE
New compilation warnings caused by PR #660

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#672]
keymap.h:37:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     extern Lisp_Object get_where_is_cache();
     ^
    keymap.h:39:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     extern Lisp_Object get_where_is_cache_keymaps();
     ^

@accidentalrebel this should be a quick one.

**Comment by accidentalrebel** [comment]
I tried looking for this warning but couldn't find it when running `make` nor `cargo build`. Do I need to set some options when running `make` in order to show this warning? Thanks!

**Comment by accidentalrebel** [comment]
Aha, found it. Can be set with this `./configure CFLAGS="-Wstrict-prototypes"`.
