### ISSUE TITLE
Invalid op-codes for MELPA packages when switching between remacs and gnu emacs

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#674]
Hi!

Sometimes when I switch between gnu emacs and remacs I get invalid op-code warnings, I resolve this by deleting the elpa directory and re-installing and compiling packages. Is this kind of error expected or could it be a bug? If it could be a bug I can narrow down the issue and try find a reproducible case for it.

**Comment by shaleh** [comment]
You are probably be jumping between Emacs versions so the compiled elisp is not valid. Removing the .elc files and recompiling should handle it.

**Comment by accidentalrebel** [comment]
I think I faced this before. My GNU Emacs version was Version 25 while Remacs was already version 26. I remember removing the `.elc` files and it certainly did the trick.

**Comment by cjohansson** [comment]
Ah I see, alright I'll close this
