### ISSUE TITLE
remacs becomes unresponsive when opening random new window on macOS 10.13.3

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#693]
Sometimes when I open random window, like a *Help* buffer or *Debug Backtrace* or *Magit*  remacs gets unresponsive and I have to force quit it. I don't get these errors in latest GNU Emacs trunk. 

Pressing Ctrl + G doesn't work either. I first experienced this 3-4 weeks ago. Seems to happen entirely random but it's always related to opening a new window and it happens frequently.

**Comment by accidentalrebel** [comment]
Could it be you've built Remacs in debug mode? I remember also experiencing slowdowns before but realized that I needed to make a release build. After that everything was smooth.

```
$ ./autogen.sh
$ ./configure --enable-rust-debug
$ make
```
> For a release build, don't pass --enable-rust-debug.

More details [here](https://github.com/Wilfred/remacs#building-remacs).

**Comment by shaleh** [comment]
That said, we should keep on eye on this to see if it goes away as we continue the port. If not there may be a subtle issue that is aggravated in debug mode.

**Comment by cjohansson** [comment]
I'm not using the debug-flag, this was my entire update script:

```
cd ~/Documents/remacs/; git pull origin master; rustup update; rustup update `cat rust-toolchain`; ./autogen.sh; ./configure; make;
```

I have changed it to
```
cd ~/Documents/remacs/; git pull origin master; rustup update; rustup install `cat rust-toolchain`; ./autogen.sh; ./configure; make clean; make;
```

Maybe a cache for make was causing the issue? Maybe compiled lisp-files? Currently can't compile, get this error:

```
unexec: unrecognized section __thread_bss in __DATA segment
make[1]: *** [bootstrap-emacs] Error 1
make: *** [src] Error 2
```

**Comment by shaleh** [comment]
I see this too. However, the OSX builder on older systems works because our Travis build is still working. I have not had a chance to investigate. I _think_ it has something to do with the unexec crate.

**Comment by cjohansson** [comment]
My rust version is `nightly-2018-02-08-x86_64-apple-darwin unchanged - rustc 1.25.0-nightly (29c8276ce 2018-02-07)`, is it the right one?

I run this command from terminal ```rustup install `cat rust-toolchain`;```

Still same error
```
--- Load Commands written to Output File ---
Writing segment __PAGEZERO       @        0 (       0/0x100000000 @          0)
Writing segment __TEXT           @        0 (0x5ee000/0x5ee000 @ 0x100000000)
Writing segment __DATA           @ 0x5ee000 (0x43c000/0x43c000 @ 0x1005ee000)
        section __nl_symbol_ptr  at 0x5ee000 - 0x5ee010 (sz:     0x10)
        section __got            at 0x5ee010 - 0x5ee2c8 (sz:    0x2b8)
        section __la_symbol_ptr  at 0x5ee2c8 - 0x5ef638 (sz:   0x1370)
        section __const          at 0x5ef640 - 0x60aac8 (sz:  0x1b488)
        section __cfstring       at 0x60aac8 - 0x60b348 (sz:    0x880)
        section __objc_classlist at 0x60b348 - 0x60b3c0 (sz:     0x78)
        section __objc_catlist   at 0x60b3c0 - 0x60b3c8 (sz:      0x8)
        section __objc_protolist at 0x60b3c8 - 0x60b3f0 (sz:     0x28)
        section __objc_imageinfo at 0x60b3f0 - 0x60b3f8 (sz:      0x8)
        section __objc_const     at 0x60b3f8 - 0x60f008 (sz:   0x3c10)
        section __objc_selrefs   at 0x60f008 - 0x610168 (sz:   0x1160)
        section __objc_classrefs at 0x610168 - 0x610388 (sz:    0x220)
        section __objc_superrefs at 0x610388 - 0x6103e8 (sz:     0x60)
        section __objc_ivar      at 0x6103e8 - 0x6105e0 (sz:    0x1f8)
        section __objc_data      at 0x6105e0 - 0x610a90 (sz:    0x4b0)
        section __data           at 0x610a90 - 0x979360 (sz: 0x3688d0)
        section __thread_vars    at 0x979360 - 0x979408 (sz:     0xa8)
        section __thread_data    at 0x979410 - 0x979440 (sz:     0x30)
unexec: unrecognized section __thread_bss in __DATA segment
make[1]: *** [bootstrap-emacs] Error 1
make: *** [src] Error 2
```

**Comment by shaleh** [comment]
I just ran a successful build from a clean tree on my High Sierra 10.3.3 system.

**Comment by cjohansson** [comment]
It's working now for me as well 👍

**Comment by shaleh** [comment]
Back to the original issue.

Can you come up with a minimum set of steps to reproduce it? Something like:

1. Fire up a new remacs with the following configuration....
1. Run this bit of elisp
1. Observe that remacs is unresponsive

Not the bit about configuration. Try to reproduce the issue when running `remacs -Q` which loads _NO_ elisp that is not required by the editor. No user config, minimal packages, etc. From there you can make a small init.el which loads just enough to demonstrate the problem and add it to this Issue.

**Comment by cjohansson** [comment]
Yeah, I haven’t noticed any freezes yet. Been using it for a couple of hours now so the problem seems to be gone. I’m closing this and will create a new issue if I get the problem again and I’ll try to narrow it down by using minimal or zero config.
