### ISSUE TITLE
Compilation error in `lisp_fn`

### ISSUE THREAD

**Issue by pipcet** [Wilfred/remacs#704]
This line in remacs-macros/lib.rs is giving me a compilation error on current nightly:
```
    vec![tokens.parse().unwrap(), fn_ts].into_iter().collect()
```
The error is
```
a collection of type `proc_macro::TokenStream` cannot be built from an iterator over elements of type `proc_macro::TokenStream`
```
I'm very new to the Rust world, but the workaround that's described in the comment above that code, of putting `#fn_item` into the `quote!` and simply using `tokens.parse().unwrap()`, appears to work. I don't know whether error messages for that approach are still broken, though.

**Comment by shaleh** [comment]
We have the Rust version we support specified in the `rust-toolchain` file in the top of the tree. The build should use that unless you force it not to.

**Comment by pipcet** [comment]
Thanks! I was following the instructions provided by `autogen.sh`, which told me to run `rustup override set nightly`. Maybe that's why it's using the latest nightly?

**Comment by shaleh** [comment]
Yes, that is exactly why! Good catch. It should *NOT* say that any longer.

**Comment by shaleh** [comment]
@pipcet care to send in a PR?

**Comment by pipcet** [comment]
Here's the code I'm currently using, since I have dependencies on a newer toolchain:

```
    // we could put #fn_item into the quoted code above, but doing so
    // drops all of the line numbers on the floor and causes the
    // compiler to attribute any errors in the function to the macro
    // invocation instead.
    let ts: TokenStream = tokens.parse().unwrap();
    ts.into_iter().chain(fn_ts).collect()
```

I think that does the same thing as the original code (does it?), but is a bit easier to read.

**Comment by shaleh** [comment]
rustup will install multiple versions. The benefit of the `rust-toolchain` file is the right version will be used for the local project without interfering with the "global" version _and_ without requiring your intervention.
