### ISSUE TITLE
Can Lisp_Object and LispObject be unified?

### ISSUE THREAD

**Issue by pipcet** [Wilfred/remacs#706]
I've started looking around the code a little, and the first thing that I'm wondering about is whether all this `from_raw` and `to_raw` stuff is strictly necessary.

There are currently something like 558 calls to these functions, not counting the ones that get autogenerated by `#[lisp_fn]`. Is that really worth the (nice, certainly) isolation of having the types live in separate crates?

Maybe there's a deeper difference between the types that I'm missing (if so, in my defense, it's not very obvious from the names), but I've played around with merging the remacs_sys crate into the remacs crate, and that appears to enable me to remove most of the calls.

Is there a better/Rustier way?

**Comment by shaleh** [comment]
We have kept them separate to catch mistakes. We are using the type system as a safety net.

**Comment by pipcet** [comment]
Sorry for being dense, but what kind of mistake? If Lisp*Objects were merged, treating one as the other wouldn't be a mistake.

The one use case I can think of is to drop the Copy or Clone traits for LispObjects, but I'm not convinced that's actually a good idea.

**Comment by shaleh** [comment]
Basically we treat `Lisp_Object` as meaning "for C" and `LispObject` as meaning "for Rust". This catches mistakes during porting.

**Comment by shaleh** [comment]
Deeper reason.

`typedef EMACS_INT Lisp_Object;`

in Rust a typedef is indistinguishable from the aliased object. So basically `Lisp_Object` looks like a `int64`. So we need to make a struct type in Rust.

**Comment by pipcet** [comment]
> So we need to make a struct type in Rust.

No argument there. Do we need two struct types, though?
```
pub struct Lisp_Object(EmacsInt);
pub struct LispObject(Lisp_Object);
```
is what's currently in the code. My proposal is to use
```
pub struct LispObject(EmacsInt);
```
and drop the Lisp_Object.

**Comment by Wilfred** [comment]
The problem here is that the C code has multiple different definitions for `Lisp_Object`.

It can be:

```c
typedef EMACS_INT Lisp_Object;
```

or it can be a struct wrapping an int. There is actually a config option to toggle whether a struct is used. (I imagine Remacs won't build if you change this flag.)

To make complicate matters further, structs have different calling conventions on 32-bit. I'm on my phone, but if you look at my comment on the repr(transparent) RFC I give an example.

We've not had any 32-bit issues or PRs submitted in some time, and I think it's a shrinking use case.

I don't see anything stopping us moving to a single struct if we go 64-bit only.

**Comment by pipcet** [comment]
Is 32-bit currently broken? Right now the Rust code unconditionally uses a (Rust) struct, and uses `repr(C)` rather than `repr(transparent)`. I'm pretty sure that should work on 32-bit Linux, but I honestly don't know about 32-bit Windows.

Anyway, I don't think anyone is proposing we might have to switch to a typedef for Lisp_Objects.

**Comment by shaleh** [comment]
repr(transparent) is new. We want to support it but have not had the time yet. a PR would be welcomed. There are docker configs for 32 bit in the tree to aid testing.

**Comment by Wilfred** [comment]
Yep, I suspect 32-bit was broken. Until #562 we had an alias for `EmacsInt` for `Lisp_Object`.

Still, now `repr(transparent)` has landed, that should all work nicely :)

**Comment by Wilfred** [comment]
I've been going over a big merge today and this really stuck out to me as something that would make the Remacs code easier to work with. @pipcet would you like to create a PR for this?
