### ISSUE TITLE
Application icon missing on Mac OS

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#711]
I'm on Mac OS `10.13.4` and when I `make install` the Application Icon is missing. I have traced this issue down to invalid file-name `Emacs.icns` instead of `Remacs.icns` as specified in `Contents/Info.plist`. 

The new file `Contents/Resources/Remacs.icns` also need to be updated with better resolution images that are available in folder `Contents/Resources/Emacs.iconset`.

It it ok if I take on this issue?

**Comment by jaccarmac** [comment]
This ready to close? Looks like the PR merge didn't auto-mark it.
