### ISSUE TITLE
re-builder freezes buffers

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#717]
When I start `M-x` `re-builder` in a clean remacs instance (started with `src/remacs -Q`) all buffers freezes, however it seems that the application is responsive in some way, the mini-buffer is updating on events and pop-ups are opened when I force quit the application but other than that it's frozen.

**Comment by cjohansson** [comment]
Update, I don't get this issue if I run remacs with `src/remacs -Q -nw` so it seems to be related to the GUI mode. I use macOS 10.13.4

**Comment by shaleh** [comment]
```
(defun my/test-issue ()
  ;; (interactive)
  (select-window (or (get-buffer-window "*my-test*")
                       (progn
                         (split-window (selected-window) (- (window-height) 4)))))
  (switch-to-buffer (get-buffer-create "*my-test*")))
```

Above is the minimal test case to reproduce. `M-: (my/test-issue)` or uncomment the interactive line.

**Comment by cjohansson** [comment]
Yeah I can confirm I get the same issue with your test case

**Comment by shaleh** [comment]
This does _not_ happen on my Linux system. I just built from master to confirm.

**Comment by cjohansson** [comment]
Strange, it seems like the issue is related to running `(select-window)` before `(switch-to-buffer)`. Running them independently works.

**These examples work:**

```
(defun my/test-issue ()
  (select-window (or (get-buffer-window "*my-test*")
                       (progn
                         (split-window (selected-window) (- (window-height) 4)))))
  (let (buffer (get-buffer-create "*my-test*"))
    ;; (switch-to-buffer buffer)
    ))
(my/test-issue)
```

```
(defun my/test-issue ()
  ;; (select-window (or (get-buffer-window "*my-test*")
  ;;                      (progn
  ;;                        (split-window (selected-window) (- (window-height) 4)))))
  (let (buffer (get-buffer-create "*my-test*"))
    (switch-to-buffer buffer)
    ))
(my/test-issue)
```

**This hangs on line with** `(switch-to-buffer)`:

```
(defun my/test-issue ()
  (select-window (or (get-buffer-window "*my-test*")
                       (progn
                         (split-window (selected-window) (- (window-height) 4)))))
  (let (buffer (get-buffer-create "*my-test*"))
    (switch-to-buffer buffer)
    ))
(my/test-issue)
```

**Comment by shaleh** [comment]
Is it the select or the split-window?

**Comment by cjohansson** [comment]
It seems like it's the split-window, same issue with this:

```
(defun my/test-issue ()
  (split-window (selected-window) (- (window-height) 4))
  (let (buffer (get-buffer-create "*my-test*"))
    (switch-to-buffer buffer)
    ))
(my/test-issue)
```

This works:

```
(defun my/test-issue ()
  (split-window (selected-window) (- (window-height) 4))
  ;; (let (buffer (get-buffer-create "*my-test*"))
     (switch-to-buffer buffer)
;; )
  )
(my/test-issue)
```

This works as well:

```
(defun my/test-issue ()
  (split-window (selected-window) (- (window-height) 4))
  (let (buffer (get-buffer-create "*my-test*"))
    ;;(switch-to-buffer buffer)
    )
  )
(my/test-issue)
```

So the combination of (split-window) with (get-buffer-create) and (switch-to-buffer)...

**Comment by cjohansson** [comment]
This causes same issue so (get-buffer-create) is not a part of the issue:

```
(defun my/test-issue ()
  (split-window (selected-window) (- (window-height) 4))
  (let (buffer (current-buffer))
    (switch-to-buffer buffer)
     )
  )
(my/test-issue)
```

**Comment by cjohansson** [comment]
More testing, I noticed my previous tests had some invalid syntax..

**Works**
```
(let ((buffer (get-buffer-create "*my-test*")))
  (switch-to-buffer buffer)
  )
```

**Works**
```
(split-window (selected-window) (- (window-height) 4))
(let ((buffer (get-buffer-create "*my-test*")))
  ;; (switch-to-buffer buffer)
  )
```

**Works**
```
(split-window (selected-window) (- (window-height) 4))
(let ((buffer (current-buffer)))
  (switch-to-buffer buffer)
  )
```

**Works**
```
;; (split-window (selected-window) (- (window-height) 4))
(let ((buffer (get-buffer-create "*my-test*")))
  (switch-to-buffer buffer)
  )
```


**Fails**
```
(split-window (selected-window) (- (window-height) 4))
(let ((buffer (get-buffer-create "*my-test*")))
  (switch-to-buffer buffer)
  )
```

So it seems like something with combination of split-window with get-buffer-create and switch-to-buffer causes a error in Mac OS GUI mode

**Comment by cjohansson** [comment]
It is the `set-window-buffer` call inside `switch-to-buffer` that triggers the error

**Fails**:
```
(split-window (selected-window) (- (window-height) 4))
(let ((buffer (get-buffer-create "*my-test*")))
  (set-window-buffer nil buffer)
  )
```

**Comment by cjohansson** [comment]
**Works:**

```
(split-window (selected-window) (- (window-height) 11))
(let ((buffer (get-buffer-create "*my-test*")))
  (set-window-buffer nil buffer))
```

So something is happening when window-height is 10 or less that causes a freeze

**Comment by shaleh** [comment]
Good hunting.

**Comment by cjohansson** [comment]
Ok found something..

1. Start a clean remacs `src/remacs -Q`
2. Enable debug on quit `M-x` `toggle-debug-on-quit`
3. Run `re-builder` to freeze window
4. Press `C-g` to quit process, window title changes to *Backtrace*
5. Minimize window
6. Open window again, change it's size and minimize it again
7. Open window again, display is now responsive again

The backtrace is something like this:

```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
  redisplay()
  sit-for(2)
  execute-extended-command(nil "re-builder" "re-bui")
  funcall-interactively(execute-extended-command nil "re-builder" "re-bui")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

The error is somewhere in redisplay? It seems like changing window size + minimizing + opening resolves the issue

**Comment by cjohansson** [comment]
Ok after running the `git bisect` procedure I found out this:

```
2d47adc4c431081a6b252ab13d63b39cd36750b3 is the first bad commit
commit 2d47adc4c431081a6b252ab13d63b39cd36750b3
Author: Sean Perry <shaleh@speakeasy.net>
Date:   Mon Feb 26 20:47:36 2018 -0800

    Port CURRENT_MODE_LINE_HEIGHT (#518)
    
    Also CURRENT_MODE_LINE_FACE_ID and CURRENT_MODE_LINE_FACE_ID_3
    
    Replace the original macros with extern references.

:040000 040000 be03aee9e1e1cbb7c0f27af9aaee4d3511489b15 7bf3a10c57a84c45d4386fb21f91e1ec8d0c59d3 M	rust_src
:040000 040000 8a3409df364dd94b57ae9a5129a0ffc7ff0d86a5 f6e1898970e757c5250c9b1998c39e8e2e9f7804 M	src
bisect run success
```

**Comment by shaleh** [comment]
All rounds lead to this change it appears. Good work!

**Comment by cjohansson** [comment]
This issue seems to persist after that [commit](https://github.com/Wilfred/remacs/commit/785d425b4bc8a8bc6bd47f7e9f2f6fcb12536b57)

**Comment by shaleh** [comment]
Confirmed. Drat.

**Comment by cjohansson** [comment]
I added:

```
        } else if matrix_mode_line_height != 0 {
            let frame = self.frame().as_frame_or_error();
            let window = selected_window().as_window_or_error();
            let mode_line_height = unsafe {
                estimate_mode_line_height(frame.as_ptr(), CURRENT_MODE_LINE_FACE_ID(window))
            };
            unsafe { wset_mode_line_height(self.as_mut(), matrix_mode_line_height) };
            if matrix_mode_line_height == 1 {
                panic!("matrix_mode_line_height: {:?}, mode_line_height: {:?}", matrix_mode_line_height, mode_line_height);
            }
            matrix_mode_line_height
        } else {

```

And after running `re-builder` I get this output
`thread '<unnamed>' panicked at 'matrix_mode_line_height: 1, mode_line_height: 14', src/windows.rs:81:17
`

The estimate line-height is 14px but the glyph row is 1px, something is still wrong with the glyph row

**Comment by cjohansson** [comment]
Yeah it seems to be resolved now 😀 Great work, closing this

**Comment by shaleh** [comment]
Partially my work and partially @db48x merging in the bindgen so we no longer have C vs. Rust confusions.
