### ISSUE TITLE
New Rust compiler breaks OSX build

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#725]
The build dies trying to create the remacs binary.

**Comment by cjohansson** [comment]
I can't reproduce this issue on macOS 10.13.4, build is successful, I run this command:

```cd ~/Documents/remacs/; git pull origin master; rustup update `cat rust-toolchain`; ./autogen.sh; ./configure; make clean; make; make install;```

Where `~/Documents/remacs/` is this GIT repo

**Comment by cjohansson** [comment]
Works for me on macOS 10.13.4. I run this command:

```cd ~/Documents/remacs/; git pull origin master; rustup update `cat rust-toolchain`; ./autogen.sh; ./configure; make clean; make; make install;```

Where `~/Documents/remacs/` is connected to this repository

**Comment by Wilfred** [comment]
@shaleh it breaks on your machine, or on Travis?

**Comment by shaleh** [comment]
Both @Wilfred, see #692 

@cjohansson I am talking about updating to any Rust version newer than in our rust-toolchain file. The version checked into the remacs tree does indeed work.
