### ISSUE TITLE
`suggest` crashes Remacs

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/remacs#731]
Remacs crashes abruptly when running the [`suggest` package](https://github.com/wilfred/suggest.el). `suggest` takes some inputs and a desired output and attempts to find some Elisp code that will produce that output from those inputs. Here is an example:

```
;; Inputs (one per line):
5

;; Desired output:
nil

;; Suggestions:

(not 5) ;=> nil
(listp 5) ;=> nil
(consp 5) ;=> nil
(floatp 5) ;=> nil
(arrayp 5) ;=> nil
```

I'm looking for a function that takes 5 and returns `nil`, and those are `suggest`'s suggestions. That works fine on Remacs, and so do certain other queries. On the other hand, changing the `nil` to `t` and running the query causes Remacs to crash without warning, whereas on GNU Emacs it produces the expected output:

```
;; Inputs (one per line):
5

;; Desired output:
t

;; Suggestions:

(oddp 5) ;=> t
(atom 5) ;=> t
(natnump 5) ;=> t
(numberp 5) ;=> t
(integerp 5) ;=> t
```

I haven't figured out how to characterize the input/output sets that crash it, but here are some more examples.

Works:
```
;; Inputs (one per line):
'(1 2 3)
'(4 5 6)

;; Desired output:
'(1 2 3 4 5 6)
```

Crashes:
```
;; Inputs (one per line):
'(1 2 3)
'(4 5 6)

;; Desired output:
'((1 2 3) (4 5 6))
```

Works:
```
;; Inputs (one per line):
'(1)

;; Desired output:
'()
```

Works:
```
;; Inputs (one per line):
'()

;; Desired output:
'()
```

Crashes:
```
;; Inputs (one per line):
'()

;; Desired output:
'(1)
```

When I say "crashes", I mean the Remacs window vanishes immediately and a few seconds later an Apple dialog box comes up that says "Remacs quit unexpectedly." Occasionally it will freeze for a few seconds before crashing.

These crash triggers are pretty reliable, at least for me. I can post a crash report if it would be helpful.

`Remacs 26.0.60 (build 4, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2018-05-07`

**Comment by db48x** [comment]
Nice. I got a crash when I ran `M-x suggest`, but my build might not be perfectly clean.

**Comment by nickdrozd** [comment]
I have also had that happen. In fact, a few days ago I was getting the behavior described above for a while, and then it started crashing immediately when running `M-x suggest`. Did the binary get corrupted or something? Is that even possible?

**Comment by Wilfred** [comment]
Ooh, interesting! Suggest basically fuzzes your (r)emacs instance, so it does find bugs.

The best approach is to run remacs under gdb to get a backtrace, but you can also modify suggest.el to print (to stdout so it persists) each function before it calls the function and crashes.

**Comment by nickdrozd** [comment]
I poked around a little in `suggest.el` and determined that `intern` is the problem. No, I don't mean that weird kid at your office who says inappropriate things from time to time, I mean the function that converts strings into symbols. Making the following change fixes this problem completely:
```
modified   suggest.el
@@ -240,7 +240,7 @@
    #'symbol-name
    #'symbol-value
    #'symbol-file
-   #'intern
+   ;; #'intern
    ;; Converting between types
    #'string-to-list
```
I have no idea why.

**Comment by Wilfred** [comment]
`(intern 1 2)` is killing Remacs.
