### ISSUE TITLE
Cannot compile using newer nightly due to proc macro issue

### ISSUE THREAD

**Issue by darkanthey** [Wilfred/remacs#752]
This happened with the latest git master repo. 
I used rust nightly-2018-05-01. This rust works well before.

`Compiling remacs-lib v0.1.0 (file:///home/xxx/remacs_src/rust_src/remacs-lib)
error: custom attribute panicked
   --> src/base64.rs:341:1
    |
341 | #[lisp_fn(min = "1")]
    | ^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: Invalid lisp_fn attribute: Unexpected literal type `string`
error: aborting due to previous error`

**Comment by shaleh** [comment]
We saw this on the Windows appveyor builds when the wrong compiler was being installed. Make sure the Rust compiler version run for this build matches the version in `rust-toolchain`. The command `rustup` allows you to specify a version for just one project using an override. You do not have to switch the compiler used for other Rust projects.

**Comment by shaleh** [comment]
ok. This is actually an issue with the latest nightly. Something is changing in proc macro land. We need to get a handle on it and perhaps make some noise.

**Comment by nitishch** [comment]
@shaleh The fix that I talked about in Gitter channel is after including your changes in #759. So I guess this and #759 have to be merged in a single branch.
