### ISSUE TITLE
"Invalid function: lamba" in .emacs file

### ISSUE THREAD

**Issue by jmelesky** [Wilfred/remacs#758]
The following portion of my `.emacs` file is causing the message "Invalid function: lambda" on remacs startup, and has been for some weeks.

It runs without complaint on emacs 25.3 (and several spot-checked earlier versions).

    (setq
     emacs-lisp-mode-hook '(lambda () (font-lock-mode 1))
     c-mode-hook '(lambda () (font-lock-mode 1))
     c++-mode-hook '(lambda () (font-lock-mode 1))
     html-mode-hook '(lambda () (font-lock-mode 1))
     shell-script-mode-hook '(lambda () (font-lock-mode 1))
     makefile-mode-hook '(lambda () (font-lock-mode 1))
     mutt-mode-hook '(lambda () (font-lock-mode 1))
     perl-mode-hook '(lambda () (font-lock-mode 1))
     cperl-mode-hook '(lambda () (font-lock-mode 1))
     c++-c-mode-hook '(lambda () (font-lock-mode 1))
     tex-mode-hook '(lambda () (font-lock-mode 1))
     shell-mode-hook '(lambda () (font-lock-mode 1))
     dired-mode-hook '(lambda () (font-lock-mode 1))
     compilation-mode-hook '(lambda () (font-lock-mode 1)))

Happy to provide any further detail required.

(Edited to add: There's a very simple workaround in my case, which is remove the code, as it's old and no longer needed. The behavior discrepancy is troubling, though, which is why I mention it.)

**Comment by Wilfred** [comment]
Could you start remacs with `--debug-init` to get a traceback?

**Comment by shaleh** [comment]
You can also but this in a .el file and test for the regression using the `git bisect` tools in `rust_src/admin`.

**Comment by nitishch** [comment]
Smaller reproducible case:

```elisp
    (setq temp-hook '(lambda () (setq c 1)))
    (run-hooks 'temp-hook)
```

**Comment by jmelesky** [comment]
I finally get a chance to try and capture debug output, and it turns out y'all have already fixed the issue!

Thank you much. Closing this, as it's been fixed in master.
