### ISSUE TITLE
A simple test program to check if the right rustmt is installed.

### ISSUE THREAD

**Issue by rocky** [Wilfred/remacs#764]
Since having the code formatted with a specific version of rustfmt is needed, (and is probably not the default rustfmt that people will have), perhaps there should be a check up front in "make" to check that and warn if the wrong version is used. 

There are a couple ways this could be done: either by checking the version number (`rustfmt -V`) and checking against an acceptable list -- or and I like this better -- by running rustfmt on some rust programs that are known to come out formatted differently with improper rustfmt versions. 

But note, for those who just want to build remacs and don't care if the Rust files are formatted in a way for contributing , `make` should warn if it detects a problem, not fail. And it should be possible to build remacs even if you don't have rustfmt installed.

**Comment by shaleh** [comment]
A better way to handle this is a local git commit hook. It would prevent you from checking in code formatted with the wrong tool. We could ship the hook in `rust_src/admin` and have installation instructions in the CONTRIBUTING.md file.

**Comment by rocky** [comment]
Don't think that is better - I'd want to know _before_ I run git commit.

**Comment by nitishch** [comment]
@shaleh I started using 3 pre-commit hooks actually. One to check if any `eassert` is used, one to check for `emacs_abort` and one to check if all Rust code has been formatted with `rustfmt`.

**Comment by shaleh** [comment]
Post a PR @nitishch. Add it to `rust_src/admin`.

**Comment by shaleh** [comment]
Also, as I comment on #773 the rustfmt version check is no longer required. rustup will now handle this for us.

**Comment by brotzeit** [comment]
> Also, as I comment on #773 the rustfmt version check is no longer required. rustup will now handle this for us.
