### ISSUE TITLE
Linux: Unable to find libclang

### ISSUE THREAD

**Issue by gaak99** [Wilfred/remacs#788]
After resync w/upstream last night seeing this:

(was all good 24 hours ago, also same problem on fresh clone today of remacs, I've not touched clang but have done some Ubuntu updates this week, ideas?)
```
cargo build --release --manifest-path ../rust_src/Cargo.toml
   Compiling remacs v0.1.0 (file:///home/gb/warez/remacs-wtf-v8/remacs/rust_src)
error: failed to run custom build command for `remacs v0.1.0 (file:///home/gb/warez/remacs-wtf-v8/remacs/rust_src)`
process didn't exit successfully: `/home/gb/warez/remacs-wtf-v8/remacs/rust_src/target/release/build/remacs-f5a2b8cf84118c26/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=EMACS_CFLAGS
cargo:rerun-if-env-changed=SRC_HASH

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Makefile:610: recipe for target '../rust_src/target/release/libremacs_lib.a' failed
make[1]: *** [../rust_src/target/release/libremacs_lib.a] Error 101
```

**Comment by shaleh** [comment]
I suspect the clang dependency has changed and the configure script needs updating.

**Comment by shaleh** [comment]
If you have `LIBCLANG_PATH` set can you get it to work?

**Comment by Wilfred** [comment]
Just to be clear, do you have libclang installed @gaak99?

**Comment by gaak99** [comment]
So oddly enough:
```
apt list -a libclang1
Listing... Done
libclang1/xenial-updates 1:3.8-33ubuntu3.1 amd64
libclang1/xenial 1:3.8-33ubuntu3 amd64
```
which is stock Ubuntu 16.04 I believe. Also 1-5.0 is installed says apt list/show.

But doing a find shows no libclang.so under /usr which I assume it should. I do have a few under my ~/.buildozer/android which I assume have nothing to do with the stock Ubuntu one.

I'll try installing latest libclang.

Thanks.

**Comment by shaleh** [comment]
You need the `-dev` package to build against it

**Comment by gaak99** [comment]
Installed -dev (3.8) and the .so and such are now installed in
```
/usr/lib/llvm-3.8/lib/libclang.so.1
/usr/lib/llvm-3.8/lib/libclang.so

/usr/lib/llvm-3.8/lib/clang/3.8.0/include/stdbool.h
```
The build found libclang this time but not it's header files:
```
   Compiling remacs v0.1.0 (file:///home/gb/warez/remacs-final/remacs/rust_src)
error: failed to run custom build command for `remacs v0.1.0 (file:///home/gb/warez/remacs-final/remacs/rust_src)`
process didn't exit successfully: `/home/gb/warez/remacs-final/remacs/rust_src/target/release/build/remacs-adf5e1008637d80c/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=EMACS_CFLAGS
cargo:rerun-if-env-changed=SRC_HASH

--- stderr
/home/gb/warez/remacs-final/remacs/src/conf_post.h:32:10: fatal error: 'stdbool.h' file not found
/home/gb/warez/remacs-final/remacs/src/conf_post.h:32:10: fatal error: 'stdbool.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Makefile:610: recipe for target '../rust_src/target/release/libremacs_lib.a' failed
```
If I make that a script and add a "-isystem /usr/lib/llvm-3.8/lib/clang/3.8.0/include" the cargo build completes ok here.

But if I try adding that dir for a full clean build like so:
```
./configure
MYCPPFLAGS="-I/usr/lib/llvm-3.8/lib/clang/3.8.0/include" make
```
or edit configure.ac (either of these two)
```
30973:        #REMACSLIB_CFLAGS="-isystem /usr/lib/llvm-3.8/lib/clang/3.8.0/include -pthread" ;;
30974:        REMACSLIB_CFLAGS="-I/usr/lib/llvm-3.8/lib/clang/3.8.0/include -pthread" ;;
```
we get fails like so:
```
   Compiling remacs-lib v0.1.0 (file:///home/gb/warez/remacs-final/remacs/rust_src/remacs-lib)
    Finished release [optimized] target(s) in 51.45 secs
  CCLD     etags
In file included from /usr/include/stdlib.h:958:0,
                 from ../lib/stdlib.h:36,
                 from etags.c:112:
/usr/include/x86_64-linux-gnu/bits/stdlib.h: In function ‘wctomb’:
/usr/include/x86_64-linux-gnu/bits/stdlib.h:90:3: error: #error "Assumed value of MB_LEN_MAX wrong"
````
So it appears adding that clang header dir best be done after the C modules are compiled -- makes sense -- so configure.ac likely needs to be hacked.

Also curious how the llvm header dir is being found ok on other (Linux systems).

**Comment by jaccarmac** [comment]
> Also curious how the llvm header dir is being found ok on other (Linux systems).

It's especially badly-behaved on Gentoo since Gentoo uses its own directory for 64-bit libs. Don't have the energy to solve the problem, @ me and I'll come back around and solve it eventually when this issue stabilizes.

**Comment by gaak99** [comment]
I have a decent workaround. I'll close this tomorrow unless somebody wants to keep it open.

Thanks all.

**Comment by shaleh** [comment]
Until the configure script is updated this should stay open

**Comment by jaccarmac** [comment]
@gaak99 What was the workaround you found? I'd like to knock this out for my setup as well and maybe start on fixing the configuration.

**Comment by jaccarmac** [comment]
Looks like I've fixed the issue by setting `LIBCLANG_PATH` manually. Is it still the plan to set up the configure script to handle this automatically?

**Comment by gaak99** [comment]
@jaccarmac Manually mod ```src/Makefile``` after each ```./configure``` in target ```$(LIBREMACS_ARCHIVE):```

```s,EMACS_CFLAGS="$(EMACS_CFLAGS)",EMACS_CFLAGS="$(EMACS_CFLAGS) -I/usr/lib/llvm-3.8/lib/clang/3.8.0/include"```

your method is better I'll try it next time.

**Comment by db48x** [comment]
Or set `MYCPPFLAGS` when you build, rather than modifying the Makefile:

```
make MYCPPFLAGS=-I/usr/lib/llvm-3.8/lib/clang/3.8.0/include -j16
```

That will insert the include flag in the same place as your modification.

**Comment by shaleh** [comment]
I will try again on my Ubuntu machine tonight. It works on my Mac

**Comment by gaak99** [comment]
Had no luck setting MYCPPFLAGS when I first filed this issue (see above).

Tried it again last night similar fail
```
./configure
...
 make MYCPPFLAGS=-I/usr/lib/llvm-3.8/lib/clang/3.8.0/include -j16
...
  CC       emacsgtkfixed.o
In file included from /usr/include/stdlib.h:958:0,
                 from ../lib/stdlib.h:36,
                 from /usr/include/x86_64-linux-gnu/freetype2/freetype/config/ftstdlib.h:120,
                 from /usr/include/freetype2/freetype/config/ftstdlib.h:3,
                 from /usr/include/x86_64-linux-gnu/freetype2/freetype/config/ftconfig.h:43,
                 from /usr/include/freetype2/freetype/config/ftconfig.h:3,
                 from /usr/include/freetype2/freetype/freetype.h:33,
                 from /usr/include/X11/Xft/Xft.h:40,
                 from xsettings.c:48:
/usr/include/x86_64-linux-gnu/bits/stdlib.h: In function ‘wctomb’:
/usr/include/x86_64-linux-gnu/bits/stdlib.h:90:3: error: #error "Assumed value of MB_LEN_MAX wrong"
 # error "Assumed value of MB_LEN_MAX wrong"
   ^

```

**Comment by nitishch** [comment]
I had the same problem.

I had `libclang.so.1` in `/usr/lib/llvm-6.0/lib`. Only way I could get the compiler pick libclang.so is to do the following

```
sudo ln -s libclang.so.1 libclang.so
export LIBRARY_PATH=$LIBRARY_PATH:/usr/lib/llvm-6.0/lib;
```

I don't think this is the recommended way to deal with libraries but I couldn't find any other way.

**Comment by shaleh** [comment]
Missing `.so` files is usually a sign you did not install a development package along with the standard library package.

**Comment by jaccarmac** [comment]
Am I missing something and the fix suggested by the error doesn't work in some cases? I was worried about this issue but setting that one variable fixes the problem. Changing the build script seems more prone to failure but perhaps I'm just lucky

**Comment by shaleh** [comment]
@nitishch on Ubuntu you most likely missed a clang-dev package.

**Comment by gaak99** [comment]
@jaccarmac do you mean setting LIBCLANG_PATH (suggested by orig fail above)? I just tried it after ```./configure``` and no luck. Same fail as noted in the MYCPPFLAGS workaround (which is not so good as it has to fail once before setting it works ok).

**Comment by jaccarmac** [comment]
@gaak99 Yes that's what I meant.

Thanks for verifying that it doesn't work for everyone, just wanted to make sure we had picked the low-hanging fruit.

**Comment by mikhail-krainik** [comment]
The same it doesn't work with llvm-6.0 and current master branch.

**Comment by shanavas786** [comment]
> this issue happens when clang is not installed (but libclang-dev is)

I have clang-3.8 installed and still have the issue

**Comment by niluxv** [comment]
Strange. For me this only happens when clang is not installed. Updated previous comment.

**Comment by mikhail-krainik** [comment]
Should I add some additional information for reproduce?

**Comment by brotzeit** [comment]
Seems to be solved.

**Comment by piaoger** [comment]
I found this solution is great. It fixed my same issue though it's not related to this project.
Thanks again .....
