### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by gaak99** [Wilfred/remacs#789]
Now for my Windows build problem ...

My up to date master is failing on Appveyor
```
thread 'main' panicked at 'Unable to generate bindings: ()', libcore\result.rs:945:5
make[1]: *** [Makefile:610: ../rust_src/target/release/remacs_lib.lib] Error 101
```
known issue? (or is my config hosed)

**Comment by db48x** [comment]
It very likely couldn't find clang. Install it from http://clang.llvm.org/.

**Comment by db48x** [comment]
wrong button :)

**Comment by gaak99** [comment]
There's a ton of Visual Studio errors too so I suspect the Appveyor default, Visual Studio 2015, is not correct now. I'm trying VS 2017 now...

**Comment by db48x** [comment]
MSVC is not required at all.

**Comment by db48x** [comment]
That's clang emitting error messages that contain the names of header files from MSVC. Clang can't deal with those headers, because they contain MSVC-specific extensions. The solution is to keep the MSVC headers out of your include path.

**Comment by gaak99** [comment]
good info, thanks @db48x. 

I was able to reset
```
HEAD is now at 72f9ca0 Don't run a full build at the C errors stage (#774)
```
to a place where make check is clean (cept for benchmark test false positive). So a least I can test my new junk.

**Comment by brotzeit** [comment]
#970
