### ISSUE TITLE
stdbool not found by cargo

### ISSUE THREAD

**Issue by DaanHoogland** [Wilfred/remacs#791]
Not sure if this is a specific problem with remacs but this is what happened:
I upgraded fedora from 26 to 28 and the installed remacs didn'trun anymore. I pulled latest and rebuild but that fails with this message:
```
   Compiling remacs v0.1.0 (file:///home/dahn/prj/remacs/rust_src)
error: failed to run custom build command for `remacs v0.1.0 (file:///home/dahn/prj/remacs/rust_src)`
process didn't exit successfully: `/home/dahn/prj/remacs/rust_src/target/release/build/remacs-a9c820dad8cea677/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=EMACS_CFLAGS
cargo:rerun-if-env-changed=SRC_HASH

--- stderr
/home/dahn/prj/remacs/src/conf_post.h:32:10: fatal error: 'stdbool.h' file not found
/home/dahn/prj/remacs/src/conf_post.h:32:10: fatal error: 'stdbool.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

make[1]: *** [Makefile:610: ../rust_src/target/release/libremacs_lib.a] Error 101
make[1]: Leaving directory '/home/dahn/prj/remacs/src'
make: *** [Makefile:426: src] Error 2
```
stdbool.h is available and found by g++

I upgraded to latest nightly:
```
[dahn@blimbing remacs]$ rustup toolchain list
stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)
[dahn@blimbing remacs]$ rustc --version
rustc 1.28.0-nightly (01cc982e9 2018-06-24)
```
I did a make clean and ./configure
Where to look next?

**Comment by db48x** [comment]
This error is coming from clang, not gcc or rustc. If you look a few lines up you should see what the EMACS_CFLAGS were set to; that will include the include paths that we tell clang about.

**Comment by shaleh** [comment]
Woah. _RED_ flag.

The Rust version inside the remacs directory should not be 06-24. rust-toolchain file says `nightly-2018-03-01`.

Do not override the rust-toolchain file.

**Comment by db48x** [comment]
That's true, but not relevant to this issue. At the time this error happens, none of the main rust code has been built yet (a few of the utilities have, and the rust version is not so critical for them). Once the clang problem is sorted out, however, it would become a problem.

**Comment by nickdrozd** [comment]
I ran into this problem on Ubuntu 18 and got around it by apt-installing clang. I have no idea why it worked or what the real problem is.

**Comment by DaanHoogland** [comment]
```
sudo dnf install clang
rustup install `cat rust-toolchain`
rustup override set `cat rust-toolchain`
```
does get me past most of my problems here. thanks (still compiling)

**Comment by DaanHoogland** [comment]
```
./configure --with-mailutils --without-pop --prefix /opt/remacs
make
make install
```
went smoothly without any hickups

**Comment by shaleh** [comment]
@DaanHoogland do **not** set the override. Let rustup handle it. This way if we update the rust toolchain expectation your next build will automatically retrieve it.

**Comment by DaanHoogland** [comment]
Ah, I had to set it before way back when on fedora26 so I kept in my comfort. I'll unset it
