### ISSUE TITLE
Accessing menu on macOS sometimes crashes remacs

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#802]
Happens a few times a day, I haven't been able to narrow down what causes it. 99% of times the menu works as expected

**Comment by shaleh** [comment]
"menu"?? What is this thing you speak of?

**Comment by cjohansson** [comment]
The GUI application menu-bar

**Comment by cjohansson** [comment]
I think I get this problem on GNU Emacs as well, I'll try to find a reproducible case for it there and if so create a bug report for it there instead.
