### ISSUE TITLE
abbrev-mode broken?

### ISSUE THREAD

**Issue by gaak99** [Wilfred/remacs#818]
Starting using remacs a few days ago as my main kitchen-sink...

Everything seems to work ok so far except ```abbrev-mode```.

My basic init of it has been working 4evers. It appears in the mode line and listing abbrevs all looks fine. Just silently does not expand. Anything. Ever.

Code running on Linux and master is synced couple days ago plus my file attrs junk.

```make check``` is clean.

Work ok for anybody?

**Comment by gaak99** [comment]
This just in ...

Command ```expand-abbrev``` works ok.

**Comment by shaleh** [comment]
If `expand-abbrev` works what is failing? Could you write a test?

**Comment by gaak99** [comment]
The minor-mode, ```abbrev-mode``` is failing. If the mode is enabled when the ```spc`` bar is typed (or any punctuation I think) it expands the prev text.

I'll take a look at current tests -- I wonder if testing of modes is doable.

**Comment by gaak99** [comment]
No ```abbrev-mode``` test it appears in ```abbrevs-tests.el``` (or anywheres in remacs ```test``` dir).

I tried writing a small snippet as the core of a test but no luck.
Note I have ```abbrev-mode``` enabled globally (all buffers).
Note also the code results are the same here on remacs and emacs 25.3 (only the interactive is diff).
```
;; zt -> tail in my global-abbrev-table
(symbol-value (abbrev-symbol "zt"))
"tail"

(let ((myabrev "zt"))
  (with-temp-buffer			
      (insert myabrev)
      (goto-char 3)
      (insert-char ?!)
      (buffer-substring 1 (point-max))))
"zt!"
``` 
You can see it's not expanded. If "zt!" is typed interactively it is expanded as expected on emacs 25.3 (and fails on current remacs).

```expand-abbrev``` works good.
```
(let ((myabrev "zt"))
  (with-temp-buffer			
      (insert myabrev)
      (goto-char 3)
      (expand-abbrev)
      (buffer-substring 1 (point-max))))
"tail"
```
Anyways my guess is interactive is just different enough to make this test difficult/impossible or I'm missing the trick (which is very possible).

**Comment by shaleh** [comment]
If you can work out a test you can use our git bisect tools to hunt down the commit that broke it.
