### ISSUE TITLE
Crash: 'assertion failed: charpos == bytepos', src/marker.rs:247:13

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/remacs#820]
I was messing with a package that deals with hooks and local variables (see https://github.com/Malabarba/Nameless/pull/25) and Remacs crashed abruptly. The error message:

```
thread '<unnamed>' panicked at 'assertion failed: charpos == bytepos', src/marker.rs:247:13
```

I haven't been able to reproduce it, and I don't remember exactly what I was doing when it happened. Wish I could be of more help :cat2: 

`Remacs 26.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-19`

**Comment by db48x** [comment]
That's going to be fun. Could you run Remacs with RUST_BACKTRACE=1, just in case this happens again? It'll cause it to print a stack trace when it asserts like this, which can be very helpful for tracking down the problem.

**Comment by brotzeit** [comment]
This looks familiar :/

**Comment by brotzeit** [comment]
So what can we do about this ? Is there a way to run it automatically and repeatedly in a debugger until the error occurs ? Or what are other ways to catch non deterministic bugs ?

**Comment by brotzeit** [comment]
Let's reopen an issue if somebody sees it again. I didn't see this error for a long time.
