### ISSUE TITLE
(Feature request) Update with Flymake changes from upstream GNU Emacs

### ISSUE THREAD

**Issue by leungbk** [Wilfred/remacs#840]
`eglot` is a LSP frontend that depends on recent changes to Flymake. The present version of Remacs does not have these changes, so running `M-x eglot` in Remacs gives an error of `flymake--diag is not a struct`.

`flymake--diag` was renamed from `flymake-ler` at https://github.com/emacs-mirror/emacs/commit/ae64bf12a865d5d40b7541af0da9b971936994ec.

**Comment by Wilfred** [comment]
We do periodically sync up with upstream GNU Emacs, but we've fallen behind a little.
