### ISSUE TITLE
Not copy but improve and extend

### ISSUE THREAD

**Issue by ayrat555** [Wilfred/remacs#841]
Firstly, I don't want to be rude and I just want to describe my concerns and suggestions about the project.

There are tendencies to rewrite everything in Rust and I'm pretty cool about it. But Emacs has stable C code base and instead of rewriting it,  Rust can be used to extend Emacs and resolve some of its problems

Emacs is single threaded. Rust's programming idioms fit perfectly for multithreaded programming and can be used to extend emacs with C bindings.

Emacs Lisp is cool but not perfect. I think a new language can be written extending Elisp and adding new features (modules etc)

Also, some new features can be written in Rust.

**Comment by db48x** [comment]
Absolutely. Just remember that while Rust's lifetime system makes multi-threaded programs easier, it only works if the whole program is written in Rust.

**Comment by shaleh** [comment]
And a multi threaded Rust extension will still be blocked by the Emacs single threaded flow.

**Comment by cjohansson** [comment]
I think that going through the GNU Emacs C-code and converting it to Rust potentially offers many opportunities that may not be predicted. Improved knowledge of Emacs architecture, extensions, optimizations, improved maintainability, improvements, forks etc

**Comment by harryfei** [comment]
FWIW, I am starting a work to use `webrender` as a new GUI backend in `remacs` recently. :smile: I think the code porting is necessary because it will be harder(even impossible) to achieve this work without those ported codes.

 https://github.com/harryfei/remacs/commits/webrender

**Comment by ayrat555** [comment]
Thanks. I think the project's readme `Why Rust?` should be changed. Currently there only common rust features are described.
