### ISSUE TITLE
eww just outputs \213

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#842]
**Steps to reproduce**:
* `src/remacs -Q`
* `M-x eww`
* `﻿﻿https://github.com/Wilfred/remacs` (return)

**Expected result**:
GitHub page

**Actual result**:
\213

**Environment**:
* macOS 10.13.5
* GIT head `master port force_mode_line_update (#817)` ([ac7975c19fad158629788cf6d89ad36e3933fe91](https://github.com/Wilfred/remacs/commit/ac7975c19fad158629788cf6d89ad36e3933fe91))

**Comment by cjohansson** [comment]
Yes, I'll do that later

**Comment by cjohansson** [comment]
Here's the result:

```
99c5874981672ad1e6b0a2c1160a992b6fac57ca is the first bad commit
commit 99c5874981672ad1e6b0a2c1160a992b6fac57ca
Author: Harry Fei <tiziyuanfang@gmail.com>
Date:   Thu Jul 26 15:33:10 2018 +0800

    Port zlib_available_p and zlib_decompress_region (#819)

:100644 100644 38e9d7263ce1b2bc19722269c4897b8d95c15c06 ab1e9701fdab14b36c73461aa1ffb483bfd587ea M	configure.ac
:040000 040000 3bab52b46783b8f62213520834070efa635832b3 28f62180077a70abd6fae80e6f4ea51ba78d961d M	lib
:040000 040000 17bb3be381a25e406fd9e3b29c93469215be5163 ba946d272b76e0d340b14b3cd1d39b14609f806e M	rust_src
:040000 040000 bd94a2b8c5051d81ced1ae88b33397ab2717f639 c8232a4d5d11dc779c421e7abcc112050a4fcc0b M	src
:040000 040000 0f7ec839893e3e7ab647d935cf813eff1d331c6a 99d2a56b29167f8ea89a4c6f6246fd154d620531 M	test
bisect run success
```

So it's something in [this one](https://github.com/Wilfred/remacs/commit/99c5874981672ad1e6b0a2c1160a992b6fac57ca)

**Comment by cjohansson** [comment]
Tried different things, can't really say why `https://news.ycombinator.com/` works but `https://github.com/`doesn't work. Both use `Content-Encoding: gzip` and `TLS`..

**Comment by harryfei** [comment]
This commit is from me. If I have time, I will check this issue.

**Comment by harryfei** [comment]
Fixed in #843.

**Comment by shaleh** [comment]
@cjohansson I jut merged Harry's fix. Please confirm and close.

**Comment by cjohansson** [comment]
Can't build remacs at the moment, will do when I get to my other computer. I get a weird compilation issue on macOS that is unrelated to this issue, I had it before as well, but it's only present at one of my macOS computers.

```
make[3]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../admin/grammars all EMACS="../../src/bootstrap-emacs"
make[3]: Nothing to be done for `all'.
Directories for loaddefs: . ./calc ./calendar ./cedet ./cedet/ede ./cedet/semantic ./cedet/semantic/analyze ./cedet/semantic/bovine ./cedet/semantic/decorate ./cedet/semantic/symref ./cedet/semantic/wisent ./cedet/srecode ./emacs-lisp ./emulation ./erc ./eshell ./gnus ./image ./international ./language ./leim ./leim/ja-dic ./leim/quail ./mail ./mh-e ./net ./nxml ./org ./play ./progmodes ./textmodes ./url ./vc
  GEN      loaddefs.el
Loading macroexp.elc...
Invalid time specification
make[2]: *** [loaddefs.el] Error 255
make[1]: *** [../lisp/loaddefs.el] Error 2
make: *** [src] Error 2
```

**Comment by cjohansson** [comment]
Working now, closing
