### ISSUE TITLE
remacs freezes with 100% CPU in c++-mode

### ISSUE THREAD

**Issue by Hi-Angel** [Wilfred/remacs#846]
# Steps to reproduce

1. Open `remacs -Q`
2. Execute <kbd>C-x</kbd>+<kbd>f</kbd> `/tmp/test.cpp`
3. try to type:

	```c++
	template<T
	```

# What should happen

You successfully typed the text

# What actually happens

after the `template<` typed, remacs freezes with high CPU load.

# Additional info

* remacs build from commit `315d5f1016`
* problem does not happen with vanilla `emacs`
* in some obscure circumstances *(specifically, when remacs allowed to load init file, i.e. being ran without `-Q`)* remacs in addition to high CPU load takes away all RAM, thus freezing the system.

*edit: reduced the testcase*

**Comment by Hi-Angel** [comment]
Actually, I just figured that to reproduce it's enough to only type the `template<` part, nothing else matters.

**Comment by Hi-Angel** [comment]
FWIW I tried bisecting, but haven't got too far. It's still reprodicible at `315d5f1016~150`, but `315d5f1016~175` and `315d5f1016~200` simply doesn't compile.

I'm also wondering, how did I manage to type code at all with such a vivid bug. I think, it could be caused by some upgrade. E.g. rust is using LLVM, and recently [there was a bug at LLVM's linker fixed](https://github.com/electron/electron/issues/13972#issuecomment-411532741); although, I've upgraded llvm to latest, which should contain the fix, plus I'm my glibc has a workaround, so… I dunno.

I'll check at Monday if it's reprodicible at work.

**Comment by Hi-Angel** [comment]
> I'll check at Monday if it's reprodicible at work.

Nvm. It's weird, but I can reproduce it there either. As for "how did I manage to code" — well, for some reason it's not reproducible in a filled c++ file.

**Comment by Wilfred** [comment]
It looks like an infinite loop in `c-restore-<>-properties`. I'm not sure why yet.

**Comment by Hi-Angel** [comment]
> However, `C-g` does enable me to carry on typing. Are you seeing the same thing?

Thanks, I didn't try it before — yes, it works the same for me.

Btw, I found what code makes `remacs` to leak memory when this loop happens, it's this one:


```lisp
(setq gc-cons-threshold most-positive-fixnum)
(run-with-idle-timer 2 t (lambda () (garbage-collect)))
```

This, basically, enables garbage collection to happen only on 2 seconds of inactivity *(because it's expensive)*.

So, when remacs hanged in the loop, took a lot of memory, and I press <kbd>C-g</kbd> to quit the loop: remacs does not give the memory back, not even upon manually running <kbd>C-x</kbd> `garbage-collect`.

It seems like this infinite loop uncovers some other bug, a memory leak.

**Comment by Wilfred** [comment]
@Hi-Angel please open a separate bug regarding any memory leaks.

I'm not sure that's a Remacs bug: we haven't changed any of the allocation logic from upstream, but happy to have a look :)

**Comment by agraven** [comment]
I'm not able to reproduce this in current master (`e2b0d31902f80dabe7a4eb0cdf27bf6acb11b8a7`). is anyone else?

**Comment by Hi-Angel** [comment]
@agraven thank you for the update! I just built and tested latest remacs, and I can no longer to reproduce it. I guess it's fixed.
