### ISSUE TITLE
Remacs does't allow division by zero (float number math)

### ISSUE THREAD

**Issue by harryfei** [Wilfred/remacs#847]
In vanilla Emacs:
* (/ 0 0) gets `Arithmetic error`
* (/ 0.0 0) gets `-0.0e+NaN`

In Remacs:
* (/ 0 0) gets `Arithmetic error`
* (/ 0.0 0) gets `Arithmetic error`

I think we need to keep the same logic as vanilla Emacs.

**Comment by Wilfred** [comment]
Agreed, that's a bug.
