### ISSUE TITLE
remacs can leak memory (large amounts, Gigabytes)

### ISSUE THREAD

**Issue by Hi-Angel** [Wilfred/remacs#854]
# Overview

This bug was found as part of another one. [I was asked to report it separately](https://github.com/Wilfred/remacs/issues/846#issuecomment-419271096). There's hypothesis that whilst the linked bug is remacs-specific, but the memory leak might be in Emacs too.

Basically, reproducing it requires disabling garbage collector, and then triggering the [infinite loop bug](https://github.com/Wilfred/remacs/issues/846). remacs starts quickly filling the memory, then you make it quit with <kbd>C-g</kbd>. And then executing <kbd>M-x</kbd><kbd>garbage-collect</kbd> **does not** make it free memory.

# Steps to reproduce

1. Run `remacs -Q` built from commit `315d5f1016` *(actually, any commit where the #846 is present)*.
2. Eval <kbd>M-:</kbd> `(setq gc-cons-threshold most-positive-fixnum)` *(this basically makes GC to never run automatically)*.
3. Execute <kbd>C-x</kbd>+<kbd>f</kbd> `/tmp/test.cpp`
4. Type *(this will make remacs to freeze and to start very quickly consuming the RAM)*:

	```c++
	template<T
	```
4. Press <kbd>C-g</kbd> to make remacs quit the infinite loop.
5. Check amount of memory remacs took. E.g. with `smem -kc "name pss" | grep remacs`. Then type <kbd>M-x</kbd><kbd>garbage-collect</kbd> to make remacs to free the memory.

# What should happen

Amount of memory remacs takes should reduce dramatically

# What actually happens

Amount of memory remacs takes does not change

 Real-world significance is that it's [a common practice](https://emacs.stackexchange.com/questions/34342/is-there-any-downside-to-setting-gc-cons-threshold-very-high-and-collecting-ga) to make GC to be only run only on inactivity, because it's expensive CPU-wise.

A possible problem outside of making GC to run on inactivity is just a slow leak.

**Comment by Hi-Angel** [comment]
So, I did dig into it for a bit *(with valgrind and such)*, and I suspect it might simply be that the revision that REmacs is using is buggy. Because there have been dozens of patches changing the `src/alloc.c` file in Emacs master compared to REmacs master.

I tried to extract the patches to see if I can quickly apply them, but I can't figure out the command. I expected this one to work `git format-patch -1 $(git rev-list 5172fa02ccc..HEAD src/alloc.c) --stdout > /tmp/1.patch`, but for some reason it generates a single random patch.

**Comment by shaleh** [comment]
Try just running `git diff`. I rarely fuss with format patch.

Make sure the hash you use is an emacs hash from an emacs git checkout.

**Comment by Hi-Angel** [comment]
Okay, the correct command was `git format-patch --stdout --full-diff 5172fa02ccc -- src/alloc.c`. However, for applying the patches I ran into a bunch of complex conflicts, and can't say I'm motivated enough to solve them, given it's not even 100% that this bug was fixed.

> Try just running `git diff`. I rarely fuss with format patch.

I doubt this would work — commits touching the alloc.c are touching other files as well, and it's likely if I only change the alloc.c it just won't compile; and even if it will compile, there could be other bugs because of that.

**Comment by shaleh** [comment]
Thanks for the detective work.

**Comment by agraven** [comment]
Since #846 has been fixed, should this be closed as well? Or should we err on the side of caution and assume that the underlying bug which was triggered by #846 might still be around?

**Comment by Hi-Angel** [comment]
Well, I thought about that. On one hand, they're distinct entities, it's just that the fixed bug was the only known way to reproduce that.

On the other hand, now fixing memory leak requires digging into git history, checking out the state where the prev. bug was present; and also that since there's no other way to reproduce memory leak, it's unclear whether it was fixed or not without researching the underlying cause…

All in all, I don't think anybody at all would be interested to go through these troubles, so let's just close it. If I happen to find another way to reproduce a memory leak, I'll just report it separately.
