### ISSUE TITLE
[Proposal] Delete all x-toolkit except `gtk3`.

### ISSUE THREAD

**Issue by harryfei** [Wilfred/remacs#863]
Currently, Emacs has quite a few x-toolkit choices for Linux platform.
* gtk
* gtk2
* gtk3
* lucid
* motif
* no-toolkit

Shall we just keep the `gtk3` and remove all the other `x-toolkit`? The related code will be simpler and cleaner. I believe it will be helpful for our porting.

**Comment by db48x** [comment]
It certainly would simplify things, but... I don't think we should do it.

**Comment by shaleh** [comment]
Can you give reasons why not?

Which of the toolkits are in use on modern Linux?

**Comment by shaleh** [comment]
I can see the argument for keeping gtk2 and 3. Lucid, gtk1, and motif are ancient.

**Comment by Wilfred** [comment]
I did actually build a GUI Emacs on Fedora 7 last year without gtk, but it wasn't as nice and I chased down the missing gtk bits.

I think this is reasonable. As long as it doesn't cause problems on other platforms, it would certainly make the code simpler.

**Comment by harryfei** [comment]
AFAIK, Emacs use win32 raw api to implement it's gui.

**Comment by Wilfred** [comment]
It will also increase the number of conflicts when we merge updates from GNU Emacs, because any change to the removed backends will conflict.

It's still a nice simplification I think.

**Comment by harryfei** [comment]
I will work on this during the next days if no more opposite opinion.

**Comment by harryfei** [comment]
Should we delete the `gtk2` or not?

**Comment by shaleh** [comment]
Gtk2 is  likely still viable.

**Comment by db48x** [comment]
> @db48x before we tell Harry to present a PR, do you have concerns?

I don't think we should do it because it would be quite difficult to undo it later, and because it might not make our job any easier (merge conflicts, as mentioned), and because we shouldn't delete things merely to make our job more convenient.

**Comment by brotzeit** [comment]
I remember that we removed DOS support last year. Did this make merges more complicated ?

**Comment by Wilfred** [comment]
Removing DOS slightly increased conflicts, but the DOS logic is more coupled to the Windows logic so there's more code churn. Most of these old toolkits rarely see any changes, so I'm not terribly concerned about increasing conflicts. The most impactful change was removing changelog files, which always conflict (trivial to fix though).

Removing these toolkits makes the code smaller, easier to understand and easier to port. It also removes a ton of kludges, such as:

```c
#include <X11/CoreP.h>		/* foul, but we need this to use our own
				   window inside a widget instead of one
				   that Xt creates... */
```

```c
/* Install an asynchronous timer that processes Xt timeout events
   every 0.1s as long as either `toolkit_scroll_bar_interaction' or
   `popup_activated_flag' (in xmenu.c) is set.  Make sure to call this
   function whenever these variables are set.  This is necessary
   because some widget sets use timeouts internally, for example the
   LessTif menu bar, or the Xaw3d scroll bar.  When Xt timeouts aren't
   processed, these widgets don't behave normally.  */
```

```c
#ifdef HAVE_X11XTR6
    /* I think this is to compensate for XtSetLanguageProc.  */
    fixup_locale ();
#endif
```

```c
      /* Something is fishy here.  When using Motif, starting Emacs with
	 `-g -0-0', the frame appears too low by a few pixels.
```

```c
      /* We use an estimate of 30 chars per line rather than the real
         `portion' value.  This has the disadvantage that the thumb size
         is not very representative, but it makes our life a lot easier.
         Otherwise, we have to constantly adjust the thumb size, which
         we can't always do quickly enough: while dragging, the size of
         the thumb might prevent the user from dragging the thumb all the
         way to the end.  but Motif and some versions of Xaw3d don't allow
         updating the thumb size while dragging.  Also, even if we can update
         its size, the update will often happen too late.
         If you don't believe it, check out revision 1.650 of xterm.c to see
         what hoops we were going through and the still poor behavior we got.  */
```

```c
static void
hack_wm_protocols (struct frame *f, Widget widget)
```

```c
	  /* Bloodcurdling hack alert: The Lucid menu bar widget's
	     redisplay procedure is not called when a tip frame over
	     menu items is unmapped.  Redisplay the menu manually...  */
```

**Comment by harryfei** [comment]
I admit the potential conflict with upstream merging because we change the code location in several files (by deleting so many codes). So I will respect you guys' final conclusion.

I believe that, cleaning (and even reranging) the legacy code before poring them can push our process more quickly.

**Comment by harryfei** [comment]
FWIW, I tried to find more methods or tools to boost our porting process. Finally found [c2rust](https://c2rust.com/).

What's your opinion on it?

**Comment by shaleh** [comment]
https://github.com/immunant/c2rust/wiki/Known-Limitations-of-Translation

That sounds like it will be less helpful.

**Comment by shaleh** [comment]
Resolved.
