### ISSUE TITLE
Consider disabling appveyor

### ISSUE THREAD

**Issue by Wilfred** [Wilfred/remacs#883]
It's currently failing the build, so it's confusing for new contributors. They only need to check that Travis is still green.

It'd be great to have a working appveyor setup, but at this point I don't think it's worth running on every pull request.

**Comment by harryfei** [comment]
Just for curiosity. What is blocking the Windows builds?

**Comment by db48x** [comment]
The AppVeyor build VMs have MSVC installed on them. We don't use MSVC at all, but the include paths muck up the build that bindgen does.

**Comment by shaleh** [comment]
Agreed. appveyor is doing us no good currently. Since we cannot provide an image to run on it is not clear how we could use it properly.

**Comment by Wilfred** [comment]
I've disabled the webhook, it should stop appearing on PRs.

**Comment by brotzeit** [comment]
Maybe open a new issue ?
