### ISSUE TITLE
Can't build GNU Emacs or Remacs on macOS 10.14 Mojave - fatal error: 'libxml/tree.h' file not found

### ISSUE THREAD

**Issue by cjohansson** [Wilfred/remacs#886]
Might be off-topic but I get this error on macOS 10.14 Mojave, after running `make`:

`xml.c:23:10: fatal error: 'libxml/tree.h' file not found`

Both `xcode-select --install` and `brew install libxml2` is installed. I get the same error on GNU Emacs as well. Do you get this error or do you know about a solution to it?

I didn't get this error before updating macOS to Mojave.

**Comment by shaleh** [comment]
I have bit upgraded yet.

**Comment by socketwiz** [comment]
I also upgraded to Mojave and I ran into this problem.  I solved it by using [homebrew](https://brew.sh/) to install `libxml2`:

```shell
$ brew install libxml2
```
If you have already installed `libxml2` then you can see what environment variables it wants you to set by doing `brew info libxml2`.  Here is what it said on my machine.

```shell
$ export LDFLAGS="-L/usr/local/opt/libxml2/lib"
$ export CPPFLAGS="-I/usr/local/opt/libxml2/include"
$ export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
```

Once you have your environment updated with `libxml2` then you need to re-run `configure` so it can pickup `libxml2` from the environment you've setup.

```shell
$ ./configure --enable-rust-debug
```

Now you should be able to re-run make.  It built to completion for me when I did this.  It took just over 2 hours on my machine.

```shell
$ make
```

**Comment by db48x** [comment]
> $ export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"

This is all you need. The `configure` script will run `pkg-config` to find out what to add to `LDFLAGS` and `CPPFLAGS`.

**Comment by cjohansson** [comment]
Yes it's working @db48x , I have this in my `~/.bash_profile` now:

```bash
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/opt/X11/li
    b/pkgconfig:$PKG_CONFIG_PATH
```

Running `brew link libxml2` gives that as an advice as well but I only tried the first two advices (LDFLAGS and CPPFLAGS) which didn't work.

I'm a bit curious why the built-in libxml2 from Xcode located at `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2/` doesn't work anymore. `xcode-select --install` was the only requirement before Mojave but now it's not enough anymore..

**Comment by shaleh** [comment]
@cjohansson maybe the Xcode version is not in `PKG_CONFIG_PATH`?

**Comment by cjohansson** [comment]
The Xcode version does not seem to have a pkgconfig directory and setting the environment variables `LDFLAGS` or `CPPFLAGS` seems to have no effect. So `brew install libx2ml` and `export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"` seems like the only option at the moment. It's the same when building GNU Emacs

**Comment by brotzeit** [comment]
Can we close this issue ?

**Comment by cjohansson** [comment]
Yes sure but we should probably update the build instructions for macOS with the extra `brew install libxml2; export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"`

**Comment by shaleh** [comment]
@brotzeit I re-opened this so you can close it after updating the docs.

**Comment by Leimy** [comment]
Should be fine to use the Xcode headers... you just need to copy them out, and Apple provided a package for this. They hid it well. 

 ```cp /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg ~/Desktop/```

Then launch it from your desktop. After, I'm able to build Emacs at least. Haven't tried Remacs yet.

**Comment by shaleh** [comment]
@Leimy if this work, can you submit a PR to update the our docs?

**Comment by Leimy** [comment]
Well it works for Emacs. Have not tried REmacs yet. I might get around to that eventually but I feel like someone more involved with the project may beat me to it.

**Comment by shaleh** [comment]
Many of us hacking on remacs have not upgraded yet. I know I haven't.

**Comment by cjohansson** [comment]
I tested this and it works, I was able to build using this command

```
export PKG_CONFIG_PATH="/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg" && cd ~/Documents/remacs/ && git pull origin master && rustup update `cat rust-toolchain` && ./autogen.sh && ./configure && make clean && make && make install;
```

so there is no need for installing libxm2 via brew, I'll update the docs later

**Comment by cjohansson** [comment]
It seems it was a false positive, but doing `open Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` before building remacs works

**Comment by nicola** [comment]
this file does not exist anymore in 10.15 :(

**Comment by denis631** [comment]
@nicola same for me. Did you somehow fix the issue?

**Comment by bistack** [comment]
export LIBXML2_CFLAGS=`xml2-config --cflags`
export LIBXML2_LIBS=`xml2-config --libs`
./configure
make

see :
https://github.com/veshboo/emacs/issues/1#issuecomment-352239375
