### ISSUE TITLE
Remacs blog update

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#898]
I noticed that the last blog update was a year ago. The code base has changed a lot since then. Especially bindgen is a major improvement. @Wilfred seems busy lately. Is anybody motivated to write a summary ? I would do it, but I don't have the technical understanding.

**Comment by brotzeit** [comment]
@db48x already wrote about the improvements of `lisp_fn` http://db48x.net/rust-remacs-2018/.

Maybe we could add some lines about the files that we have removed and the most important improvement, bindgen. I think  #885 is also worth mentioning.

Any idea where we could put the article ? It would be nice if it could be reviewed before it becomes public. I don't know if that's possible.

**Comment by Wilfred** [comment]
I'm very happy to review anything if someone want to write a post, or I might have a chance in a week or two to write an update (or both!)

We could just put the article on a private github gist or something.

**Comment by Wilfred** [comment]
> @db48x already wrote about the improvements of lisp_fn http://db48x.net/rust-remacs-2018/.

Awesome! I've put it on https://www.reddit.com/r/remacs/ too.

**Comment by brotzeit** [comment]
:+1:
