### ISSUE TITLE
magit emacsclient

### ISSUE THREAD

**Issue by izahn** [Wilfred/remacs#92]
I'm just trying out remacs, and almost everything seems to work properly. The only issue I've noticed so far is that `magit` complains that it can't find `emacsclient`
 
         Warning (with-editor): Cannot determine a suitable Emacsclient
         Determining an Emacsclient executable suitable for the
          current Emacs instance failed.  For more information
          please see https://github.com/magit/magit/wiki/Emacsclient.

I'm using the Archlinux package distributed through the AUR, so it's possible this is a packing issue. Anyone else see this? If so, any solution or workarounds?

**Comment by izahn** [comment]
Oh, I see there is a `remacsclient` executable. I looked but didn't find it earlier. I just set

```
  (when (executable-find "remacsclient")
    (setq with-editor-emacsclient-executable (executable-find "remacsclient")))
```
And everything seems to work fine.

**Comment by PythonNut** [comment]
@izahn I can't seem to commit with `magit` and `remacs -Q` with your workaround, does this happen to you as well?

**Comment by izahn** [comment]
It seemed to work with the version on remacs I had compiled at the time, but I also can't comment using a more recent build. Haven't had time to look into it yet.

**Comment by PythonNut** [comment]
I'll open a new issue for it.
