### ISSUE TITLE
Port time-add, time-subtract

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/remacs#932]
From `editfns.c`

```c
DEFUN ("time-add", Ftime_add, Stime_add, 2, 2, 0,
       doc: /* Return the sum of two time values A and B, as a time value.
A nil value for either argument stands for the current time.
See `current-time-string' for the various forms of a time value.  */)
  (Lisp_Object a, Lisp_Object b)
{
  return time_arith (a, b, time_add);
}

DEFUN ("time-subtract", Ftime_subtract, Stime_subtract, 2, 2, 0,
       doc: /* Return the difference between two time values A and B, as a time value.
Use `float-time' to convert the difference into elapsed seconds.
A nil value for either argument stands for the current time.
See `current-time-string' for the various forms of a time value.  */)
  (Lisp_Object a, Lisp_Object b)
{
  return time_arith (a, b, time_subtract);
}
```

**Comment by JuanPotato** [comment]
Hi I'd like to take this up, but I'm pretty new to mixing C and Rust. If I'm just porting those two functions how do I go about calling `time_arith`? If I'm porting `time_arith` too I'm not sure how to handle `lisp_time`. Would love to learn more while contributing

**Comment by shaleh** [comment]
Any exported C function can be called from Rust. If the C function is `static` you need to remove the `static` and put a forward declaration in a header file in src/.

**Comment by shaleh** [comment]
Welcome to the project. Don't worry about being new to C or Rust. We can help answer questions in a PR and in our Gitter channel.

If you get stuck just post what you have and label it Needs Help.

**Comment by brotzeit** [comment]
@JuanPotato It seems @bb010g was faster.

**Comment by JuanPotato** [comment]
Well at least I have something to learn off of
