### ISSUE TITLE
Inline methods

### ISSUE THREAD

**Issue by brotzeit** [Wilfred/remacs#954]
While cleaning the code base, I noticed that we don't use inline macros consistently. Where does it make sense to use it and where not ? I have no idea. But we should have a guide line.

**Comment by harryfei** [comment]
I suggest to avoiding use any manual inline. Let the rust compiler do that automatically. :smile:

**Comment by shaleh** [comment]
Because today the Rust code is a library most of the inlining is ignored. Once the compiler can do better analysis inlining will matter.

I agree with Harry, we should just drop the inline requests for now.
