### ISSUE TITLE
Proposal: make `emacs_abort` local to C

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#976]
The porting guide suggests using `panic!` instead. However, `emacs_abort` is available in Rust thanks to bindgen. What we could do is remove emacs_abort from the header and put a declaration at the top of any C files using it.

**Comment by brotzeit** [comment]
I had the same idea some time ago, but I forgot to ask :)

**Comment by shaleh** [comment]
I have a git hook which prevents me from using emacs_abort.

**Comment by harryfei** [comment]
Maybe we can skip this function in the bindgen configuration (located in `build.rs`?).

**Comment by shaleh** [comment]
Thanks @nickdrozd for picking this one up.
