### ISSUE TITLE
Porters, I started a tool. Feedback requested.

### ISSUE THREAD

**Issue by shaleh** [Wilfred/remacs#993]
I made this tool: https://gist.github.com/shaleh/c84d905b0bc755163beea8269be00f1d

It will start a port of a C function or DEFUN to Rust. It tries to handle adding the right bits for the `lisp_fn` macro. It also tries to convert C types to Rust types. Currently it does not know many types.

My intent is to validate the approach and then port this to a rustize-emacs elisp package for us to use.

**Comment by brotzeit** [comment]
It would be convenient if you could just pass the function as a string to the script.

**Comment by jaccarmac** [comment]
Looks like the `rustize` function takes a string, the command line handling just is set up to read from a file handle.

**Comment by shaleh** [comment]
`M-|` passes the current region to the script on stdin. Passing the C code on the command line directly is really not worth it.

Once we have hammered out the behaviour I plan to port it to Elisp and then ya, it will just take a string and the interactive version will take a region.

**Comment by shaleh** [comment]
If one of you wants to know out a elisp package, go for it. Python is my native tongue.

**Comment by nickdrozd** [comment]
Just tried this thing out and it works pretty well. Can you put it up in a PR to get it into Git? It would be nice to have some Elisp to do it, but this is definitely good enough until then.

**Comment by shaleh** [comment]
Will do @nickdrozd thanks for testing it.

**Comment by shaleh** [comment]
I have committed this to rust_src/admin. Enjoy all.

**Comment by brotzeit** [comment]
Can we close this ?

**Comment by shaleh** [comment]
Drat, I clicked comment instead of close & comment last time.
