### ISSUE TITLE
Error running timer ‘blink-cursor-timer-function’: (wrong-number-of-arguments #<subr internal-show-cursor-p> 0)

### ISSUE THREAD

**Issue by nickdrozd** [Wilfred/remacs#996]
This error is thrown every time the cursor tries to blink, which is often.

`Remacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-11-02`

**Comment by nickdrozd** [comment]
Looks like the optional argument was left off from `internal_show_cursor_p`.

**Comment by shaleh** [comment]
yep, that needs a min="0". I wrote my porting tool for a reason.

We could also have a linter which reads the diff, finds any DEFUNs and validates the Rust lisp_fn.

**Comment by shaleh** [comment]
I have already written the C DEFUN parser. It is in the rustize-emacs tool. So this is not too much more work.
